### ISSUE TITLE
[QUESTION] 메이크샵 구매전환 이벤트 스크립트 변수 문의

### ISSUE THREAD

**Issue by innobrand** [daangn/karrot-conversion-tracker-tool-support#10]
안녕하세요 담당자님, 변수관련 문의드립니다.
호스팅사는 메이크샵 사용하고 있구요. 메이크샵 담당자님들께 확인해보니 제공하는 모듈 및 변수 가이드라인이 없고
변수를 확인하기 위해서는 아래 정보가 필요하다고 하십니다. 

1. 주문완료 페이지 내에 등록되어있는 소스들 중에서 매칭값을 찾아야 하는건지
2. 메이크샵의 가상태그로도 수집이 가능한지
3. 상품id가 정확히 어떤 값을 말하는지

구매전환 이벤트 제외하고 방문, 상세페이지 조회, 회원가입은 정상 수집되고 있습니다.

**Comment by Gummybearr** [comment]
안녕하세요 :) 
1. 일반적으로는 구매자가 실제로 주문한 상품의 아이디를 이용하시기를 권장드리고 있습니다.
2. 메이크샵의 동작을 잘 알지못하여 이는 답변이 어려우나, 내부적으로 스크립트가 동작할 경우 가상태그로도 수집이 가능합니다.
3. 1번 답변에 있는 것처럼 구매자가 실제로 주문한 상품의 아이디를 권장하고 있습니다.

구매 전환 이벤트만 들어오지 않는다면 스크립트에 콤마가 빠져있는지 확인을 부탁드립니다.
```js
products': [{ 'id': '{$order_id}', ...후략
```
문제가 계속될 경우 위 이슈에 답변을 달아주세요.

감사합니다.

**Comment by Gummybearr** [comment]
2주간 별도의 답변이 있지는 않아서 닫을게요 문제가 있다면 다시 열어주세요
