### ISSUE TITLE
[QUESTION] 카탈로그 구매 전환 트래킹 문의

### ISSUE THREAD

**Issue by 72011** [daangn/karrot-conversion-tracker-tool-support#100]
안녕하세요.

당근 전환 추적 관리 도구에서 방문과 구매 모수가 정상적으로 수집되고 있음에도 불구하고
대시보드 상에서는 전환수가 확인되지 않아 문의드립니다.

트래픽 캠페인은 스마트 스토어 랜딩인 점을 고려해 전환수가 트래킹되지 않는 것이 맞지만,
카탈로그는 자사몰 피드URL을 통해 집행 중이므로 내부적으로 확인 한번 부탁드리겠습니다.

**Comment by extJo** [comment]
광고주 ID 부탁드립니다

**Comment by 72011** [comment]
2889652 입니다.

**Comment by extJo** [comment]
> 대시보드 상에서는 전환수가 확인되지 않아 문의드립니다.

광고 대시보드 말씀이실까요? 전환이 잡히는걸로 보입니다.
다만 픽셀은 베타로 오픈된 상태여서 전환 수입에 대해서 개선중에 있습니다
