### ISSUE TITLE
[QUESTION] 회원가입 이벤트 스크립트 미작동 문의

### ISSUE THREAD

**Issue by bgpark-ft** [daangn/karrot-conversion-tracker-tool-support#101]
광고주 ID : 3040650

안녕하세요.
현재 전문가모드로 광고 운영 중이며, 스크립트는 GTM을 통해 아래와 같이 설치하여 운영 중입니다.

- 공통 스크립트
- 잠재고객 수집
- 서비스 신청
- 회원가입

그런데 다른 모든 스크립트는 정상적으로 발동을 하는데, 회원가입 스크립트의 경우 추적이 되지 않고 있습니다.

잠재고객 수집, 서비스 신청의 경우 특정 버튼 클릭 혹은 맞춤 스크립트로 특정 이벤트가 발동될 경우 실행되도록 설정해 둔 상태인데요. 회원가입 이벤트의 경우 회원가입 완료 페이지에 대해 페이지뷰가 발생 시 발동하도록 설치해 둔 상태입니다. 

회원가입 이벤트에 설정해둔 트리거로 메타나 다른 매체에서 설정해 둔 이벤트는 정상적으로 발동이 되며, GTM 상에서 테스트 시에도 당근 회원가입 이벤트 태그가 정상적으로 발동되는 것이 확인되나, 당근마켓 전환 추적 관리 상에서만 카운팅이 되지 않고 있습니다. 

혹이 어떤 문제가 있는 것일지 문의드립니다. 
![당근문의1](https://github.com/user-attachments/assets/7111ca60-87bb-4eb7-b8b0-d8a4127df9b1)
![당근문의2](https://github.com/user-attachments/assets/118b8043-a296-44ac-9272-120f5d62b41e)
![당근문의3](https://github.com/user-attachments/assets/394646eb-949b-4334-8037-fccc7c193abf)

**Comment by extJo** [comment]
GTM으로 설정하는경우, 공통스크립트도 같이 설치해주시길 바랍니다

**Comment by bgpark-ft** [comment]
공통 스크립트의 경우 아래 이미지와 같이 별도의 태그로 설치가 완료되어 있는데요. 혹시 회원가입 이벤트 설치 시 공통 스크립트의 코드를 같이 추가하여 설치해야 한다는 말씀이실까요? 
![당근문의4](https://github.com/user-attachments/assets/7e04a089-0a27-4b82-908c-87d6bfbdcf0a)

**Comment by bgpark-ft** [comment]
> GTM으로 설정하는경우, 공통스크립트도 같이 설치해주시길 바랍니다

공통 스크립트의 경우 아래 이미지와 같이 별도의 태그로 설치가 완료되어 있는데요. 혹시 회원가입 이벤트 설치 시 공통 스크립트의 코드를 같이 추가하여 설치해야 한다는 말씀이실까요?
![당근문의4](https://github.com/user-attachments/assets/db020489-e60a-4bd6-a2b9-6e2470311a3b)

**Comment by extJo** [comment]
넵 맞습니다.

**Comment by bgpark-ft** [comment]
> 넵 맞습니다.

혹시 아래 이미지와 같이 공통스크립트 + 회원가입 이벤트 함께 기재하면 될지 문의드립니다. 

![Uploading 당근문의5.png…]()
추가로 현재 공통스크립트 없이 이벤트 스크립트만 설치하여 정상적으로 데이터 수집중인 타 이벤트 스크립트(잠재고객, 서비스 신청)에 대해서도 동일하게 공통스크립트 함께 기재하여야 할지 문의드립니다!

**Comment by bgpark-ft** [comment]
> 넵 맞습니다.

혹시 아래 이미지와 같이 공통스크립트 + 회원가입 이벤트 함께 기재하면 될지 문의드립니다. 

추가로 현재 공통스크립트 없이 이벤트 스크립트만 설치하여 정상적으로 데이터 수집중인 타 이벤트 스크립트(잠재고객, 서비스 신청)에 대해서도 동일하게 공통스크립트 함께 기재하여야 할지 문의드립니다.
![당근문의5](https://github.com/user-attachments/assets/a35051e5-3238-451a-8dff-ff50540cbe65)

**Comment by extJo** [comment]
네 맞습니다. 캡쳐주신 화면처럼 다른 이벤트에도 동일하게 적용해주시면 될거같습니다.
추후에 개선해서 타 매체 스크립트와 비슷하게 설치 가능하도록 개선하겠습니다
