### ISSUE TITLE
[QUESTION] 대시보드 내, 전환데이터가 잡히지 않습니다. 

### ISSUE THREAD

**Issue by yeongheon-son** [daangn/karrot-conversion-tracker-tool-support#102]
**Describe the question**
A clear and concise description

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

대시보드에서 전환 데이터가 잡히지 않아 관련하여 문의드립니다.

퍼블로그 모바일웹 스크립트 설치 완료하여

구매 데이터 수집되는 부분까지 '전환 추적 관리' 탭에서 확인한 바 있습니다.

실제로 셋팅한 url로 접속하여 구매 테스트시 > 하기와 같이 구매 이벤트 로그 수집 되는 부분도 확인하였습니다.
그럼에도 매체 대시보드 상에서 구매수, 구매 금액 끌어오지 못하고 있어 어떤 이슈 때문일지 함께 체크해주시면 하고 도움 요청드립니다.
스크립트 정상 설치 여부 확인할 수 있을지 문의드립니다
![image (1)](https://github.com/user-attachments/assets/bdd2547d-bd2e-4626-aeb6-0932c9a0776c)
![image](https://github.com/user-attachments/assets/44d8f87c-19d0-4982-997a-e9df97a4ef7c)
광고 계정 id는 2917222 입니다

**Comment by extJo** [comment]
> 구매 데이터 수집되는 부분까지 '전환 추적 관리' 탭에서 확인한 바 있습니다.ㅍ

전환추적관리에서 수집되는 이벤트는, 설치하신 웹사이트의 모든 이벤트에 대해서 관리되는 부분입니다.
캠페인 대시보드상에서 잡히는 전환 성과와 다릅니다

**Comment by yeongheon-son** [comment]
스크립트 설치되는 정상적으로 되어있으나, 
해당 전환추적관리의 구매 등의 수치는 대시보드상에서는 확인이 어렵다는 의미이실까요?
대시보드상에는 어떤 성과가 나타나고, 
말씀주신 전환추적관리에서의 수집 이벤트와 대시보드상에 나타나는 것이 어떻게 다른것인지 
조금더 상세한 설명 가능하실까요?

**Comment by extJo** [comment]
전환추적관리 대시보드
> 설치하신 웹사이트에 방문하는 모든 유저의 행동에 대한 이벤트를 수집한 대시보드

광고 대시보드상의 전환
> 설치하신 웹사이트에 방문하는 유저 중 광고주가 집행하고 있는 당근 광고를 통해서 방문한 유저의 행동에 대한 이벤트를 수집 및 가공하여 보여 줌

혹시 더 추가적으로 설명이 필요할까요?
