### ISSUE TITLE
[QUESTION] 대시보드 전환 체크 관련 문의의 건

### ISSUE THREAD

**Issue by progress-LeeHeeWon** [daangn/karrot-conversion-tracker-tool-support#103]
**Describe the question**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

![이미지_1](https://github.com/user-attachments/assets/90dcb6d5-1726-47c6-b622-5128376323f3)
![이미지_2](https://github.com/user-attachments/assets/eeca7fb2-99ea-49f3-bd3e-17c4ee709747)

전환 추적관리에서는 구매가 확인이되나,
대시보드상에서는 해당 구매가 연결되지않아 관련문의를 드렸었고 

전환 추적관리에서는 모든전환 (당근 광고 포함한 모든 광고) 이어서 전환 확인이되고,
대시보드 상에서는 당근 광고의 전환으로 인식되는 광고만 표기되어 대시보드 상에서는 전환 수치가 확인이 안된다고 답변을 받았었는데요.

당근 광고 URL을 통해 직접 구매를 통해 대시 보드 상에서 전환이 체크 되는지 확인하였는데도,
대시보드 상에서 전환이 발생되지 않아 문의드립니다.

**Comment by extJo** [comment]
> 당근 광고 URL을 통해 직접 구매를 통해 대시 보드 상에서 전환이 체크 되는지 확인하였는데도,
대시보드 상에서 전환이 발생되지 않아 문의드립니다.

이부분에 대해서 자세히 설명 가능할까요?

**Comment by progress-LeeHeeWon** [comment]
실제로 노출 되는 광고를 직접 클릭하여 구매하여, 구매 전환 체크를 하였습니다.
하지만 대시보드 상에서는 저희가 테스트로 구매한 전환이 최소 1개는 표기되었어야하나
해당 부분이 체크되지 않아 대시보드상에서 이슈가 있을것으로 예상되어 문의드리게 되었습니다.

**Comment by extJo** [comment]
설치한 웹사이트를 확인해보았는데요, 픽셀 ID를 두개로 운영하시면 전환 추적이 어려울 수 있습니다. 
퍼블로그 MOweb, 퍼블로그 PC를 통합해서 관리하시길 바랍니다

<img width="324" alt="image" src="https://github.com/user-attachments/assets/5b9f4603-3be9-4d2e-931f-c778e179c830">

**Comment by progress-LeeHeeWon** [comment]
현재 확인 주신 상황에서는 대시보드상에서 표기되지 않는것이,
두개의 픽셀 ID를 사용함에 따라 전환 추적이 안되는것으로 예측하는것이 맞으실까요?

PC / MO 각 개별로 사용함에 따라 전환 추적이 0이 될 수 있는것일지 문의드립니다.

**Comment by progress-LeeHeeWon** [comment]
![image](https://github.com/user-attachments/assets/283387c4-5fbe-447f-9f13-38d84099338c)

![image](https://github.com/user-attachments/assets/97a143ff-f00e-4c28-9a36-c7afcd21abb9)


캠페인 단에서는 전환 추적 코드를 1개 선택하여 진행하고 있는데, 
 둘중 1개만 진행하고 나머지는 삭제를 하여야할까요?

**Comment by extJo** [comment]
> 현재 확인 주신 상황에서는 대시보드상에서 표기되지 않는것이,
두개의 픽셀 ID를 사용함에 따라 전환 추적이 안되는것으로 예측하는것이 맞으실까요?
PC / MO 각 개별로 사용함에 따라 전환 추적이 0이 될 수 있는것일지 문의드립니다.

웹사이트 상에서 전환추적코드가 서로 다른 픽셀이 2개가 심겨져있는걸로 확인됩니다.
픽셀이 중복되어 설치되면 오동작할 수 있습니다. 따라서 둘중 하나는 삭제하시고 합쳐서 운영하시면 됩니다.
캠페인 연동또한 합쳐서 운영할 전환추적코드를 연동하시면됩니다.
