### ISSUE TITLE
[QUESTION] 광고 이벤트 스크립트 오류의 건

### ISSUE THREAD

**Issue by Eunseo-Jung** [daangn/karrot-conversion-tracker-tool-support#104]
안녕하세요, 당근 광고 이벤트 스크립트 건으로 문의드립니다.
업체명은 '야나두'이며, 연동시키고자 하는 이벤트는 '구매'와 '잠재고객 수집'입니다.

'잠재고객 수집'은 이전에 이미 GTM을 통해 연동했던 바 있고
이번에는 직접 코드로 '구매' 이벤트 스크립트를 삽입하였는데,
그 이후로 잘 작동하던 '잠재고객 수집' 데이터까지 수집되지 않고 있습니다.
그래서 '구매' 이벤트 스크립트는 현재 삭제하여 원상복구해둔 상태입니다.
(즉, 현재는 공통 스크립트와 '잠재고객 수집' 이벤트 스크립트만 추가된 상태) 

![image](https://github.com/user-attachments/assets/c56fdb1b-9b0f-4017-a87a-8092672bf662)

공통 스크립트는 정상 설치되어 있는 것 같고, 이벤트 전환 스크립트의 점검을 요청드립니다.
필요한 자료가 있다면 말씀 부탁드립니다. 감사합니다.

**Comment by extJo** [comment]
GTM 설정 첨부 부탁드립니다

**Comment by Eunseo-Jung** [comment]
태그 유형은 '맞춤 HTML'이고, '상담신청 완료'의 이벤트 트리거가 발생하면 실행되는 조건입니다.
아래 이미지와 같은 스크립트로 추가해두었습니다.

![image](https://github.com/user-attachments/assets/098fe379-1b56-4659-b32c-53508b5c04c4)

**Comment by extJo** [comment]
GTM 설정 맞는걸까요?
이와는 별개로 GTM으로 설정하는경우 예시로 상담신청 완료를 설치한다고 했을 때 공통스크립트와 함께 들어갈 수 있도록 설정해야합니다.
[이전의 유사 질문 참고부탁드립니다](https://github.com/daangn/karrot-conversion-tracker-tool-support/issues/101)

**Comment by Eunseo-Jung** [comment]
> GTM �설정 맞는걸까요? 이와는 별개로 GTM으로 설정하는경우 예시로 상담신청 완료를 설치한다고 했을 때 공통스크립트와 함께 들어갈 수 있도록 설정해야합니다. [이전의 유사 질문 참고부탁드립니다](https://github.com/daangn/karrot-conversion-tracker-tool-support/issues/101)

네, GTM 설정값 일부를 캡쳐해서 보내드린 것이었습니다.
전달주신 유사 질문 케이스 덕분에 우선 GTM에 공통 스크립트 추가하여 게재했습니다 :) 감사합니다.

추가로 혹시 정상 수집되는지 체크하기 위해서는 광고를 통해 실제 전환이 발생할 때까지 기다리는 방법밖에 없을까요?
'구매' 이벤트의 경우 금방 발생하지 않기 때문에 직접 테스트해보고자 합니다.

**Comment by extJo** [comment]
전환추적코드 대시보드상에서 구매가 잡힌다면, 캠페인에 전환추적코드만 연동하시면 광고기여 전환 이벤트인경우에는 광고관리 대시보드상에서 확인 하실 수 있습니다.
