### ISSUE TITLE
[QUESTION] 티젠 당근 계정 구매전환 트래킹 이슈_계정 검토 문의

### ISSUE THREAD

**Issue by WB-leeheeseon** [daangn/karrot-conversion-tracker-tool-support#105]
**Describe the question**
A clear and concise description
- 티젠 당근계정 구매완료 페이지 내, 구매 이벤트 스크립트 설치가 정상적으로 되지 않은 것으로 파악됩니다. 
   > 크로스 체크 요청 드리며,
   > 해결 방안 안내 부탁드립니다. 

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS Sonoma 14.5
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22]  125.0.6422.142(공식 빌드) (arm64)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Galaxy Note20 5G
 - OS: [e.g. iOS8.1] IOS13

**Additional context**

* 특히 네이버페이 결제 시 트래킹 이슈 확인 됨
   > 구매전환 트래킹 테스트 소재  (랜딩 URL: https://teazenmall.com/surl/P/1293)
   
<img width="482" alt="스크린샷 2024-07-25 오후 7 03 09" src="https://github.com/user-attachments/assets/532f545a-56f8-4c6e-b62e-fa5293ca1185">

   > 위 랜딩, 페이지 뷰 이벤트 스크립트 확인 되었으나, 구매완료 페이지 내(네이버페이) 구매 이벤트 스크립트 확인 불가.
   
<img width="1185" alt="스크린샷 2024-07-25 오후 7 01 45" src="https://github.com/user-attachments/assets/dd191ffc-d355-4abf-8211-90fb67af342c">
<img width="1184" alt="스크린샷 2024-07-25 오후 6 59 35" src="https://github.com/user-attachments/assets/3b4638ad-1610-44e9-9c8e-39e368da7b05">

* 위 테스트 결과 페이지 뷰는 정상적으로 데이터 수집 되는 점 확인하였으나, 구매 이벤트 데이터 미수집 된 점 확인하였습니다.

**Comment by 0jinn** [comment]
안녕하세요, 보여주신 구매 완료 페이지는 네이버페이에서 결제 완료 된 상황으로 보이고, 해당 페이지는 네이버 외에는 컨트롤 할 수 없는 영역으로 생각됩니다. 

구매 완료 후에 쇼핑몰로 돌아가는 부분이 있다면 해당 부분에서 [이 안내](https://bizschool.daangn.com/87729a84-5029-4a17-9531-d0f299e5f1f0)에 있는 구매 전환 부분 스크립트를 적용시켜 주셔야 할 것 같습니다. 
<img width="1030" alt="image" src="https://github.com/user-attachments/assets/dc40e723-140d-4672-bf23-beac9fcedc38">

혹은 쇼핑몰로 돌아가는 부분이 없다면 호스팅사에서 결제 연동되는 api등을 받아 처리 하셔야 할 것 같습니다.

**Comment by extJo** [comment]
혹시 cafe24와 같은 웹호스팅을 사용한 웹사이트일까요?

**Comment by WB-leeheeseon** [comment]
네,  cafe24 사용중입니다.

**Comment by extJo** [comment]
간편결제와 관련해서 이벤트 수집 스크립트 설치문의는 해당 호스팅사와 이야기해보셔야 할것같습니다!
저희가 모든 호스팅사에 대응 될 수 있도록 가이드 제공드리지 못하는 점 양해부탁드립니다~
