### ISSUE TITLE
[QUESTION] 전환 추적 관리  - 대시 보드 문의의 건

### ISSUE THREAD

**Issue by progress-LeeHeeWon** [daangn/karrot-conversion-tracker-tool-support#106]
전환 추적 관리에서는 구매가 표기가 되나, 
대시보드 상에서는 전환 확인이 되지않아 문의를 드렸었고,

스크립트 중복설치로 인한, 오류일 수 있다고 확인주셔서 광고주측에서 해당 스크립트는 삭제를 하였다고합니다.

![image](https://github.com/user-attachments/assets/8817553a-6375-4e71-8b73-0727df467dcf)

![image](https://github.com/user-attachments/assets/6686fd66-dbb8-4880-bffa-c427e35c2433)

전환 추적 관리 리스트에서도 삭제를 하여야하는걸까요?

관련 문의드립니다.

**Comment by extJo** [comment]
리스트에서는 따로 삭제하지 않으셔도 됩니다!

**Comment by progress-LeeHeeWon** [comment]
주말이후 지속적으로 광고 운영중이나, 해당 스크립트 이슈가 없는지 확인주실 수 잇을까요?
전환추적관리에서는 지속적으로 구매가 표기되나,
구매 등의 전환이 대시보드상에서 체크가 되지않아 문의드립니다

**Comment by 0jinn** [comment]
안녕하세요,
전환추적관리에서 구매가 표시된다는건 
<img width="768" alt="image" src="https://github.com/user-attachments/assets/c3b8eeee-3f81-40c4-a81d-619e992e96f3">
이 부분 말씀이실까요?

**Comment by progress-LeeHeeWon** [comment]
![image](https://github.com/user-attachments/assets/6015b71f-9313-40ba-be59-db724436c428)

전환 추적관리로 들어가면, 데이터 수집 모수 부분에서 노란색 표기한 것 처럼 모수가 표기되어서 문의드린것입니다

**Comment by extJo** [comment]
관리 도구에서 잡히는 이벤트는 픽셀을 설치하신 사이트의 모든 유저에 대한 이벤트를 보실 수 있고, 광고 관리 대시보드상에서는 광고 기여를 통한 이벤트만 보실 수 있습니다

**Comment by extJo** [comment]
추가문의사항 없으실까요?

**Comment by progress-LeeHeeWon** [comment]
네 확인주셔서 감사합니다. 추가 문의사항 없습니다.
