### ISSUE TITLE
[QUESTION] GTM으로 2개 광고 계정 전환스크립트 설치 문의건

### ISSUE THREAD

**Issue by jin5051** [daangn/karrot-conversion-tracker-tool-support#107]
두개의 당근 마켓 광고 계정의 전환 추적을 한 개의 GTM 컨테이너로 구현하려고 합니다. (랜딩페이지가 동일하기 때문)

각각의 계정의 공통 스크립트를 GTM 맞춤 HTML 태그로 등록하였고, 당근 잠재고객 수집, 상세페이지 조회 등 맞춤이벤트 태그를 생성하여 배포 하였는데, 한개의 당근 마켓 계정에서만 맞춤 이벤트가 수집됩니다.

![image](https://github.com/user-attachments/assets/feceee7d-2d34-44bc-88f8-01e06f3daeaa)
![image](https://github.com/user-attachments/assets/a5d0f72b-33fb-4853-8bb1-5e3785788e8a)
![image](https://github.com/user-attachments/assets/e9921836-0a2f-40f0-9e9b-d69f5c22fcbf)

한개의 GTM 컨테이너에서 2개의 공통스크립트 삽입 & 맞춤이벤트 태그 삽입

![image](https://github.com/user-attachments/assets/53bf5037-41d1-418a-8670-930a06502e76)

하지만 한개의 계정에서는 맞춤이벤트 로그가 수집이되는데 나머지 한개의 광고 계정에서는 방문 로그만 수집됩니다.

![image](https://github.com/user-attachments/assets/161d9d09-eba3-4a41-a89d-c6134195f307)

이상해서 맞춤이벤트 로그가 잘 수집되고 있는 광고계정의 공통스크립트를 삭제해봤더니 그때 나머지 계정에서도 잠깐 맞춤이벤트
로그가 잘 수집되었었는데 다시 재배포하니깐 또 수집이 안되더라고요.ㅠㅠ   

어케 해결할 수 있는지 문의드립니다.

**Comment by extJo** [comment]
안녕하세요. 지금 당근 픽셀의 경우 다른 전환 코드를 기준으로 중복설치하는것을 권장하지 않습니다.
현재는 중복으로 설치하는경우 이벤트를 정확하게 수집할 수는 없습니다~!
