### ISSUE TITLE
[QUESTION] 당근비즈니스 연동 서비스신청 수집 오류

### ISSUE THREAD

**Issue by bumsang1214** [daangn/karrot-conversion-tracker-tool-support#108]
카페24 호스팅을 통하여 웹 구축 후 당근비즈니스 광고를 진행중입니다.
전환추적관리의 서비스신청 전환을 구축하여 원할히 진행이 되어 수집모수 903명을 모았습니다.
그런데 24.07.19 기준으로 전환집계가 되지 않습니다.
자체 웹 내부에서 DB를 확인해보았을떄는 문의는 꾸준하게 들어오고있습니다.
온라인광고를 당근비즈니스로만 진행하기에 해당 DB문의는 당근비즈니스 문의입니다.
잘 잡히던 서비스신청 전환집계가 24.07.19 이후로 집계가 되지않는 사유와 해결방안 문의드립니다. 
사이트 URL : https://coway9402.mycafe24.com/

![image](https://github.com/user-attachments/assets/de91e513-2afd-421b-b303-54d8b318395e)
전환추적 관리 서비스 신청_24.07.19까지 집계 이미지

![image](https://github.com/user-attachments/assets/0fff576e-b5e8-4120-bd92-e7011eb37c11)
서비스 신청 완료 페이지에 서비스신청 스크립트 삽입 확인 이미지

**Comment by bumsang1214** [comment]
> 카페24 호스팅을 통하여 웹 구축 후 당근비즈니스 광고를 진행중입니다. 전환추적관리의 서비스신청 전환을 구축하여 원할히 진행이 되어 수집모수 903명을 모았습니다. 그런데 24.07.19 기준으로 전환집계가 되지 않습니다. 자체 웹 내부에서 DB를 확인해보았을떄는 문의는 꾸준하게 들어오고있습니다. 온라인광고를 당근비즈니스로만 진행하기에 해당 DB문의는 당근비즈니스 문의입니다. 잘 잡히던 서비스신청 전환집계가 24.07.19 이후로 집계가 되지않는 사유와 해결방안 문의드립니다.
> 
> ![image](https://private-user-images.githubusercontent.com/177917919/356505632-de91e513-2afd-421b-b303-54d8b318395e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxODkyMzgsIm5iZiI6MTcyMzE4ODkzOCwicGF0aCI6Ii8xNzc5MTc5MTkvMzU2NTA1NjMyLWRlOTFlNTEzLTJhZmQtNDIxYi1iMzAzLTU0ZDhiMzE4Mzk1ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQwNzM1MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNGE2MjNhZGIxMzQ4ZmYyNGQ5ZTY1NmZlMjQ4YTljZWIyNWU1NjZjNGZhZGZlMTNmMzVhZDUzODJhYmNkMzYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.B5vudjZlt0DBVsiL3smMnoyB4mzV_-cC78casFtJtms) 전환추적 관리 서비스 신청_24.07.19까지 집계 이미지
> 
> ![image](https://private-user-images.githubusercontent.com/177917919/356506259-0fff576e-b5e8-4120-bd92-e7011eb37c11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxODkyMzgsIm5iZiI6MTcyMzE4ODkzOCwicGF0aCI6Ii8xNzc5MTc5MTkvMzU2NTA2MjU5LTBmZmY1NzZlLWI1ZTgtNDEyMC1iZDkyLWU3MDExZWIzN2MxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQwNzM1MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MjJmYzg2Njg5MjkxZTdlYzc3ZDhiNjlhOTg2ZDUzNzQ1MzljYjA4YzE0NzlmODJhNDkyOTljNzU3YjlhMzdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.T-as2YCTHcpx6JWrCidEiEQbfi8hctdwJnvYu2xVSh4) 서비스 신청 완료 페이지에 서비스신청 스크립트 삽입 확인 이미지

**Comment by extJo** [comment]
안녕하세요. 문제가 된 기간동안 당근에서 관련된 배포나 문제가될 만한 부분은 확인하지 못했습니다.
- 해당 코드가 이전부터 설치되어있었는지
- 카페 24 설정을 수정하셔서 수집되지않는건지
- 카페 24쪽 배포로 인한 영향이 아닌지
등등 확인해보셔야할거같습니다.

**Comment by extJo** [comment]
@bumsang1214 추가 질문 있으실까요?
