### ISSUE TITLE
[QUESTION] 아임웹 이용자도 구매전환 추적이 가능한가요?

### ISSUE THREAD

**Issue by pjjoo** [daangn/karrot-conversion-tracker-tool-support#11]
**Describe the question**
A clear and concise description

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

개발관련 전문 지식이 없어 전달이 명확하지 않을 수 있습니다.
양해 부탁드립니다.  
구매전환을 추적하고 싶은데 제가 사용하는 아임웹에서는 서비스 내 데이터값을 알 수 없어서요..
아임웹 이용자도 구매전환을 할 수 있는지 궁금합니다. 

https://developers.imweb.me/cs/get
혹, 아임웹의 api 데이터값으로 시도해도 가능할까요?

만약 불가능 하다면 해당 광고로 구매전환의 유/무만이라도 파악할 수 있을까요?

**Comment by Gummybearr** [comment]
안녕하세요 :) 
imweb을 사용하지는 않기에 정확하지는 않을 수 있으나 [코드위젯](https://imweb.me/faq?mode=view&category=29&category2=38&idx=329) 페이지를 이용하여 구매 완료후 스크립트를 작동시키는 것으로 구매전환을 추적할 수 있을 것으로 보입니다. 

imweb 사이트 내부에서의 이용방식이나 동작방식은 imweb에 문의하시면 더 좋은 답변을 받으실 수 있을 것으로 보입니다.

감사합니다.

**Comment by Gummybearr** [comment]
2주간 별도의 답변이 있지는 않아서 닫을게요 문제가 있다면 다시 열어주세요
