### ISSUE TITLE
[QUESTION] 당근 전환추적 코드 관련 질문

### ISSUE THREAD

**Issue by ps010** [daangn/karrot-conversion-tracker-tool-support#111]
워드프레스 사이트로 전환추적 코드를 심어서 당근을 진행했는데 초반에 전환추적이 되다가 이후 전환추적이 아예 안되고 있습니다. 왜 그런 건지 알고 싶습니다. 

공통스크립트는 모든 바디에, 이벤트 스크립트는 상담버튼 클릭시 스크립트가 실행되도록 설치되어있습니다.

**Comment by extJo** [comment]
광고주 ID 첨부 바랍니다

**Comment by ps010** [comment]
3110975 입니다.

**Comment by ps010** [comment]
사이트는 https://car-dream.co.kr/req_quote/   입니다.

**Comment by extJo** [comment]
스크립트는 정상적으로 설치된것으로 보이며, 정상적으로 이벤트가 수집 되는지에 대한 여부는 전환 추적 관리에서 확인하실 수 있습니다.
다만 광고를 통해서 서비스 신청과 같은 전환 추적 지표가 광고관리 대시보드에 나타나지 않는걸로 문의주신거같은데요, 이는 광고 기여를 통한 전환이 잘 일어나지 않아서 그렇습니다.
타겟 오디언스를 좁히거나 더 많은 오디언스에게 광고가 도달 할 수 있도록 광고 집행 금액을 늘리시길 바랍니다.

**Comment by ps010** [comment]
넵 확인 감사드립니다 !

**Comment by ps010** [comment]
혹시 test db 3건 직접 넣어주신 걸까요?

**Comment by extJo** [comment]
아니요. 테스트 한 적 없습니다!

**Comment by ps010** [comment]
넵 확인 감사드립니다.

**Comment by ps010** [comment]
안녕하세요 ! 추가문의 드립니다ㅜㅜ 광고를 안 돌릴 땐 db가 1개~2개, 광고를 돌릴 땐 8-10개 정도의 db가 들어오는데 어떤 소재에서 들어오는지, 몇개가 들어온 건지 당근 대시보드/ 소재>서비스신청수에서 확인이 안됩니다.. 혹시 이것 또한 위에서 말씀해주신 것과 같은 사유일까요?

**Comment by extJo** [comment]
그건 저희가 답변드릴 수 있는 부분이 아닌거같습니다
