### ISSUE TITLE
[QUESTION] 당근마켓 전환 추적 코드 미집계 오류

### ISSUE THREAD

**Issue by EDAEUN** [daangn/karrot-conversion-tracker-tool-support#113]
Describe the bug
안녕하세요, 윤선생 당근마켓 전환 추적 코드가 미집계되고 있는 오류 보고 드립니다.

* 계정명/ID: 윤선생(윤스닷컴)/2224224

현재 서비스신청(SubmitApplication) 전환 추적 코드가 5/31일을 마지막으로 데이터 수집이 끊긴것으로 보여
지난 5/17에 신청하기 CTA 버튼에 스크립트 삽입이 되었는데 미집계 사유 문의 드립니다.

신청 페이지: https://www.yoons.com/experience/consultationRequest
신청 버튼: 페이지 최하단의 [신청] (아래 이미지 참고)
의심되는 사유는 6월에 페이지 변경으로 인해 페이지 시안이 변경되었는데
해당 시점에 CTA 버튼에 삽입된 스크립트도 유실되었을수 있을듯 하여 자세한 확인 부탁 드립니다.
![image](https://github.com/user-attachments/assets/6aaaa547-da9b-4690-935b-7569a52ca9ca)

**Comment by EDAEUN** [comment]
@extJo 안녕하세요, 지난 5월에 관련 문의 답변 주셨는데 확인 부탁 드립니다.

**Comment by EDAEUN** [comment]
@extJo 안녕하세요, 지난 5월에 관련하여 문의드려 답변 받았었는데 재확인 부탁 드리빈다.

**Comment by extJo** [comment]
전환추적도구 관리에서 이벤트가 수집되지않으면 잘못설치하신걸로 보입니다.

**Comment by EDAEUN** [comment]
@extJo 네 그럼 해당 이슈에 대해서는 스크립트 설치 부분을 확인해보겠으며,

추가로 저희가 윤선생 계정의 경우 통합상담신청/무료체험신청/사업자신청 등의 여러가지 캠페인으로 광고 운영이 되고 있는데요, 주로 <신청> 위주의 전환이 발생하여, 현재 무료체험 캠페인의 이벤트 스크립트는 현재 [서비스 신청 이벤트 스크립트(SubmitApplication]로 사용 중입니다.

다만 현재 라이브 되고 있는 사업자모집 캠페인에도 전환 추적 코드를 삽입 하고자 하는데, 혹 해당 동일 이벤트 유형인 [서비스 신청 이벤트]로 라벨명(트래킹명) 수정하여 사용이 가능할까요? (ex. SumitApplication_02)

기타 구매 및 잠재고객 수집 이벤트 명으로는 적합하지 않을듯 하여 현 윤선생 계정 내 위와 같이 라벨명을 변경하여 트래킹이 가능할지 문의드리며, 빠른 회신 주시면 감사드리겠습니다.

**Comment by extJo** [comment]
이벤트 유형을 커스텀하는 기능은 아직 지원하지 않습니다.
다만 캠페인 별로 지표를 관리하기 위해서 변경을 원하시는걸로 보입니다.
캠페인 성과로 잡히게 된 전환 지표는 광고관리에서 확인 하실 수 있습니다.

**Comment by EDAEUN** [comment]
@extJo 캠페인 성과로 잡히게 된 전환 지표는 광고관리에서 확인 가능하다는 부분에대해 세부 설명 부탁 드립니다.
저희가 캠페인별 각기 다른 페이지를 사용중인데, 전환 추적 코드의 경우 전환이 발생되는 시점에 삽입이 필요하여 캠페인(페이지)별 한가지 사용이 필요할것으로 보여 캠페인별 성과를 잡기 위해 추적 이벤트 코드 삽입이 필요한 부분이라, 확인 부탁 드립니다.

* 무료체험 신청 페이지: https://www.yoons.com/experience/event/id/110
└ 최하단 [신청하기] 버튼에 서비스 신청 이벤트 코드 삽입
* 사업자모집 신청 페이지: https://www.yoons.com/business

**Comment by extJo** [comment]
페이지별로 서비스 신청 이벤트 스크립트(SubmitApplication) 를 설치하시면
광고관리 또는 보고서상에서 캠페인 별 소재 랜딩에 따라서 일어난 전환은 각각 표기되도록 확인할 수 있습니다.

**Comment by extJo** [comment]
예를들어서 
- A, B 페이지의 각 버튼에 서비스 신청 이벤트 코드 삽입
- a 캠페인의 모든 소재의 랜딩이 A 페이지
- b 캠페인의 모든 소재의 랜딩이 B 페이지
- 오디언스가 당근에서 a 캠페인을 보고 A 페이지에서 스크립트가 설치된 버튼을 동작
- a 캠페인의 광고 관리 또는 보고서에서 서비스 신청 집계 내역 확인 가능

**Comment by EDAEUN** [comment]
@extJo 네네, 1개의 이벤트 스크립트로 캠페인별 성과 분리 가능한점 확인 하였습니다. 답변 감사합니다.

**Comment by EDAEUN** [comment]
@extJo 안녕하세요, 무료체험 캠페인 페이지 내 버튼에 이벤트 코드가 반영이 되어있는점을 확인 하였는데,
작동 및 트래킹이 안되고 있는걸로 보여 반영된 코드 아래 공유 드리오니 검토 부탁 드리겠습니다.

<link rel="stylesheet" href="/image/common/css/event-240723.css">

 



<script src="https://karrot-pixel.business.daangn.com/0.1/karrot-pixel.umd.js"></script>

<script>

  window.karrotPixel.init('1697596674446800001');

  window.karrotPixel.track('ViewPage');

  //window.karrotPixel.track('SubmitApplication');

</script>

**Comment by extJo** [comment]
@EDAEUN 해당 코드가 동작하지 않는거라면, 코드에 문제가 있으므로 반영되도록 수정하시면 됩니다.

**Comment by EDAEUN** [comment]
@extJo 페이지 내 코드는 정상적으로 반영이 되어있는데 당근 전환추적 관리에서 데이터 수집이 안되고 있는걸로 보여, 매체사 이슈일지 확인 부탁 드리겠습니다.

**Comment by extJo** [comment]
이슈 없습니다. 그리고 주신 코드를 보면 SubmitApplication 과 관련된 코드는 주석처리 되어있어서 동작하지 않을것으로 보입니다

**Comment by EDAEUN** [comment]
@extJo 혹시 주석처리로 인해 동작 불가상태라는 내용에 대하여 상세 설명해주실수 있으실까요? 서비스신청 이벤트 스크립트는 window.karrotPixel.track('SubmitApplication')로 처리가 되어있어서 문의 드립니다.
(https://bizschool.daangn.com/0f1f3e3b-67b4-452f-938a-25b872e5be9f)

**Comment by extJo** [comment]
담당 개발자 분에게 말씀드리면 아실꺼같습니다

**Comment by EDAEUN** [comment]
@extJo 네 해당건은 내부적으로 확인 해보겠으며, 추가로 광고주 측에 심겨져있는 당근마켓 코드엔 0.1의 내용이 심겨져있는데, 당근 매체 측 연동 가이드에는 0.4 내용이 있어 해당건은 어떤 차이일지/맞춰야 할지 추가 문의 드립니다.

* 당근마켓 이벤트 스크립트(방문)
![image](https://github.com/user-attachments/assets/ddab63e3-2fe4-47d8-80a9-2a9489e42d04)


* 광고주 측 삽입된 이벤트 스크립트(서비스 신청)
![image](https://github.com/user-attachments/assets/715bc167-771e-49d5-942c-76ba636ef0b9)

**Comment by extJo** [comment]
그 부분은 더 높은 버전으로 맞추셔도 되고, 맞추지 않으셔도 됩니다~!

**Comment by EDAEUN** [comment]
@extJo 넵 하였으며, 아래 추가 문의드리고자 하는게 있어 확인 해주시면 감사드리겠습니다.

1) 현재 사업자모집 광고의 신청 버튼에도 "이벤트 신청(SubmitApplication)" 코드 삽입을 하고자 하는데 사업자모집의 신청페이지는 앞단 도메인이 달라 혹시 이벤트 코드 작동이 안될수도 있을지?
└ 당근 전환 추적코드 연동 웹사이트URL: https://www.yoons.com/
└ 사업자모집 광고 웹사이트URL: https://whattime.co.kr/yoons/join/confirm?time_zone=Asia%2FSeoul&times=2024-09-06T09%3A00%3A00%2B09%3A00&guest_uid=yoonsevent&back=1

2) 앞서 문의드렸던 무료체험/사업자모집 캠페인이 같은 이벤트 코드를 써도 "캠페인별 소재 랜딩에 따라서 일어난 전환은 각각 표시"된다고 말씀주셨는데 해당 내용 중 "캠페인"이 혹시 당근마켓에서 그룹 상위에 있는 캠페인을 별도로 생성해야하는 부분일지 아님 그룹 분리운영시에도 전환 각각 확인 될지? (계정코드가 같다는 기준하에)

**Comment by extJo** [comment]
1. 불가능합니다.
2. 소재만 분리되어있으면 괜찮습니다!
