### ISSUE TITLE
[QUESTION] 당근마켓 구매 금액 이벤트 스크립트 확인 요청

### ISSUE THREAD

**Issue by JMK-96** [daangn/karrot-conversion-tracker-tool-support#114]
**Describe the question**
A clear and concise description

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

![MicrosoftTeams-image (1)](https://github.com/user-attachments/assets/0390792a-125b-41f2-bae1-7a4a0f8c132a)

전주 말씀주신 당근마켓 스크립트 코드 설치 완료하였으며 확인 부탁드립니다!

**Comment by extJo** [comment]
각 상품의 id도 문자열로 들어갈 수 있도록 설정 부탁드립니다

**Comment by JMK-96** [comment]
> 각 상품의 id도 문자열로 들어갈 수 있도록 설정 부탁드립니다

상품ID는 어디서 확인 가능할까요?

**Comment by extJo** [comment]
이 부분입니다

<img width="800" alt="image" src="https://github.com/user-attachments/assets/564e9ee2-0c5d-464f-a245-f5c264dea434">

**Comment by JMK-96** [comment]
![MicrosoftTeams-image (2)](https://github.com/user-attachments/assets/5ea121b6-b265-4cb3-aa9c-20b37989a650)
말씀주신 ID 문자열로 변경 완료하여 스크립트 확인 부탁드립니다

**Comment by extJo** [comment]
네 해당 사항 반영해서 전환 추적 도구 대시보드상에서 구매이벤트가 잘 들어온다면 문제없이 설치된걸로 보면될거같습니다
