### ISSUE TITLE
[QUESTION] 당근마켓 스크립트 관련

### ISSUE THREAD

**Issue by JMK-96** [daangn/karrot-conversion-tracker-tool-support#116]
**Describe the question**
A clear and concise description

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
당근마켓 상품 ID 문자열로 설정 완료하여 스크립트 확인 부탁드립니다
![image](https://github.com/user-attachments/assets/602b711b-a8d3-432d-90a7-f76b24d99a2b)

**Comment by extJo** [comment]
이전 문의에 답변드렷습니다
