### ISSUE TITLE
[QUESTION]당근 전환추적 코드 관련 질문

### ISSUE THREAD

**Issue by ksmin3785** [daangn/karrot-conversion-tracker-tool-support#117]
비상교육 사이트로 전환추적 코드 삽입을 하였으나 연동이 되고 있지 않습니다.

공통스크립트는 모든 바디에, 이벤트 스크립트는 https://www.pionada.com/consult/exprn/funnel/F240900011 페이지에 서비스 신청 이벤트 스크립트 실행되도록 설치되어있습니다.
계정 ID: 3168130

**Comment by extJo** [comment]
해당 링크 확인해보니 사이트에서 사용하는 require.js로 인해 에러 발생중인데 그 문제로 보입니다.
아래 내용 참고하셔서 수정 바랍니다
https://gist.github.com/cuth/99902bbcc88485328916

**Comment by ksmin3785** [comment]
공통스크립트는 수정후 연동이 완료되었는데요! , 서비스 신청 이벤트 스크립트는 정상 작동되는지 확인 부탁드립니다.

**Comment by extJo** [comment]
네 방금 테스트했는데, 되는거같아보입니다~
다음부터는 직접 테스트해보시면 됩니다

**Comment by ksmin3785** [comment]
빠른 확인 감사합니다 :)
