### ISSUE TITLE
[QUESTION] 당근마켓 이벤트 코드 /전환추적 관련 문제

### ISSUE THREAD

**Issue by ps010** [daangn/karrot-conversion-tracker-tool-support#118]
당근마켓 아이디: 3087531

![전환추적1](https://github.com/user-attachments/assets/4a0278a4-1c2f-4283-9a9f-b26db0d6e32d)
![전환추적2](https://github.com/user-attachments/assets/1f473b2a-0d6c-4738-8cf0-5a6d1fcaf524)
![전환추적3](https://github.com/user-attachments/assets/748efa3b-ed00-4bee-8731-e1570508d116)

상황 : 전환추적 코드를 심을 사이트를 실수로 웹사이트 렌트앤카2에도 추가하고
렌트앤카_공통스크립트에도 추가했습니다.

웹사이트: https://rentncar.co.kr/

위 웹사이트에 공통 및 이벤트 스크립트를 심었는데
사이트를 전환추적 코드 둘 다 추가해서 그런지 렌트앤카_공통스크립트에는 이벤트 스크립트가 뜨고 
렌트앤카2에는 공통스크립트만 확인이 됩니다. 

렌트앤카 2에서 공통스크립트와 이벤트코드 둘 다 확인하고 싶은데 방법이 있을까요? 

공통 스크립트: 

<script src="https://karrot-pixel.business.daangn.com/0.4/karrot-pixel.umd.js"></script>
<script>
window.karrotPixel.init('1727680096236000001');
window.karrotPixel.track('ViewPage');
</script>
 

이벤트 스크립트:

<script>
window.karrotPixel.track('SubmitApplication');
</script>

**Comment by extJo** [comment]
지금 구조상 여러 픽셀 삽입 하는경우, 동작을 보장하지않습니다.
단일로 구성하거나, 실수하신 경우 삭제 후 재발급하시길 바랍니다

**Comment by ps010** [comment]
공통스크립트에서 https://rentncar.co.kr/ 링크만 삭제하는 방법은 없을까요?

**Comment by ps010** [comment]
실수로 공통스크립트에 https://rentncar.co.kr/ 사이트를 추가해서 생긴 문제라 해당 링크만 렌트앤카_공통스크립트에서 삭제하고 싶습니다.

**Comment by extJo** [comment]
불가능합니다. 전환추적코드를 삭제하고 다시 발급하시면 됩니다.
