### ISSUE TITLE
[QUESTION]SubmitApplication 이벤트 파라미터 추가 가능 여부

### ISSUE THREAD

**Issue by choi-yoonhyuk** [daangn/karrot-conversion-tracker-tool-support#119]
SubmitApplication 이벤트 사용시 커스텀 파라미터를 추가하고 싶은경우 어떻게 하는지 문의 드립니다.

예를 들어 신청서A, 신청서B를 구분하려고 합니다.

**Comment by extJo** [comment]
구분하려는 목적이 무엇인가요?

**Comment by extJo** [comment]
광고 집행시에 구분하고 싶으신건가요?

**Comment by choi-yoonhyuk** [comment]
> 광고 집행시에 구분하고 싶으신건가요?

네 맞습니다. 해당 스크립트를 사용하려고 하는데 해당 스크립트에 파라미터를 따로 추가할 수 있을까요?


<script>
window.karrotPixel.track('SubmitApplication');
</script>

**Comment by extJo** [comment]
스크립트 설치 후, 광고 집행시 캠페인에 전환추적코드만 연동하시면 어떤 광고를 통해서 발생한 이벤트인지 시스템 내에서 자동으로 분류해드리고 있습니다. 따라서 구분하실 필요는 없습니다.

**Comment by choi-yoonhyuk** [comment]
> 스크립트 설치 후, 광고 집행시 캠페인에 전환추적코드만 연동하시면 어떤 광고를 통해서 발생한 이벤트인지 시스템 내에서 자동으로 분류해드리고 있습니다. 따라서 구분하실 필요는 없습니다.

만약 광고 집행시가 아닌 경우 스크립트 코드상에서는 나눌 방법은 없나요?

**Comment by extJo** [comment]
구분 하도록 제공하고 있진 않고있으며, 구분 하더라도 플랫폼내에서 확인할 수 있는 기능이 존재하지 않습니다.
원하시는 기능은 분석 도구이므로 GA와 같은 툴을 사용하시길 바랍니다.

**Comment by choi-yoonhyuk** [comment]
> 구분 하도록 제공하고 있진 않고있으며, 구분 하더라도 플랫폼내에서 확인할 수 있는 기능이 존재하지 않습니다. 원하시는 기능은 분석 도구이므로 GA와 같은 툴을 사용하시길 바랍니다.

구글 태그 매니저를 사용하여 해당 스크립트를 페이지에 삽입하고 있습니다.
그렇다면 구분할수 있는 파라미터를 제공하지않는다는 말씀으로 이해하면 될까요?
