### ISSUE TITLE
[QUESTION] 고도몰 구매 추적 오류

### ISSUE THREAD

**Issue by ijungshop** [daangn/karrot-conversion-tracker-tool-support#12]
**Describe the question**
A clear and concise description

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

안녕하세요. 고도몰 이용 중인 업체입니다.

<script>
window.karrotPixel.track(
  'Purchase', 
  {
    'total_price': '{=.totalGoodsDcPrice}',
    'total_quantity': '{=.goodsCnt}',
    'products': [{
      'id': '{=.goodsNo}'
      'name': '{=.goodsNm}',
      'qunatity': '{=.goodsCnt}',
      'price': '{=.goodsPrice}'
    }]
  }
)
</script>

위 코드를 삽입했는데,
아래와 같은 오류가 뜹니다.

Template_ Compiler Warning #4: loop var .goodsNo in {=.goodsNo} is not in proper loop in 사이트명/order/order_end.html on line 487

어떤 문제일까요?
(현재 같은 위치에 삽입한 페이스북 광고 코드는 정상 수집되고 있습니다.)

**Comment by Gummybearr** [comment]
안녕하세요 :) 첨부해주신 스크립트에 콤마가 빠져있는 것으로 보입니다.

products': [{ 'id': '{=.goodsNo}', ...후략
콤마를 삽입 한 이후에도 문제가 발생할 경우 이 스레드를 통해 알려주세요.

감사합니다.

**Comment by Gummybearr** [comment]
2주간 별도의 답변이 있지는 않아서 닫을게요 문제가 있다면 다시 열어주세요
