### ISSUE TITLE
[QUESTION]고도몰 당근 전환추적

### ISSUE THREAD

**Issue by ps010** [daangn/karrot-conversion-tracker-tool-support#120]
안녕하세요 고도몰 사이트에 당근 전환추적 코드를 심고 싶은데 이전에 심었던 사례가 있는지, 심을 수 있는지 궁금합니다.

**Comment by extJo** [comment]
가능합니다. 당근 전환추적도구 가이드와 고도몰 문서 참고하셔서 설치하시면 됩니다

**Comment by ps010** [comment]
답변감사드립니다.
