### ISSUE TITLE
[BUG] 전환추적 서비스신청 코드 

### ISSUE THREAD

**Issue by ps010** [daangn/karrot-conversion-tracker-tool-support#121]
![당근마켓전환추적코드문제](https://github.com/user-attachments/assets/cae962cb-5147-4839-b8dc-001a523b5525)

이 사이트에 https://rentncar.co.kr/ 전환추적코드를 심었는데 서비스 신청이 렌트앤카 2에서 확인이 안되고
렌트앤카_공통스크립트에만 서비스 신청이 뜨고 있습니다. 
![화면 캡처 2024-10-15 140732](https://github.com/user-attachments/assets/9f40e4e9-ec21-4f9a-a5cf-1a974daf044c)
렌트앤카_공통스크립트를 삭제하면 렌트앤카2에서는 확인이 가능하게 되는 부분일까요? 
삭제없이 렌트앤카2에서도 서비스 신청을 확인할 수 있는 방법은 없는 걸까요? 

혹시 전환추적이 잘못 삽입된 건지 아니면 삭제를 해야하는 건지 알고 싶습니다.

**Comment by extJo** [comment]
전환 추적 코드를 두개 발급하셔서 두개를 모두 설치하신거같습니다.
하나의 픽셀만 동작할 수 있으니 둘중 하나는 삭제하시고 하나만 운영하시길 바랍니다

**Comment by ps010** [comment]
![image](https://github.com/user-attachments/assets/bb2b4bf3-0790-4070-bc03-846e0c752685)
하나 삭제했는데 서비스신청이 확인되지않습니다ㅜㅜ...

**Comment by extJo** [comment]
가이드에 따라서 설치되어있는지 확인하시길 바랍니다

**Comment by ps010** [comment]
전환추적  a( 현 삭제코드) 전환추적 b 진행시 전환추적 a에 사이트 1(잠재고객)만 운영하다가 웹사이트 연동추가를 통해 사이트2(서비스신청) 추가했었는데 중복값 체킹 될 수 있어서 전환추적코드추가를 통해 전환추적b생성 후 사이트2를 연동했었습니다. 그런데 전환추적a 를 삭제했는데 b에는 값이 안뜨는게 가이드에 따라 설치가 잘 되었는지 확인을 해봐야한다는 거죠? 제가 제대로 이해를 못한 것 같아 여쭤봅니다.

**Comment by extJo** [comment]
1. 전환추적코드를 삭제하시면 삭제한 전환추적코드와 관련된 스크립트를 먼저 삭제
2. 기존에 남아있는 전환추적코드가 정상적으로 설치되어있는지, 모든 웹페이지에 삽입 될 수 있도록 설정되어있는지 확인
3. 가이드에 따라서 서비스 신청 스크립트가 원하는 동작 또는 웹페이지 방문에 정상적으로 설치되어있는지 확인

위 단계 참고하시길 바랍니다

**Comment by ps010** [comment]
감사드립니다ㅠㅠ
