### ISSUE TITLE
[QUESTION] 고도몰 구글태그를 통한 전환추적코드 삽입 

### ISSUE THREAD

**Issue by ps010** [daangn/karrot-conversion-tracker-tool-support#122]
사이트:https://phytonutri.kr/
광고주 아이디: 3195286
삽입 이벤트코드: 
 
<script>
window.karrotPixel.track('Purchase');
</script>
 
당근 공통스크립트와 이벤트코드 모두 구글태그를 통해 삽입했는데 
공통스크립트만 뜨고 이벤트 코드는 아직 수집전 상태로 뜹니다. 
혹시 어떤 것 때문에 그런 건지, 코드가 잘못된 건지 궁금합니다.

**Comment by ps010** [comment]
삽입 전환추적 코드: 
 
<script>
window.karrotPixel.track('Purchase');
</script>

**Comment by ps010** [comment]
안녕하세요 확인해보았는데 태그는 설치되었으나 실행이 안되는 걸로 뜹니다ㅜㅜ 이런 경우엔 어떻게 해야하나요?

**Comment by ps010** [comment]
![image](https://github.com/user-attachments/assets/5bcb3ecd-64b8-49bc-b0a5-7fc244f85ec1)

**Comment by extJo** [comment]
실행하도록 만들어야 할거같습니다. 
그 부분은 제희가 도움드릴 수 있는 부분은 아닌거같습니다~!

**Comment by ps010** [comment]
앗 답변감사드립니다 ~!
