### ISSUE TITLE
[QUESTION] 전환추적 회원가입(CompleteRegistration) 이벤트 문의

### ISSUE THREAD

**Issue by OHEulGyun** [daangn/karrot-conversion-tracker-tool-support#123]
광고ID : 3031344

이슈 : 전환추적 이벤트 방문/회원가입/장바구니담기/구매 등 4가지 이벤트 GTM 태그 작업을 완료 하였는데,
         방문/장바구니담기/구매는 정상적으로 수집되고 있지만, 회원가입(CompleteRegistration) 이벤트 수집전으로
        활성화 되고 있지않아서 확인 부탁드립니다.

       가이드에 맞춰 스크립트 정상적으로 적용 하였지만, 아직까지 수집전으로 확인되고 있어서 체크 부탁 드립니다.

**Comment by extJo** [comment]
GTM을 어떻게 설치하셧는지 GTM 설정 첨부 부탁드립니다

**Comment by OHEulGyun** [comment]
![당근마켓 회원가입 GTM태그](https://github.com/user-attachments/assets/57cf080e-3a4d-4f54-8eec-4d994c834573)
캡쳐화면과 같이 회원가입 태그설정 하였습니다.

**Comment by extJo** [comment]
공통 스크립트 동작여부도 가이드따라서 설정하셨을까요?

**Comment by OHEulGyun** [comment]
공통스크립트 가이드에 맞춰서 설정하였고, 방문통스크립트 가이드에 맞춰서 설정하였고, 방문 ViewPage 는 정상적으로 수집중에 있습니다.
![당근마켓 공통스크립트 GTM태그](https://github.com/user-attachments/assets/19dc5c82-ff66-4d7b-857d-9bafcb55fcdb)

**Comment by extJo** [comment]
공통 스크립트 (방문)이 동작한다면, 다른 이벤트도 동작하지 않을 이유가 없습니다.
GTM 디버거를 이용해서 회원가입시에 GTM이 잘 동작하는 지 확인하시길 바랍니다

https://support.google.com/tagmanager/answer/6107056?hl=ko&sjid=18282533361312108901-AP

**Comment by OHEulGyun** [comment]
근데 GTM 태그가 정상적으로 적용 되었다면 수집전이 아니라 수집중으로 변경되어야 하는데
회원가입 이벤트만 수집전으로 확인되고 있습니다.
![당근마켓 전환추적](https://github.com/user-attachments/assets/b8c70a2f-6265-4c79-b603-74cab28a8ef7)

**Comment by extJo** [comment]
네 그러니 회원가입 GTM에 대해서 웹어플리케이션에서 잘 삽입했는지, 잘 동작하는지 태그매니저 디버거를 통해 다시한번 확인하시길 바랍니다.

**Comment by OHEulGyun** [comment]
디버거 통해서 확인했을때 잘 잡히고 있는데, 계정에서는 아직 수집전으로 수치가 안들어오고 있습니다.
![당근마켓 디버거](https://github.com/user-attachments/assets/07bee726-ed96-4083-867a-c73ad3fca04c)

**Comment by extJo** [comment]
CompleteRegistration 으로 작성한 코드에 공통 스크립트도 넣어서 ㅎ

**Comment by OHEulGyun** [comment]
아직 회원가입 이벤트가 수집되고 있지않아서 추가 문의 드립니다.

가이드 확인 중에 연동된 웹사이트를 http://*.kt.com 으로 설정하면 KT 내 모든 페이지가 연동 된다고 하는데
해당 부분을 수정하면 회원가입 이벤트가 수집될수있을지 문의드립니다.

**Comment by extJo** [comment]
새로운 문의 열어주시길 바랍니다
