### ISSUE TITLE
[QUESTION] 전환추적 스크립트 삽입 이후 오류 문제

### ISSUE THREAD

**Issue by DTRIBESA1** [daangn/karrot-conversion-tracker-tool-support#124]
**Describe the question**

- 문의 내용 : 전환 트래킹 태그 삽입 이후 홈페이지 오류
- 광고 계정 이름 : 한화생명
- 광고주 ID : 3124252
- 이메일 정보 : tmddnjs@dtribe.co.kr

안녕하세요,
저희가 어제 GTM을 통해 페이지 內 당근마켓 태그를 삽입해서 배포하였는데요.
광고주 측에서 홈페이지 오류가 확인되어서 긴급하게 스크립트를 해제했다고 합니다.
한화생명 개발자 측에서는 페이지의 스크립트와 충돌이 나는 케이스 같다라고 하는데,
이 부분 확인 한번 부탁드리겠습니다.

* 페이지 주소 :
PC -
https://www.hanwhalife.com/main/benefit/event/BS_EQEV000_P20000.do?tab=1&seq=438
MO -
https://m.hanwhalife.com/mobile/customerCenter/event/MBS_EQEV000_P20000.do?tab=1&seq=439&currentPage=1

**Comment by extJo** [comment]
정확하게 스크립트를 어떻게 설치하셧는지, 어떤환경으로 동작하는 웹어플리케이션인지 알아야 도움드릴 수 있을 것 같습니다

**Comment by DTRIBESA1** [comment]
구글 태그 매니저를 통해서 모든 페이지 작동 시 공통 스크립트 호출될 수 있도록 설정해두었으며, 전환 스크립트의 경우 [상세페이지 조회]는 해당 페이지뷰 작동 시 호출, [잠재고객 수집]은 페이지 內 팝업 진입하는 '상담신청' 버튼 클릭 시 호출, [서비스 신청]은 팝업에서 모든 프로세스(상담신청) 완료 시 호출되게 세팅해두었습니다.

추가로, 오류 화면 캡쳐해둔 이미지 업로드를 안해드렸던 것 같아 함께 첨부해드립니다.
![image (23)](https://github.com/user-attachments/assets/cbb507c4-1061-46e7-8fb4-1adeabf4ebba)

**Comment by extJo** [comment]
가이드 문서 참고하셔서 공통 스크립트를 정상적으로 연동하시길 바랍니다

**Comment by DTRIBESA1** [comment]
GTM으로 연결했을 뿐 가이드에 나와있는대로 진행했습니다. 어떤 부분이 잘못된 건지, 스크립트 상에 문제가 있는 것인지(앞서 말씀 드린대로, 한화생명 페이지랑 충돌이 있을 수 있는 가능성 등)를 확인하기 위해 문의한 부분이니 확인 부탁드립니다.

**Comment by extJo** [comment]
가이드와 다른형태로 설치가 되어있기때문에, 가이드 문서를 참고하셔서 정확하게 공통 스크립트를 연동하시면 됩니다

**Comment by extJo** [comment]
https://bizschool.daangn.com/11328c3a-9f8f-8004-b6ea-f952a9ea7faa#:~:text=%EB%82%B4%20%EC%82%BD%EC%9E%85%EC%9D%B4%20%ED%95%84%EC%9A%94%ED%95%B4%EC%9A%94.-,2.%20GTM%20%2D%20%EA%B3%B5%ED%86%B5%20%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8%20%EC%97%B0%EB%8F%99,-%EB%8B%B9%EA%B7%BC%20%EC%A0%84%ED%99%98%20%EC%B6%94%EC%A0%81

**Comment by DTRIBESA1** [comment]
어떤 부분이 가이드랑 다른 형태일까요? 제가 확인했을때에는 가이드와 동일하게 설치가 잘 되어있는 것 같습니다.
당근만 GTM을 사용하는게 아니고, META/카카오모먼트 등 다른 매체도 동일하게 설치하고 문제없이 사용 중인데, 당근에서만 이러한 스크립트 오류가 확인되어서 문의 드린 부분입니다. 단순히 가이드와 다른 형태로 설치하였기 때문의 문제는 아닌 것 같아 문의 드린 부분인데, 잘못된 부분이 있다면 어떤 부분의 문제인지 말씀 부탁드립니다.
![공통스크립트](https://github.com/user-attachments/assets/b9c7c7e4-c0f9-4aff-bb09-3749829bb69d)
![전환스크립트](https://github.com/user-attachments/assets/59a5c2e7-6930-471d-9c72-1d06ab89a151)

**Comment by extJo** [comment]
첨부 주신 내용으로는 이상이 없어야 정상입니다. 다만 적용된 태그를 통해서 새 버전을 게시 하였는지도 확인 부탁드립니다.
그 이후에 한화 웹어플리케이션 환경과 저희가 제공하는 스크립트와 문제가 없을 지 확인 가능할것으로 보입니다

**Comment by DTRIBESA1** [comment]
해당 부분이 최초 배포 시에 적용되어있던 내용이며, 현재는 위에 말씀드렸다시피 오류로 GTM 연결을 해제해놓은 상태입니다.
말씀주신 부분으로는 적용되어있는 상태여야 점검이 가능한 것 같은데 맞을까요? 우선 현재 광고주 내부적으로 이슈사항이라 태그를 서버에 재반영하는 것은 불가능할 것 같습니다..

**Comment by extJo** [comment]
그러면 저희도 더 도움 드릴 수 있는 방안은 없을 것 같스빈다
