### ISSUE TITLE
[QUESTION] 전환 스크립트 삽입 위치 관련 문의

### ISSUE THREAD

**Issue by MINYOUNGPARK2563** [daangn/karrot-conversion-tracker-tool-support#125]
ID: 2372831

공통스크립트는 정상적으로 삽입 가능하나 전환 스크립트 관련 문의 드립니다.

전환 스크립트를 두가지로 삽입 예정이며, 한 건은 [버튼]에 서[비스 신청 이벤트 스크립트]를 설치, 한 건은 전환 완료 시 뜨는 [팝업]에 [구매이벤트 스크립트] 설치 하고자 합니다.

![버튼영역(서비스신청 이벤트 스크립트)_1](https://github.com/user-attachments/assets/f79294da-ed93-499a-97a6-42e2da0ac5c6)
![완료팝업(구매 이벤트 스크립트)_2](https://github.com/user-attachments/assets/cc7e9d8a-84d7-4ace-8bd3-40e8c220acd5)

위 두영역에 스크립트 삽입 관련해서 단순히 body 안에만 되는 건인지, 아니면 버튼에 추가해야 하는 것일지 문의 드립니다.

(개발측에서 버튼에 추가시 ga 트래킹에 위배 된다고 전달 받았는데 버튼에 추가해야 한다면 그 외 방안은 없을지 확인 부탁드립니다.)

**Comment by extJo** [comment]
버튼 액션으로 하셔도 됩니다

**Comment by MINYOUNGPARK2563** [comment]
말씀드린것과 같이 버튼에는 삽입이 불가능하여 문의 드린 건입니다.
단순 바디에 삽입해도 되는지, 혹은 버튼 추가 외 방안은 없는지 확인 부탁드립니다.

**Comment by extJo** [comment]
저희가 가이드 드릴 수 있는 부분은 아닌것 같습니다.
내부적으로 논의하셔서 설치하시면 될거같습니다

**Comment by MINYOUNGPARK2563** [comment]
[서비스 신청 이벤트 스크립트]
[구매이벤트 스크립트]

위 전환 스크립트 모두 body 삽입 하더라도 정상 작동이 가능한지도 내부에서 논의해야 하는 부분일까요?
페이지 개발 측에서 문의 온 사항이나 확인 가능한 경로가 없어 재문의 드립니다.

**Comment by extJo** [comment]
설치는 어디에 하셔도 무방하며, 원하시는 부분에 설치하시면 될거같습니다.
설치후 동작 확인만 잘 하시면 될 것 같습니다.

다만 수집하고자 하는 이밴트의 동작을 단순히 바디에 하는 경우에 의도하신대로 수집이 안될 수 있으니 이는 내부적으로 논의하시고 설치하시면 될거같습니다
