### ISSUE TITLE
[QUESTION] 전환추적 회원가입(CompleteRegistration) 이벤트 문의

### ISSUE THREAD

**Issue by OHEulGyun** [daangn/karrot-conversion-tracker-tool-support#126]
광고ID : 3031344

이슈 : 전환추적 이벤트 방문/회원가입/장바구니담기/구매 등 4가지 이벤트 GTM 태그 작업을 완료 하였는데,
방문/장바구니담기/구매는 정상적으로 수집되고 있지만, 회원가입(CompleteRegistration) 이벤트 수집전으로
활성화 되고 있지않아서 확인 부탁드립니다.

전체적으로 점검하고 GTM 미리보기로 체크 하였을때 정상적으로 잡히는데, 당근마켓 계정내 전환추적에서는
회원가입 이벤트가 수집전으로 활성화 되지않고 있습니다.

하여, 가이드 확인 하였을때 해당 부분을 적용하면 정상적으로 수집이 가능할지 추가 문의 드립니다.

연동 웹사이트 URL을 여러개로 설정하였는데, 가이드 상 http://*.kt.com으로 설정하며 다른 페이지로 같이 연동된다고 하는데
해당부분을 적용하면 이벤트수집에 영향을 줄지 확인 부탁드립니다.

**Comment by extJo** [comment]
1. 회원가입 이벤트를 전송하는 시점의 도메인 확인이 필요 해 보입니다. 만약 해당시점의 도메인이 전환추적도구에 연동되어있지 않다면, 수집 전으로 나오는것이 맞습니다
2. URL을 여러개 등록하는 대신 와일드카드를 사용해서 모든 서브도메인을 허용 해 줄 수 있습니다. https://*.kt.com 로 등록하시면 됩니다.

**Comment by OHEulGyun** [comment]
회원가입이 적용 되는 도메인을 모두 전환추적도구에 연동을 하였는데도 수집이 안되는 상황입니다.
다만, 와일드카드를 사용하면 회원가입이 수집 될수있을지 문의드립니다.

**Comment by extJo** [comment]
회원가입 이벤트가 발송되는 시점에 속해있는 도메인 알려주시길 바랍니다

**Comment by extJo** [comment]
@OHEulGyun 추가적으로 문의 없으신가요?

**Comment by OHEulGyun** [comment]
회원가입 이벤트가 발송되는 시점에 속해있는 도메인 전달 드립니다.

회원가입완료 - PC : "Page URL = (tb.)[accounts.kt.com/wamui/MemIdSuccess.do](http://accounts.kt.com/wamui/MemIdSuccess.do)"

회원가입완료 - Mobile  :   Page URL = (tb.)[accounts.kt.com/wamui/MemIdSuccessMobile.do](http://accounts.kt.com/wamui/MemIdSuccessMobile.do)

**Comment by extJo** [comment]
- accounts.kt.com은 이미 연동된 도메인으로 확인이 됩니다. 따라서 와일드카드를 적용한다고해서 수집되지않던 이벤트가 수집되지는 않습니다.
- 디버깅시에도 동작한다면 새 버전으로 개시하셧는지 꼭 확인바랍니다. [관련 링크](https://stackoverflow.com/questions/28381394/gtm-fires-some-tags-in-debug-mode-only)
- 디버깅으로 발생한 이벤트는 수집된것으로 보입니다. 따라서 gtm 설정 문제인것으로 보입니다.
