### ISSUE TITLE
전환스크립트 설치 관련 문의드립니다. 

### ISSUE THREAD

**Issue by dongchul-0703** [daangn/karrot-conversion-tracker-tool-support#127]
광고주:현대캐피탈

전환스크립트 테스트 진행시 추가 문의드립니다.
해당광고주는 금융사로 테스트계정에 스크립트를 진행하고 테스트후 실제 운영계정 www.hyundaicapital.com 사이트에 
동일한 스크립트를 적용합니다.

네이버의 경우 전환스크립트 테스트후 ID값을 전달하여 설치여부를 확인하고 있는것 같습니다.
혹시 당근도 유저 ID 값으로 전환여부를 확인할수 있는 부분이 있지않을까 생각됩니다.
당근마켓 내부 스크립트 관련 부서가 따로 계시진 않은지 문의드립니다.

**Comment by ham-daangn** [comment]
질문 더 없으신 것 같아서 이슈 닫도록 하겠습니다!
