### ISSUE TITLE
[QUESTION] 스크립트 설치 관련 문의드립니다.

### ISSUE THREAD

**Issue by dongchul-0703** [daangn/karrot-conversion-tracker-tool-support#128]
**Describe the question**
A clear and concise description

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

광고주: 현대캐피탈

스크립트 설치간 광고주측 보안부서에서 몇가지 문의가 와서 전달드립니다.

1. 스크립트 설치는 당사 웹사이트 특정 이벤트에 설치하여 특정정보를 수집하는 것으로 보입니다.
당근 마켓 내부 DB에 저장하다는것은 어떻게 어떤데이터를 저장한다는 것 일까요?

2. 당근마켓 DB에 저장된 어떤정보를 이용해서 광고가 노출되는지 프로세스 설계도를 요청하였습니다.

참고 파일은 첨부하였으며 아무래도 당근마켓 개발부서쪽에서 의견을 전달주셔야 될것으로 생각되어 
바쁘시겠지만 내부 개발부서측에 도움을 요청드립니다.
 
![캡처_참고_1](https://github.com/user-attachments/assets/2d35f174-905c-4222-a130-a71da56c4927)
![캡처_참고_2](https://github.com/user-attachments/assets/704f4dee-6a31-4e25-885a-eb9796eb057e)

**Comment by extJo** [comment]
안녕하세요. 이전에 세일즈 통해서 문의주신부분들은 답변을 드렸는데, 추가적으로 더 질문주신걸로 보입니다.

> 스크립트 설치는 당사 웹사이트 특정 이벤트에 설치하여 특정정보를 수집하는 것으로 보입니다. 당근 마켓 내부 DB에 저장하다는것은 어떻게 어떤데이터를 저장한다는 것 일까요?

이용자의 웹사이트/앱 서비스 방문 이력, 탐색 이력, 서비스 신청 이력, 접속 유저 정보, 기기상태정보, 그 외 비식별 범위 내에서 수집이 가능한 정보를 수집하여 저장합니다. 자세한 저장방식은 대외비이므로 답변드릴 수 없습니다

> 당근마켓 DB에 저장된 어떤정보를 이용해서 광고가 노출되는지 프로세스 설계도를 요청하였습니다.

광고 노출 방식과 관련된 설계도 또한 대외비이므로 전달드릴 수 없습니다

감사합니다

**Comment by dongchul-0703** [comment]
당근마켓 예산 비중 강화를 위한 방안으로 스크립트 설치로 다양한 타겟팅을 진행하고자 하는 취지에서 요청드렸습니다.
타매체사들은 해당 부분에 대한 내용을 상세하게 공유주셨는데 러프하게라도 공유주시기 어려우실까요?
확인 부탁드립니다.

**Comment by extJo** [comment]
죄송하지만 세일즈를 통해서 다시 연락주실 수 있을까요? 감사합니다
