### ISSUE TITLE
[QUESTION] 카페24 구매전환이 캠페인에 적용 안되는 이유 확인 부탁드립니다.

### ISSUE THREAD

**Issue by KHoon88** [daangn/karrot-conversion-tracker-tool-support#129]
카페24에서 자사몰을 운영중입니다.
광고 랜딩을 자사몰로 해서 진행 중에 다른 이벤트는 GTM으로 적용하고
구매 전환만 세부 정보들 때문에 몰 결제 완료 페이지에 스크립트를 심어서
전환추적관리 메뉴에서는 구매가 제대로 들어오는 것을 확인했습니다.

그런데 캠페인 쪽에서는 다른 부분은 다 반영이 되는데 구매가 잡히지 않고 있는 상황입니다.

```
Items_dg.push({
   'name' : '{$product_name}'.replace(item_name_pattern,'').replace('</span>',''), //상품명
   'id' : '{$product_no}', //상품번호
   'price' : '{$product_price_front}'.replace(',','').replace('원',''), //판매가
   'quantity' : '{$product_quantity_text}' //수량
});
```

위와 같이 구매한 제품별 정보를 Items_dg 라는 array에 넣고

```
const totalQuantity = Items_dg.reduce((sum, item) => sum + item.quantity, 0);
if('{$order_id}'){
	if('{$order_id}' != '20111102-0000001') { //테스트 구매 제외
		window.karrotPixel.track(
				'Purchase', 
				{
			'total_price': '{$result_order_price_front}'.replace(',','').replace('원',''),
			'total_quantity': `'${totalQuantity}'`,
			'products': Items_dg
				}
		);
	}
}
```

위처럼 스크립트를 사용 중입니다.

어떤 문제로 구매가 잡히지 않는지 확인 부탁드립니다.

**Comment by extJo** [comment]
광고주 ID 전달 부탁드립니다

**Comment by KHoon88** [comment]
> 광고주 ID 전달 부탁드립니다
3297352
입니다.
이걸 전달드리면 되는것일까요?

**Comment by extJo** [comment]
product_quantity_text가 제대로 파싱되지않고 empty string으로 들어온 것 같습니다. 다시한번 로직 파악 부탁드립니다!

1. `const totalQuantity = Items_dg.reduce((sum, item) => sum + item.quantity, 0);` 로 작성하셨는데요, item의 quantity가 위에서 이미 string이므로 정상적으로 동작 할 수 없습니다.
2. ``` 'total_quantity': `'${totalQuantity}'` ``` 대신 ```'total_quantity': `${totalQuantity}` ```로 작성하셔야합니다

들어온 로그 전달드립니다

```
{"totalQuantity":"'0;","totalPrice":"23300","products":[{"id":"936","name":"아가드 하이체어 전용 교체용 시트 커버","quantity":"","price":"29000"}]}
```

**Comment by extJo** [comment]
로그 전달드립니다
```
{"totalQuantity":"1","totalPrice":"6500","products":[{"id":"948","name":"아가드 문 손잡이 안전잠금장치 문고리고정장치","quantity":"1","price":"4900"}]}
```
