### ISSUE TITLE
[QUESTION] 카페24 구매 전환 추적 불가 관련 질문

### ISSUE THREAD

**Issue by nolimmath0807** [daangn/karrot-conversion-tracker-tool-support#13]
<script>
window.karrotPixel.track(
  	'Purchase', 
  	{
    	'total_price': '{$total_product_price}',
    	'total_quantity': '{$product_quantity}',
    	'products': [{
      		'id': '{$order_id}',
      		'name': '{$product_name}',
      		'quantity': '{$product_quantity}',
      		'price': '{$product_price}',
  			 }]
 			}
	)
</script>

현재 주문완료 창 쪽에 해당 코드를 삽입했는데 추적이 안되네요.. 혹시 어떤부분의 문제일까요

**Comment by Gummybearr** [comment]
안녕하세요 :) 광고주 아이디를 알려주실 수 있나요?

**Comment by nolimmath0807** [comment]
네 광고계정 말씀하시는걸까요?  ID : 2420103 입니다.

**Comment by Gummybearr** [comment]
제가 시험삼아 구매를 한번 해보았는데 이벤트를 발송하지 않는 것으로 보입니다. 저희측 코드로부터 기인하지 않는 에러가 있는 것으로 보입니다.

```js
Uncaught TypeError: Cannot set properties of undefined (setting 'price90')
    at HTMLSpanElement.<anonymous> (<anonymous>:1:474)
    at Function.each (1693380264:699:35)
    at jQuery.fn.init.each (1693380264:519:27)
    at <anonymous>:1:33
    at gtm.js?id=GTM-5WWMHQMV:419:414
    at b (gtm.js?id=GTM-5WWMHQMV:420:337)
    at Df (gtm.js?id=GTM-5WWMHQMV:107:103)
    at e (gtm.js?id=GTM-5WWMHQMV:281:214)
    at gtm.js?id=GTM-5WWMHQMV:55:130
    at Array.<anonymous> (gtm.js?id=GTM-5WWMHQMV:282:401)
```

**Comment by Gummybearr** [comment]
구매완료 페이지에서 전송하고 있는 ViewPage 요청을 함께 첨부드립니다.

```
https://collect.kr.karrotmarket.com/p/c?id=1692255259299300001&uid=km%7Cracelturn.co.kr%7C1693460643736%7C8a66e156-7c26-42ff-a0c2-dfa2e79fa477&et=ViewPage&rl=https%3A%2F%2Fracelturn.co.kr%2Fapi%2Fshop%2Fpgsuccess%3Forder_id%3D20230831-0001474%26request_protocol%3Dhttps%3A&l=https%3A%2F%2Fracelturn.co.kr%2Forder%2Forder_result.html%3Forder_id%3D20230831-0001474&ts=1693461482209&pl=%7B%7D&md=%7B%22sw%22%3A3360%2C%22sh%22%3A1890%2C%22ec%22%3A0%2C%22it%22%3A1693461482208%2C%22v%22%3A%220.1.0%22%7D
```

**Comment by nolimmath0807** [comment]
위 페이지가 아무것도 안열리네요...!

**Comment by Gummybearr** [comment]
@nolimmath0807 어떤 페이지를 말씀하시는걸까요?

**Comment by nolimmath0807** [comment]
https://collect.kr.karrotmarket.com/p/c?id=1692255259299300001&uid=km%7Cracelturn.co.kr%7C1693460643736%7C8a66e156-7c26-42ff-a0c2-dfa2e79fa477&et=ViewPage&rl=https%3A%2F%2Fracelturn.co.kr%2Fapi%2Fshop%2Fpgsuccess%3Forder_id%3D20230831-0001474%26request_protocol%3Dhttps%3A&l=https%3A%2F%2Fracelturn.co.kr%2Forder%2Forder_result.html%3Forder_id%3D20230831-0001474&ts=1693461482209&pl=%7B%7D&md=%7B%22sw%22%3A3360%2C%22sh%22%3A1890%2C%22ec%22%3A0%2C%22it%22%3A1693461482208%2C%22v%22%3A%220.1.0%22%7D

**Comment by nolimmath0807** [comment]
저희쪽에서 아무것도 안열리는데, 혹시 주소로 저희가 어떤 데이터를 체크가 가능한건가요?

**Comment by Gummybearr** [comment]
해당 url은 데이터 수집을 위한 url로 status code 이외의 응답을 주고 있지는 않습니다. 
다만 아래 요청의 형식을 통해 필요한 상황에서 요청이 가고 있는지 확인은 가능한데요, 광고주께서 전환이벤트 수집 소스로 등록하신 url을 방문하셔서 필요한 시점에 위와 유사한 형식의 요청을 보내는지 확인부탁드립니다. 제가 직접 방문하여 구매해보았을때는 일부 파라미터를 세팅하는 로직에 오류가 있는 것으로 보였습니다.

**Comment by Gummybearr** [comment]
<img width="1582" alt="Screenshot 2023-09-01 at 2 12 01 PM" src="https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/41829700/0b648719-b8c0-45a4-b717-fb45fccf816b">

**Comment by Gummybearr** [comment]
<img width="1468" alt="Screenshot 2023-09-01 at 2 13 28 PM" src="https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/41829700/639857f1-654f-4a6d-aecf-035c2b9b865c">
