### ISSUE TITLE
[QUESTION] 전환 추적 코드 도메인 설정 관련

### ISSUE THREAD

**Issue by EDAEUN** [daangn/karrot-conversion-tracker-tool-support#130]
**Describe the question**

안녕하세요, 윤선생 신규 캠페인(레벨테스트) 전환추적 코드 생성 관련하여 문의 드립니다.

레벨테스트 캠페인이 12월부터 집행 예정으로, 소재의 랜딩 페이지와 실제 전환 추적할 페이지의 도메인이 다른 경우
공통(방문) 스크립트 및 이벤트(서비스 신청) 스크립트 둘다 개별로 심겨야 하는 부분일지, 그리고 가능한건지 문의 드립니다.

현재 "윤선생베이직" 전환 추적 코드처럼 새로 "윤선생레벨테스트" (도메인은 https://leveltest.yoons.com) 전환 추적 코드를 신규로 추가하여 작업 하고자 하는데 아래 내용 참고하시어 이점 이슈없을지 확인 부탁 드립니다.

1) 레벨테스트 광고 소재의 랜딩의 앞단 도메인은 기존 사용중인 윤스닷컴 (https://www.yoons.com)
2) 레벨테스트 광고 소재 클릭 후 전환 추적 코드가 심길 페이지의 앞단 도메인은 https://leveltest.yoons.com

**Comment by ham-daangn** [comment]
안녕하세요.
- 스크립트는 둘 다 심어주셔야 합니다.
- 여러개의 도메인을 연동하고 싶으시다면 전환 추적 코드 웹사이트 URL을 여러개로 설정하시거나, 서브도메인을 `*`로 설정하시면 될 것 같습니다.

다만, 하나의 페이지에 여러개의 전환 추적 코드를 삽입하면 정상적인 작동이 어려울 수 있으니 이점 참고하셔서 작업 진행해주시면 될 것 같습니다.

**Comment by EDAEUN** [comment]
네 담당자님, 전달주신 내용 확인하였으며 아래 추가 문의 드립니다.

1) 현재 사용중인 윤스닷컴(https://www.yoons.com/) 도메인과 새로 트래킹 필요한 레벨테스트 캠페인 광고 소재의 랜딩의 도메인이 일치하는데 레벨테스트 페이지에 공통(방문) 스크립트 중복 집계 등 이슈는 없을지?
└ 윤스닷컴) 무료체험 캠페인 랜딩: https://www.yoons.com/experience/event/id/110
└ 윤선생레벨테스트) 레벨테스트 캠페인 랜딩: https://www.yoons.com/experience/event/id/198

2) 레벨테스트 랜딩 페이지에서 전환 집계를 위해 테스트 신청하기 버튼 클릭시 외부 페이지(https://leveltest.yoons.com)로 이동 및 해당 페이지 내 버튼에 이벤트 스크립트 삽입 예정인데, 이경우 페이지 이탈 및 도메인이 다른데 유실 가능성은 없을지?
+ 데이터 구분할떄 전환 구분값이 대시보드에서 구별할수 있을지?

**Comment by ham-daangn** [comment]
질문에 대해 답변 드립니다.
1. 랜딩 페이지 별로 다른 전환 추적 코드를 삽입하셨다면 중복 집계가 일어나진 않을 것 같습니다.
2. 외부 페이지에도 랜딩 페이지와 동일한 전환 추적 코드를 삽입하신다면 괜찮을 것 같습니다.
3. 전환 구분값은 발화하시는 이벤트에 따라서 달라지며, 대시보드에서 확인할 수 있습니다.

감사합니다.

**Comment by EDAEUN** [comment]
말씀주신 1번 답변 관련하여, 같은 도메인 및 전환추적코드 사용중인데 중복 집계가 되지 않는게 맞을까요? (윤스닷컴의 한가지 전환추적코드 사용) 

만약 레벨테스트 캠페인의 전환추적 코드를 새로 생성하여 윤스닷컴과 동일한 도메인 사용 및 랜딩에 공통 및 이벤트 스크립트를 넣으면 해당 전환추적 코드에 방문 및 이벤트가 집계 될까요?

추가로, 현재 사용중인 윤스닷컴(전환 추적id: 1697596674446800001) 에 서브도메인으로 레벨테스트 캠페인을 등록하고, 성과 분리가 필요해 스크립트 내 이벤트명을 다른  이벤트 명으로 수정하는 방법도 가능한지 문의 드립니다.

**Comment by ham-daangn** [comment]
질문에 대해 답변 드립니다.
1. 같은 전환추적코드 사용중이라면 중복 집계가 될 것 같습니다.
2. 위에 말씀드렸듯이 동일한 도메인을 사용하더라도 랜딩 페이지 마다 전환 추적 코드가 다르게 심어져 있으면 별도로 이벤트를 집계합니다. 만약, 하나의 페이지에 여러 개의 전환 추적 코드를 삽입한다면 정확한 이벤트 집계가 어려울 수 있습니다.
3. 현재는 커스텀 이벤트 기능이 지원되지 않아, 이벤트 명을 수정하는 것은 불가능 할 것 같습니다.
감사합니다.

**Comment by EDAEUN** [comment]
안녕하세요, 혹시 그럼 https://www.yoons.com/experience/event/id/198 랜딩에 대해 전환 추적을 위해서는 새로운 해당 도메인으로 새로운 전환 추적 코드 생성 및 공통/이벤트 스크립트 추가하는 방법뿐일지 최종 문의 드립니다.

**Comment by ham-daangn** [comment]
넵! 그렇게 진행하시고 테스트 해보시면 될 것 같습니다.

**Comment by EDAEUN** [comment]
Dooray! 부재중 자동 응답










부재중 자동 응답






***@***.***) 

님은 현재 부재중입니다.


2024.11.29 ~ 2024.11.29


(이 메일은 부재중 
설정을
통해 자동으로 전송되는 메일입니다.)






[부재 기간 : 2024-11-29 00:00 ~ 2024-11-29 23:30 GMT +09:00]






이 메일은 발신전용으로 회신되지 않습니다.





© Dooray!
