### ISSUE TITLE
[QUESTION] 리드전환 추적설치 문의드립니다

### ISSUE THREAD

**Issue by machonam667** [daangn/karrot-conversion-tracker-tool-support#131]
페이지뷰는 정상적으로 수집되는데
리드양식이 수집되지 않습니다.
가이드영상이나 방법을 순서대로 알려주실수 있나요?
연동랜딩페이지는 아임웹입니다
작업랜딩페이지 - https://www.finalcoinbit.co.kr

![image](https://github.com/user-attachments/assets/36359e97-21c1-4483-aa4b-bb52e61ae801)

**Comment by ham-daangn** [comment]
안녕하세요. 
[전환 추적 코드 연동 가이드](https://bizschool.daangn.com/43922c93-2958-42c3-811f-3546d17e80e1)를 참고해서 진행해주시면 될 것 같습니다.
감사합니다.
