### ISSUE TITLE
[QUESTION]당근마켓 이벤트코드 추적이 안돼요

### ISSUE THREAD

**Issue by scbyeon** [daangn/karrot-conversion-tracker-tool-support#132]
**Describe the question**
당근마켓 기본 픽셀 및 이벤트 픽셀 설치했는데
방문 픽셀만 잡히고 이벤트 픽셀은 확인 안되고 있스빈다.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Window11
 - Browser [e.g. chrome, safari] chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ham-daangn** [comment]
안녕하세요.
[전환 추적 코드 연동 가이드](https://bizschool.daangn.com/43922c93-2958-42c3-811f-3546d17e80e1)를 참고해서 진행해주시면 될 것 같습니다.
감사합니다.

**Comment by scbyeon** [comment]
안녕하세요,

가이드 참고하여 두번이나 구글태그매니저로 전환 이벤트 코드 설치했는데
수집이 안되고 있어서 연락드렸습니다.
설치 후 GTM에서 디버깅으로 체크했을때는 분명 진행이 되었는데
당근비즈니스 전환추적 관리에서는 수집이 안되고 있어 문의드립니다.

감사합니다.




--- Original Message ---
From : ***@***.***>
To : ***@***.***>
Cc : ***@***.***>, ***@***.***>
Date : 2024/12/03 화요일 오후 5:44:18
Subject : Re: [daangn/karrot-conversion-tracker-tool-support] [QUESTION]당근마켓 이벤트코드 추적이 안돼요 (Issue #132)


안녕하세요.
전환 추적 코드 연동 가이드를 참고해서 진행해주시면 될 것 같습니다.
감사합니다.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>
[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/daangn/karrot-conversion-tracker-tool-support/issues/132#issuecomment-2513883233", "url": "https://github.com/daangn/karrot-conversion-tracker-tool-support/issues/132#issuecomment-2513883233", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]   Signature (주)크리앤비
선임 매니저 변 성철
www.crenbe.com

Email: ***@***.***
Mobile: 010-2908-7470
FAX: +82-2-6951-2621
Address: 서울시 마포구 서교동 358-121, 3층 크리앤비

**Comment by ham-daangn** [comment]
안녕하세요.
확인을 위해 GTM 설정 첨부 부탁드립니다.

**Comment by scbyeon** [comment]
안녕하세요,
아래와 같이 캡쳐 이미지 보여드리면 될까요?







추가로 필요한 사항 있으면 말씀해 주세요.
감사합니다.


--- Original Message ---
From : ***@***.***>
To : ***@***.***>
Cc : ***@***.***>, ***@***.***>
Date : 2024/12/04 수요일 오후 2:43:30
Subject : Re: [daangn/karrot-conversion-tracker-tool-support] [QUESTION]당근마켓 이벤트코드 추적이 안돼요 (Issue #132)


안녕하세요.
확인을 위해 GTM 설정 첨부 부탁드립니다.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>
[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/daangn/karrot-conversion-tracker-tool-support/issues/132#issuecomment-2516243368", "url": "https://github.com/daangn/karrot-conversion-tracker-tool-support/issues/132#issuecomment-2516243368", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]   Signature (주)크리앤비
선임 매니저 변 성철
www.crenbe.com

Email: ***@***.***
Mobile: 010-2908-7470
FAX: +82-2-6951-2621
Address: 서울시 마포구 서교동 358-121, 3층 크리앤비

**Comment by ham-daangn** [comment]
안녕하세요.
이미지가 보이지 않는데 혹시 다시 한번 확인 가능할까요?

**Comment by scbyeon** [comment]
안녕하세요

파일첨부파일로 전달드립니다.

감사합니다.
변성철 드림






--- Original Message ---
From : ***@***.***>
To : ***@***.***>
Cc : ***@***.***>, ***@***.***>
Date : 2024/12/04 수요일 오후 4:32:32
Subject : Re: [daangn/karrot-conversion-tracker-tool-support] [QUESTION]당근마켓 이벤트코드 추적이 안돼요 (Issue #132)


안녕하세요.
이미지가 보이지 않는데 혹시 다시 한번 확인 가능할까요?
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>
[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/daangn/karrot-conversion-tracker-tool-support/issues/132#issuecomment-2516409296", "url": "https://github.com/daangn/karrot-conversion-tracker-tool-support/issues/132#issuecomment-2516409296", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]   Signature (주)크리앤비
선임 매니저 변 성철
www.crenbe.com

Email: ***@***.***
Mobile: 010-2908-7470
FAX: +82-2-6951-2621
Address: 서울시 마포구 서교동 358-121, 3층 크리앤비

**Comment by ham-daangn** [comment]
안녕하세요.
깃헙에서는 첨부파일과 이미지가 보이지 않는데, 확인 부탁드립니다.

**Comment by scbyeon** [comment]
안녕하세요,

그럼 텍스트로 공유드리겟습니다.
우선 랜딩페이지는 https://dbcollect.co.kr/ttangttang 이고
방문 이벤트는 수집중이고, 전환이벤트가 수집 안되는 상태입니다.
전환이벤트 GTM 태그 설정은 아래와 같이 하였습니다.
<태그 구성>
유형 : 맞춤 HTML
HTML :

<script>
window.karrotPixel.track('Lead');
</script>



<트리거>
유형 : 페이지뷰
일부 페이지뷰
Page URL(포함) : /ttangttang/result

이렇게 구성하였습니다.

확인 부탁드립니다.
감사합니다.




--- Original Message ---
From : ***@***.***>
To : ***@***.***>
Cc : ***@***.***>, ***@***.***>
Date : 2024/12/04 수요일 오후 5:10:46
Subject : Re: [daangn/karrot-conversion-tracker-tool-support] [QUESTION]당근마켓 이벤트코드 추적이 안돼요 (Issue #132)


안녕하세요.
깃헙에서는 첨부파일과 이미지가 보이지 않는데, 확인 부탁드립니다.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>
[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/daangn/karrot-conversion-tracker-tool-support/issues/132#issuecomment-2516493592", "url": "https://github.com/daangn/karrot-conversion-tracker-tool-support/issues/132#issuecomment-2516493592", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]   Signature (주)크리앤비
선임 매니저 변 성철
www.crenbe.com

Email: ***@***.***
Mobile: 010-2908-7470
FAX: +82-2-6951-2621
Address: 서울시 마포구 서교동 358-121, 3층 크리앤비

**Comment by ham-daangn** [comment]
안녕하세요.
스크립립트를 확인해보니, 픽셀이 초기화 되기 전에 다른 스크립트가 실행되서 발생하는 문제인 것 같습니다.
이 부분에 대해서 수정을 해주시면 될 것 같습니다.
감사합니다.
<img width="787" alt="image" src="https://github.com/user-attachments/assets/b658b86d-9b58-4884-91c6-f187e84770b1">

**Comment by scbyeon** [comment]
안녕하세요,
말씀주신 다른 스크립트가 실행된다고 하신 부분은
어떤 부분을 수정하면 되는지 자세히 설명주실 수 있을까요?

감사합니다.
변성철 드림







--- Original Message ---
From : ***@***.***>
To : ***@***.***>
Cc : ***@***.***>, ***@***.***>
Date : 2024/12/04 수요일 오후 7:49:29
Subject : Re: [daangn/karrot-conversion-tracker-tool-support] [QUESTION]당근마켓 이벤트코드 추적이 안돼요 (Issue #132)


안녕하세요.
스크립립트를 확인해보니, 픽셀이 초기화 되기 전에 다른 스크립트가 실행되서 발생하는 문제인 것 같습니다.
이 부분에 대해서 수정을 해주시면 될 것 같습니다.
감사합니다.
image.png (view on web)
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>
[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/daangn/karrot-conversion-tracker-tool-support/issues/132#issuecomment-2516940756", "url": "https://github.com/daangn/karrot-conversion-tracker-tool-support/issues/132#issuecomment-2516940756", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]   Signature (주)크리앤비
선임 매니저 변 성철
www.crenbe.com

Email: ***@***.***
Mobile: 010-2908-7470
FAX: +82-2-6951-2621
Address: 서울시 마포구 서교동 358-121, 3층 크리앤비

**Comment by ham-daangn** [comment]
안녕하세요.
위의 코드에서 보시면 `window.karrotPixel.init()`이 호출되고, `window.karrotPixel.track("Lead")`가 호출되어야 하는데, `window.karrotPixel.track("Lead")`가 먼저 호출되서 발생하는 문제인 것 같습니다.
GTM에서 태그 시퀀싱 기능을 활용하여 `window.karrotPixel.init()`이 먼저 호출되도록 하면 될 것 같습니다. ([참고 링크](https://dachata.com/google-tag-manager-tips/post/how-to-install-kakao-pixel-with-gtm/))

**Comment by scbyeon** [comment]
안녕하세요
안내주신대로 설정하여 이제 전환 이벤트 수집이 됩니다.
정말 감사합니다.

따뜻한 연말 보내세요





--- Original Message ---
From : ***@***.***>
To : ***@***.***>
Cc : ***@***.***>, ***@***.***>
Date : 2024/12/05 목요일 오전 11:27:52
Subject : Re: [daangn/karrot-conversion-tracker-tool-support] [QUESTION]당근마켓 이벤트코드 추적이 안돼요 (Issue #132)


안녕하세요.
위의 코드에서 보시면 window.karrotPixel.init()이 호출되고, window.karrotPixel.track("Lead")가 호출되어야 하는데, window.karrotPixel.track("Lead")가 먼저 호출되서 발생하는 문제인 것 같습니다.
GTM에서 태그 시퀀싱 기능을 활용하여 window.karrotPixel.init()이 먼저 호출되도록 하면 될 것 같습니다. (참고 링크)
감사합니다.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>
[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/daangn/karrot-conversion-tracker-tool-support/issues/132#issuecomment-2518951128", "url": "https://github.com/daangn/karrot-conversion-tracker-tool-support/issues/132#issuecomment-2518951128", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]   Signature (주)크리앤비
선임 매니저 변 성철
www.crenbe.com

Email: ***@***.***
Mobile: 010-2908-7470
FAX: +82-2-6951-2621
Address: 서울시 마포구 서교동 358-121, 3층 크리앤비

**Comment by ham-daangn** [comment]
잘 해결되었다니 다행입니다.
즐거운 연말 보내세요!
