### ISSUE TITLE
전환연동 질문드립니다.

### ISSUE THREAD

**Issue by Seo-Hoyoung** [daangn/karrot-conversion-tracker-tool-support#133]
오늘 당근 전문가모드 광고 웨비나 시청 했는데 전문가모드 추적 연동 카페24 조만간 연동 될 예정이라고 보았는데

정확한 날짜를 알 수 있을까요? 정확하게가 안되면 대략적으로 몇월달에 진행될 예정인지 알고 싶습니다.

**Comment by seongjunhwang** [comment]
안녕하세요.

아직 정확한 연동 날짜가 나오지 않았지만 12월 중 카페24 연동이 완료될 계획으로 보고 있습니다.
