### ISSUE TITLE
[QUESTION] 당근마켓 lead 전환 추적이 되지 않고 있습니다.

### ISSUE THREAD

**Issue by yoroyoro999** [daangn/karrot-conversion-tracker-tool-support#134]
계정 이름 : 먼슬리키친
사업자 번호 : 235-87-01101

해당 계정, 페이지뷰는 정상적으로 데이터 수집되고 있는데
별도로 전환 추적 설정한 Lead의 경우, 이벤트 수집이 되지 않고 있습니다.
GTM 통해 설치했고 GTM 미리보기 / 실제 GA4 데이터(utm으로 확인) / 홈페이지 리드제출 결과 등으로 확인 시에는
전환 건수가 20건 이상인데, 수집되지 않는 것이 이상해서 문의드립니다.

**Desktop (please complete the following information):**
 - OS: window[e.g. iOS]
 - Browser naver whale[e.g. chrome, safari]
 - Version 최신 [e.g. 22]

**Smartphone (please complete the following information):**

**Additional context**
hokopo@ambition-plan.com
해당 주소로도 회신 가능하실까요?

**Comment by ham-daangn** [comment]
안녕하세요.
현재 전환 추적 이벤트가 아예 들어오지 않는 것으로 보아, 태그와 스크립트가 정상적으로 설치되지 않은 것 같습니다.
[구글 태그 매니저(GTM) 연동 가이드](https://bizschool.daangn.com/11328c3a-9f8f-8004-b6ea-f952a9ea7faa)를 참고하셔서 다시 한번 설치 부탁드립니다.

**Comment by yoroyoro999** [comment]
연동 가이드 참고해서 정상 설치했고, GTM 미리보기 통해서는 정상 작동 확인했습니다.
형식적인 답변 말고, 테스트 작동 후 답변 해주세요.
당근에는 전환 추적 테스트조차 없어서 당근 매체 안에서 정상 작동되는지 확인이 어렵습니다.

**Comment by ham-daangn** [comment]
안녕하세요.
[랜딩 페이지](https://orders.monki.net/mktableorder_landing)에서 상담 신청을 테스트 해보았는데, Lead 수집이 되는걸로 확인되었습니다.
광고 관리 > 전환 추적 관리에서 잠재고객 수집 데이터 수집 모수를 확인해보시면 될 것 같습니다.
감사합니다.

**Comment by yoroyoro999** [comment]
자체적으로 해결했습니다.
공통 스크립트를 페이지뷰에만 넣는 게 아니라
lead 이벤트 스크립트 삽입 시에도, 공통 스크립트를 함께 삽입해야 하네요.
이런 부분은 안내가 사전에 되었으면 합니다.

**Comment by ham-daangn** [comment]
해결 되셨다니 다행입니다.
가이드에 관련 내용 첨부하는 것을 검토하고 내부 논의 하도록 하겠습니다.
감사합니다.
