### ISSUE TITLE
[QUESTION] 안녕하세요. 잠재고객 수집 목적으로의 집행 전 전환 스크립트 설치 문의드립니다.

### ISSUE THREAD

**Issue by jaegook12** [daangn/karrot-conversion-tracker-tool-support#135]
안녕하세요.
아이웹 호스팅사의 경우는 잠재고객 수집 목적으로 스크립트 심을 때는
공통 스크립트만 심으면 되는지, 추후 카페24처럼 연동 계획 있는지 문의드립니다.

감사합니다.

**Comment by ham-daangn** [comment]
안녕하세요.
[전환 추적 코드 연동 가이드](https://bizschool.daangn.com/tracking-guide) 참고해서 진행해주시면 될 것 같습니다.
아이웹은 현재까지는 별도로 지원 계획이 없는 상황입니다.
