### ISSUE TITLE
[QUESTION] 당근 이벤트 추적코드 수집이 안 됩니다

### ISSUE THREAD

**Issue by vpdlwm** [daangn/karrot-conversion-tracker-tool-support#136]
**Describe the question**
A clear and concise description
해당 랜딩의 경우 잠재고객 수집으로 추적코드 심은 상태입니다.
근데 계속 방문 이벤트에서만 수집이 되고 있습니다. 해결방법이 있을까요?
호스팅사는 워드프레스입니다.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
![20241205_160457](https://github.com/user-attachments/assets/d6ee697c-7092-4daa-a9ad-33daf09505fa)

**Comment by ham-daangn** [comment]
안녕하세요.
페이지를 확인해보니, `window.karrotPixel.init()` 을 호출하기 전에 `window.karrotPixel.track()`을 호출하셔서 발생하는 문제인 것 같습니다.
`window.karrotPixel.init()` 을 head 태그 상단으로 옮겨보시면 좋을 것 같습니다.
감사합니다.
