### ISSUE TITLE
[QUESTION] 아임웹/ 가비아 호스팅사 연동 문의

### ISSUE THREAD

**Issue by seoyunlee2710** [daangn/karrot-conversion-tracker-tool-support#137]
**Describe the question**
A clear and concise description

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

아입웹 활용 가비아 호스팅사 구매후 사용중입니다.
해당 코드 연동하는 프로세스 공유부탁드립니다.

**Comment by ham-daangn** [comment]
안녕하세요.
[전환 추적 코드 연동 가이드](https://bizschool.daangn.com/tracking-guide) 참고하셔서 진행하시면 될 것 같습니다.
감사합니다.
