### ISSUE TITLE
[QUESTION]전환추적코드를 웹사이트연동과 이벤트스크립트 각각 설치를 했는데 수집이 전환 발생시 수집이 2개씩 되는 것 같습니다

### ISSUE THREAD

**Issue by ming-DS** [daangn/karrot-conversion-tracker-tool-support#138]
**Describe the question**
A clear and concise description

전환추적코드를 웹사이트연동과 이벤트스크립트 각각 설치를 했는데 수집이 전환 발생시 수집이 2개씩 되는 것 같습니다.
웹검색을 통해 전환 테스트후, 웹사이트 연동 추적 관리에서 전환을 확인해보니 한번 전환에 인원이나 로그가 2명씩 뜹니다.
코드를 하나만 삽입해야하는걸까요?
<img width="668" alt="스크린샷 2024-12-11 오전 9 59 45" src="https://github.com/user-attachments/assets/247769dc-5f69-4d92-8dbd-eb0184c4e404">

**Desktop (please complete the following information):**
 **- OS: [e.g. iOS]**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ham-daangn** [comment]
안녕하세요.
스크립트 설치는 하나만 해주시면 될 것 같습니다.
감사합니다.
