### ISSUE TITLE
[QUESTION] 잠재고객 수집 이벤트 스크립트 삽입 관련

### ISSUE THREAD

**Issue by moon-135** [daangn/karrot-conversion-tracker-tool-support#14]
안녕하세요,
웹사이트에서 form 제출을 통해 고객 리드를 수집하고 있습니다.
당근 광고 전환 추적이 생겼길래 사용해보고 싶은데요, 몇 가지 질문이 있습니다.

1. 전환 추적을 통해 광고 최적화(머신러닝)를 하나요?
 - 단순 전환 추적은 GA 등을 통해서도 가능한데 당근 광고 전환 추적을 사용하는 이유가 궁금해요.
2. 잠재고객 수집 이벤트 스크립트를 어디에 삽입하나요?
- form 태그 바로 아래에 해당 코드를 넣으면 되는 것인가요?

감사합니다!

**Comment by Gummybearr** [comment]
안녕하세요 :)
1. 현재 고객향으로 공개된 ML 최적화 기능은 없지만 리타게팅, 디타게팅을 당근 내부 잠재고객들을 대상으로 적용할 수 있습니다. 
2. 스크립트를 넣을 수 있는 곳에 자유롭게 넣으시면 될 것 같습니다.

**Comment by moon-135** [comment]
답변 감사합니다!

**Comment by Gummybearr** [comment]
네 좋은 하루 보내세요!
