### ISSUE TITLE
[QUESTION] 전환스크립트 미확보되어 점검 요청드립니다.

### ISSUE THREAD

**Issue by choiwansik** [daangn/karrot-conversion-tracker-tool-support#140]
**Describe the question**
A clear and concise description

**Desktop (please complete the following information):**
 - OS: chrome
 - Browser chrome
 - Version :

**Smartphone (please complete the following information):**

**Additional context**

안녕하세요. 
PLAYD_케스코 (3319463) 계정을 운영하고 있습니다.

전환 추적관리에서 
서비스신청(메인전환값)에 대한 내용이 트래킹이 되지 않아 문의드립니다.

현재 GTM을 통해 진행중에 있으며,
어떤 부분이 잘못된건지 점검 요청드립니다!

*광고주정보
- 홈페이지 : https://www.k-esco.co.kr/kesco/index.do
- 전환페이지설치 : 본 홈페이지상 견적조회 가능한 모든 페이지로 설정희망 

![케스코 GTM 전환페이지현황](https://github.com/user-attachments/assets/4c306104-6784-440d-a426-53182af2a094)
![케스코 GTM 현황1](https://github.com/user-attachments/assets/52ffaf7b-b4e7-40a1-9bed-8c682c88b635)
![케스코 GTM 현황2](https://github.com/user-attachments/assets/e1d015f3-94ea-49b5-afa8-e2855569e18c)
![케스코 GTM 현황3](https://github.com/user-attachments/assets/8d22f6e5-0901-4d90-9d58-372d6ea79cb5)
![케스코 GTM 현황4](https://github.com/user-attachments/assets/09531962-fadc-45c7-9aff-74221653ebd1)

**Comment by ham-daangn** [comment]
안녕하세요.

[GTM 연동 가이드](https://bizschool.daangn.com/11328c3a-9f8f-8004-b6ea-f952a9ea7faa) 중 태그 시퀀싱 설정이 누락된 것 같습니다.

이 부분 확인해 주실 수 있으실까요?

**Comment by choiwansik** [comment]
안녕하세요
플레이디 최완식 입니다.


네 수정하였더니 잘됩니다!

확인감사합니다.


감사합니다.
최완식 올림.



최 완 식 대리
퍼포먼스 마케팅 본부 퍼포먼스 마케팅 1팀





010.6419.4023
031.6009.9782
 ***@***.***
031.6009.9782





www.playd.com







-----Original Message-----
