### ISSUE TITLE
[QUESTION] 카페24 전환추적 정상 설치여부 확인 요청드립니다

### ISSUE THREAD

**Issue by 1d12d** [daangn/karrot-conversion-tracker-tool-support#15]
**Describe the question**
A clear and concise description
카페24에 당근 전환추적 코드 설치 완료, 전환 추적 관리 페이지에서 심은 코드는 모두 '수집중'으로 확인되고 있습니다.
정상적으로 설치되었는지 확인 부탁드립니다.

*전환추적 코드 id : 1693293689810900001
*광고 계정 id : 2281009

ㄴ 이 외에 추가 확인 필요한 부분은 요청주시면 답변으로 달아드리겠습니다. :)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Gummybearr** [comment]
안녕하세요 :) 

이벤트 수집에는 큰 문제가 없어보입니다.
