### ISSUE TITLE
[QUESTION] purchase 이벤트 전환 트래킹 이슈

### ISSUE THREAD

**Issue by kowi2002** [daangn/karrot-conversion-tracker-tool-support#16]
**Describe the question**
A clear and concise description

안녕하세요, 카페24 호스팅을 사용하고 있는 몰을 운영 중입니다. 
나머지 전환 이벤트들은 다 설치 했는데 purchase 만 계속 수집 전이라고 뜨네요. 

전환추적 ID: 1694411825697600001
광고계정 ID: 2458585

주문 완료 페이지 하단에 아래 코드를 삽입 했습니다.
코드에 문제가 있는지 확인 부탁 드립니다. 감사합니다. 

```
<!-- Danggeun Market Code 20230911-->
<script>
window.karrotPixel.track(
  'Purchase', 
  {
    'total_price': '{$total_product_price}',
    'total_quantity': '{$product_quantity}',
    'products': [{
      'id': '{$order_id}',
      'name': '{$product_name}',
      'quantity': '{$product_quantity}',
      'price': '{$product_price}',
    }]
  }
)
</script>
<!-- End Danggeun Market Code 20230911 -->

```

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Gummybearr** [comment]
<img width="740" alt="Screenshot 2023-09-13 at 4 28 42 PM" src="https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/41829700/e4d174a9-fc4c-4ba3-b6e1-40ec15f91be7">

안녕하세요 :) 
실제 값이 아닌 템플릿에 정의된 값을 보내고 있는 것으로 확인됩니다. 실제 값으로 수정부탁드립니다.

**Comment by kowi2002** [comment]
안녕하세요, 답변 감사합니다. 
제가 기본 자바스크립트 지식은 조금 있는데 개발자가 아니라 양해 부탁 드립니다... ^^;;
저렇게 변수를 사용하면 알아서 연동이 되어 값들을 가져 오는 것으로 알고 있는데 제가 잘못 이해하고 있나요?

**Comment by Gummybearr** [comment]
변수를 정의하지 않았거나 참조를 다르게 할 경우 실제 값이 연동이 되지 않을 수 있습니다.
구매 금액 연동이 힘들 경우 가이드를 참조하여 구매 이벤트만 연동하셔도 될 것으로 보입니다.
