### ISSUE TITLE
[QUESTION] 카페24 전환 수집 코드 정상 설치 여부 문의드립니다

### ISSUE THREAD

**Issue by 1d12d** [daangn/karrot-conversion-tracker-tool-support#17]
**Describe the question**
A clear and concise description

카페24에 당근 전환 추적 코드 모두 수집중으로 확인되나, 당근 비즈니스 내 구매 전환에 대한 추적값이 확인되지 않아 정상 설치되었는지 확인 부탁드립니다!

*전환추적 코드 id : 1693293689810900001
*광고 계정 id : 2281009

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by extJo** [comment]
```
https://palette.my/product/%EC%98%A4%EB%94%94%EC%84%B8%EC%9D%B4-g3-%EA%B2%8C%EC%9D%B4%EB%B0%8D-%EB%AA%A8%EB%8B%88%ED%84%B0-684cm-fhd-%ED%94%8C%EB%9E%AB/4320/category/72/display/1/#none?utm_source=carrot&utm_medium=paid_banner&utm_campaign=gaming monitor&utm_content=gaming monitor_60d-0913gm(4)_230913_palette
```
특정 소재에서 url에 fragment (#none) 이후에 쿼리파라미터가 붙어있는거 같은데요
fragment를 url의 맨 뒤에 붙이시거나 #none 과 같은 fragment를 삭제해주셔야 합니다

예시
```
https://palette.my/product/%EC%98%A4%EB%94%94%EC%84%B8%EC%9D%B4-g3-%EA%B2%8C%EC%9D%B4%EB%B0%8D-%EB%AA%A8%EB%8B%88%ED%84%B0-684cm-fhd-%ED%94%8C%EB%9E%AB/4320/category/72/display/1/?utm_source=carrot&utm_medium=paid_banner&utm_campaign=gaming monitor&utm_content=gaming monitor_60d-0913gm(4)_230913_palette
```

**Comment by 1d12d** [comment]
말씀주신대로 변경했는데, 맞게 변경했는지 확인 한 번 부탁드립니다. :)

**Comment by Gummybearr** [comment]
네 잘 설치된 것으로 보입니다.
