### ISSUE TITLE
당근마켓 전환 수 중복 체크

### ISSUE THREAD

**Issue by 23432rtea1134s** [daangn/karrot-conversion-tracker-tool-support#18]
안녕하세요,

당근마켓 광고 진행중입니다.

URL: https://xn--2e0bo0vqkf46i.com/
브랜드: 상구맥주

현재 네이버광고 및 메타광고를 통해서 상담신청을 해도 당근마켓 대시보드상에 서비스신청 메뉴로 중복으로 잡히고 있습니다.

광고관리 또는 광고보고서에서 서비스신청 수 확인으로 따로 데이터 확인하면 된다고 요청 하셔서 그렇게는 확인했는데요.

네이버 광고를 통해 구매한 전환 수치가 찍힐 때 마다
그대로 우리쪽 광고 대시보드에 듀얼로 찍히는 케이스를 확인하셨다면 다시 문의 부탁드릴게요~
- 이 부분 해결이 필요합니다.  타광고를 통해서 상담신청을 해도 중복으로 잡히고 있습니다.
- 전체적인 스크립트 및 해결방안 확인 부탁드립니다.

**Comment by Gummybearr** [comment]
안녕하세요 :) 
당근마켓 대시보드라면 광고관리, 광고 보고서페이지를 의미하시나요? 아니면 광고도구 - 전환추적관리 페이지를 의미하시나요?

**Comment by 23432rtea1134s** [comment]
![11](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/144413641/d61a9092-91d7-4acc-bc29-cfd1eea1ad08)

광고도구>전환추적관리 페이지 입니다.

당근마켓으로만 신청된걸 따로 확인하고 싶은데 보고서에서 확인할 수 있는 방법 말곤 없나요?

**Comment by Gummybearr** [comment]
네 해당 페이지는 해당 이벤트의 전체적인 모수를 추적하기 위한 목적으로 만들어졌기 때문에 당근마켓만을 필터할수는 없습니다.

**Comment by Gummybearr** [comment]
요 이슈는 닫도록 하겠습니다! 문제가 있으시면 다시 열어주세요
