### ISSUE TITLE
당근 마켓 전환 추적 코드가 정상 작동 하지않습니다.

### ISSUE THREAD

**Issue by pinachigong** [daangn/karrot-conversion-tracker-tool-support#19]
**Describe the question**
A clear and concise description

코드 id : 1694677152190200001
랜딩 url : https://open.pncg.co.kr (방문)
https://open.pncg.co.kr/landing/landing_complete.html (잠재고객수집)
광고 ID : 2145820

현재 방문 / 잠재고객 수집에 대한 값을 넣어 테스트 중인데 

방문은 공통스크립트로 페이지 방문시 체킹이 되는데 
서비스 신청 후 페이지에 걸어둔 잠재고객 수집에 대해서는 체크가 안되는 상황입니다. 

GTM으로 코드를 등록하였습니다. 

혹시 어느 부분에 문제가 있는 걸까요?

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Gummybearr** [comment]
안녕하세요 :) 
gtm으로 등록하신 코드를 다시 확인하셔야 될 것으로 보입니다. 잠재고객 수집 페이지에서는 전환추적코드가 제대로 설치되어있지 않았기 때문에 이벤트를 전송하지 못하고 그렇기 때문에 집계가 되지 않고 있습니다.

이를 확인 하기 위해서는 gtm코드를 다시 확인하고 수정하신 후에 잠재고객 수집 페이지에서 크롬 콘솔 창을 열고 window.karrotPixel을 친 후 엔터를 쳤을 때 undefined가 뜨지 않아야 합니다. 

참조 링크: https://developer.chrome.com/docs/devtools/open

**Comment by Gummybearr** [comment]
안녕하세요 :)
gtm으로 등록한 코드의 순서를 다시 확인하셔야 될 것으로 보입니다. 언급해주신 링크를 직접 방문해서 확인해보았을 때에는 전환추적도구가 제대로 세팅되지 않은 상황에서 잠재고객수집 이벤트를 발송하는 것으로 보입니다. 

코드를 수정한 이후에 크롬 브라우저 콘솔을 열고 아래와 같은 에러가 발생하지 않고 네트워크 창에서 아래와 Lead 이벤트로 이벤트를 발송하고 있다면 정상적으로 세팅되었다고 볼 수 있습니다.

![Screenshot 2023-09-15 at 1 28 10 PM](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/41829700/35381d6f-15c1-4141-a344-7a3ca2b0da88)

![Screenshot 2023-09-15 at 1 29 36 PM](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/41829700/4ce8b21a-06f2-4e57-8db2-a24ed829cb57)

**Comment by pinachigong** [comment]
코드의 순서가 잘못된것이 정확히 무슨 말씀이실까요...

스크립트가 여러개가 겹쳐서 인건가요 아니면 head가 아닌 바디 부분에 들어가있어서인가요?

**Comment by Gummybearr** [comment]
head에 이런 형식의 코드를 넣었을 것으로 보입니다.

```html
<script>
  window.karrotPixel.init('1694742255657300001');
  window.karrotPixel.track('ViewPage');
</script>
```

그다음 잠재고객 수집 페이지의 head나 body에
```html
window.karrotPixel.track('Lead')
```

의 형식의 코드가 들어가있을 것으로 보이는데요, 위 두 코드의 순서가 반대가 될 경우 karrotPixel.init이 되지 않은 상황에서 karrotPixel.track이 호출되게 되고 이 경우 댓글에 사진으로 남긴것과 같은 에러가 발생합니다.

**Comment by pinachigong** [comment]
![KakaoTalk_20230915_143052667](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/145080326/e5d7fc3c-cf61-46c5-8deb-0d571244d5f1)
![KakaoTalk_20230915_143148140](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/145080326/773dfea3-e9dc-4c23-9cd9-0c6d4e2f4c72)
위와 같이 Carrot pageview가 실행된후에, Carrot Lead 태그가 실행되도록 시퀀스 설정을 하면 정상적으로 작동 하는 걸까요?
