### ISSUE TITLE
[QUESTION] 스크립트 오류인가요..

### ISSUE THREAD

**Issue by wlgus6896** [daangn/karrot-conversion-tracker-tool-support#21]
<script src="https://karrot-pixel.business.daangn.com/0.1/karrot-pixel.umd.js"></script>
<script>
  window.karrotPixel.init('1694588814580200001');
  window.karrotPixel.track(
      'Purchase',
    {
    'total_price': '{$payed_order_price}',
    'total_quantity': '{$product_quantity}',
        
        })
</script>

이렇게 스크립트 심었는데 작동하질 않네요 ㅠㅠ

**Comment by Gummybearr** [comment]
아래 [이슈](https://github.com/daangn/karrot-conversion-tracker-tool-support/issues/20)의 중복으로 보여서 이슈를 닫았습니다.
