### ISSUE TITLE
[QUESTION] 아임웹 purchase 전환이슈

### ISSUE THREAD

**Issue by vanjeff77** [daangn/karrot-conversion-tracker-tool-support#22]
안녕하세요, 아임웹(imweb)을 이용하여 쇼핑몰을 운영하고 있습니다.
다른 이벤트들은 추적이 되고있는데, purchase가 잡히지 않고 있습니다.

![image](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/145206106/f9e6e06a-6676-4ffe-aec2-9d9ade24bfc9)

전환추적 ID: 1694675585190200001
광고계정 ID: 2470315

주문 완료 페이지 하단에 아래 코드를 삽입 했습니다.
코드에 문제가 있는지 확인 부탁 드립니다. 감사합니다.
![image](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/145206106/ebe82093-8769-4b59-a68d-f98c4c238065)

**Comment by Gummybearr** [comment]
안녕하세요 :) 
제가 확인했을 때에는 전환코드 1694675585190200001에 구매이벤트가 잡힌 것으로 보입니다.
문의주신 내용은 해결된것으로 보이는데 맞나요?

**Comment by vanjeff77** [comment]
질문을 드리기 전 구매이벤트가 잡히지 않아 아래의 그림대로, 변수들을 모두 제거하였더니, 잡히는 하는 상황으로 보입니다. 
![image](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/145206106/4d95a657-2cc5-4b85-81de-c4355f7bf9a4)

그러나, 위의 방식대로는 총 구매값을 당근 대시보드에 기록할 수 없기에, total_price 변수를 추가하고 싶습니다.
이를 위해 아래의 이미지와 같이 오늘 아임웹에서 설정을 변경하으나, 구매 이벤트가 찍히지 않는 것으로 보입니다.
![image](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/145206106/cbe2025b-def2-4b66-afd5-c3817a86f877)

관련하여 전환코드 설치과정에서 저의 오류가 있는지 확인을 도와주시면 감사하겠니다.

**Comment by Gummybearr** [comment]
안녕하세요 :) 
제가 해보았을 때는 잘 동작하는 것으로 보입니다.
