### ISSUE TITLE
[QUESTION] 구매 전환 스크립트 이슈 문의드립니다.

### ISSUE THREAD

**Issue by wlgus6896** [daangn/karrot-conversion-tracker-tool-support#23]
<script src="https://karrot-pixel.business.daangn.com/0.1/karrot-pixel.umd.js"></script>
<script>
  window.karrotPixel.init('1694588814580200001');
  window.karrotPixel.track('Purchase');
</script>

<script src="https://karrot-pixel.business.daangn.com/0.1/karrot-pixel.umd.js"></script>
<script>
    window.karrotPixel.track(
      'Purchase',
    {
    'total_price': '{$product_total_price}',
    'total_quantity': '{$product_quantity}'
        
        })
</script>

구매 완료 페이지에 해당 스크립트를 삽입해 수집 중인데요.

일부 상품은 계속 수집이 되지 않고 일부 상품은 잘 수집 되고 있어 어디서 오류가 있는지 문의드립니다.

**Comment by Gummybearr** [comment]
안녕하세요 :) 
아래 [이슈](https://github.com/daangn/karrot-conversion-tracker-tool-support/issues/19)의 답변을 참고하시어 수집되고 있지 않는 상품들에 전환추적도구가 정상적으로 설치되었는지 확인 부탁드립니다.
