### ISSUE TITLE
[QUESTION] 네이버페이 전환 추적

### ISSUE THREAD

**Issue by livewithsjsj** [daangn/karrot-conversion-tracker-tool-support#24]
안녕하세요 현재 워드프레스와 우커머스를 이용해서 자사몰을 생성하였습니다
당근마켓 광고가 핫하다 하여, 픽셀을 설치하려 하는데
일반 카드 결제의 경우 구매완료 페이지가 있지만,
네이버페이 간편결제의 경우 네이버로 화면이 넘어가서 따로 구매완료 페이지에
픽셀을 심지 못하는 상황입니다

이 경우, 어떻게 전환추적을 할 수 있는지 여쭙습니다
감사합니다

**Comment by Gummybearr** [comment]
안녕하세요 :) 
현재는 네이버페이 간편결제로 넘어갈 경우 구매완료 페이지가 네이버에 있기 때문에 구매 전환을 추적할 수 없습니다. 
팀에서도 이 문제를 알고 있기 때문에 내부 검토 후 개선 예정입니다.
