### ISSUE TITLE
당근 구매관련 추적값 오류 확인요청

### ISSUE THREAD

**Issue by eos4583** [daangn/karrot-conversion-tracker-tool-support#25]
당근매체 구매 추적코드값이 정상적으로 작동하고 있지 않는 상황입니다.

해당 값을 구매완료 페이지 최 하단에 삽입해둔 상황입니다.

<script>
window.karrotPixel.track(
  'Purchase', 
  {
    'total_price': '{30000}'

    }]
  }
)
</script>

![image](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/145628260/94e4c9bf-5ade-46f7-a3f6-3556b58587ec)

해당 위치에 삽입은 정상적으로 된거로 보이나 , 
당근 대시보드에서는 확인이 안되네요..

![image](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/145628260/a27a7e3d-7eec-43a8-a934-cd0687425946)

혹시 잘 못 삽입한걸까요?

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Gummybearr** [comment]
안녕하세요 :) 

중괄호가 없는 실제 가격이 들어가면 추적이 될것으로 보입니다.

**Comment by eos4583** [comment]
안녕하세요

중괄호 제외한, 실 판매금액을 입력해도 , 추적이 안되고 있습니다.

혹시 소재등록시 , (웹사이트 방문 그룹)  url 뒤 ,utm넘버링을 추가해서 문제가 될 수 도 있을까요?

**Comment by Gummybearr** [comment]
확률은 낮아보이지만 확인을 위해서 전환추적 코드를 알려주실 수 있나요?

**Comment by eos4583** [comment]
1694047354588000001 입니다

**Comment by Gummybearr** [comment]
확인해봤는데 광고주의 웹사이트에 오류가 있어서 구매 이벤트를 발송하지 못하거나, 이벤트를 전송하지 않는 것으로 보입니다.
크롬 콘솔 창을 열고 console 탭에 있는 오류를 해결한 뒤 네트워크 탭에서 purchase 이벤트가 정상적으로 발송되는지 확인해주세요.
참고: https://developer.chrome.com/docs/devtools/open/

**Comment by eos4583** [comment]
안녕하세요 , 
현재 확인해보니 당근 전환추적 스크립트 삽입한 부분에도 오류가있어 해당 부분 수정했습니다.

현재에도 동일하게 사이트내의 오류가 확인되는지  체크 한 번 부탁드리겠습니다.

추가로 , 해당 오류를 해결하려면 어떻게 해야하는지도 안내 부탁드리겠습니다
