### ISSUE TITLE
[QUESTION] 당근 전환 스크립트 이슈 문의

### ISSUE THREAD

**Issue by RYUssss** [daangn/karrot-conversion-tracker-tool-support#26]
현재 운영중인 당근 매체 캠페인 내 연동중인 전환 스크립트 내 이벤트 추가 삽입 진행하였는데요,

전환추적ID : 1694669105701400001
광고계정 : 2455395

광고도구>전환추적관리>상세보기 에서는 현재 구매/상세페이지조회 데이터가 수집되고 있는 것으로 확인되오나-
광고관리나 보고서에서는 해당 수치 집계되지 않고 있는 것 같아 문의드립니다.

**Comment by Gummybearr** [comment]
안녕하세요 :) 

제가 확인했을 때에는 둘다 정상적으로 잡히는 것으로 보입니다. 
다만 이벤트 페이지에서 상세페이지 조회, 구매 페이지로 가기까지 퍼널이 꽤 있는 것같다는 생각을 했습니다.
