### ISSUE TITLE
[QUESTION] 대시보드 및 보고서 내에서 전환지표 확인 불가 이슈 문의

### ISSUE THREAD

**Issue by dsjunn** [daangn/karrot-conversion-tracker-tool-support#27]
안녕하세요, 당근 전환 지표 관련하여 문의드립니다.

광고계정 : 1998645
전환추적ID : 1694487803697600001

현재 전환 추적 관리 탭에서 이벤트 모수는 정상적으로 수집되고 있습니다.
다만 운영중인 캠페인에 전환 추적 코드를 적용하였는데도 대시보드 및 보고서 상에 전환 지표가 전혀 잡히고있지 않아 문의드립니다.
전환 추적 연동은 지난주 수요일(9/20)에 진행한 점 참고 부탁드립니다.

감사합니다.

**Comment by dsjunn** [comment]
안녕하세요, 빠른 답변 감사합니다 :)

관련하여 타 광고매체(Ex. 메타, 카카오) 또한 유사한 링크(리디렉션 url)로 운영 중이며, 전환 지표가 정상적으로 집계되고 있어 혹시 다른 이슈는 없을 지 문의드립니다.

**Comment by Gummybearr** [comment]
현재는 다른 이슈는 없는 것으로 보입니다.
모바일에서 설정하신 광고를 눌렀을 때는 아래와 같은 url로 이동하게 되는데요, 당근의 웹 전환추적코드는 현재 kmckid 파라미터를 기반으로 작동하고 있으나 리디렉션된 url에는 해당 파라미터가 없습니다. 

`https://job.coupangcorp.com/cls_b?src=8019218&spec=10914022&addtag=800&ctag=cls_b&lptag=REMAKE_CarrotMarket_traffic_2049-capitalWest_image20-8-3_im_230823&itime=20230925165141&pageType=RECRUITING&pageValue=cls_b&wPcid=16909905169064099062010&wRef=&wTime=20230925165141&redirect=landing&mcid=ab92e2b5b1984d88a98c2679157c2c92`

리디렉션기반으로 동작하는 url에는 몇가지 규칙이 필요한데요, 아직은 팀에서 논의된 것이 없기 때문에 논의하여 추후에 개선하겠습니다.

**Comment by dsjunn** [comment]
답변주신 내용 확인했습니다, 감사합니다 :)
추후 반영 완료되면 말씀 부탁드립니다!
