### ISSUE TITLE
안녕하세요. 서비스신청 스크립트 전환 확인이 안되어 문의드립니다.

### ISSUE THREAD

**Issue by mmk0329** [daangn/karrot-conversion-tracker-tool-support#28]
서비스신청 스크립트를 상담완료 버튼에 삽입하였는데
실제 문의가 들어왔지만 서비스신청 항목에는 잡히지 않습니다.

**Comment by Gummybearr** [comment]
안녕하세요 :) 

전환추적코드 번호가 어떻게 되시나요?

**Comment by mmk0329** [comment]
​안녕하세요.전환추적코드 번호 전달드립니다.1693445940536000001감사합니다:)
------ Original Message ------
Date: Tuesday, Sep 26, 2023 10:09:46 AM

**Comment by Gummybearr** [comment]
답변을 드리기 전에 문의를 조금 더 구체화하면 좋을 것 같아서 질문드립니다.

실제로 테스트를 하면서 상담신청 버튼을 눌렀을때 전환 추적 관리 -> 서비스 신청 항목의 수치가 업데이트 되는 것은 확인하였으나 
실제 광고를 보고 서비스신청을 한 사용자가 광고관리와 보고서에 잡히지 않았다는 것이죠?

**Comment by mmk0329** [comment]
​네 맞습니다.실제 테스트로 문의를 하면 서비스 신청 항목의 수치가 상세보기에서는 확인되는데데이터 모집 모수에는 잡히지 않습니다지금 테스트 문의가 2건 들어왔는데 1건만 데이터 모집 모수에 잡혔습니다
------ Original Message ------
Date: Tuesday, Sep 26, 2023 10:31:09 AM

**Comment by Gummybearr** [comment]
이것은 중복을 제어하는 로직이 있기 때문에 그런 것으로 정상적인 동작입니다.

구매 이벤트를 제외하면 중복을 세지 않고 있으며 이것은 전환 추적 관리에 잡히는 데이터가 사용자 수임을 보여주기 위함입니다. 

이 경우에도 최근 24시간 내 로그를 통해서는 모두 정상적으로 집계된 것을 확인할 수 있습니다.

**Comment by mmk0329** [comment]
​어제 25일날 들어온 문의같은경우에는 광고 대시보드 서비스 신청에서 카운팅이 안되어있습니다.대시보드에서 확인 가능한 방법 문의드립니다.감사합니다:)
------ Original Message ------
Date: Tuesday, Sep 26, 2023 10:45:49 AM

**Comment by Gummybearr** [comment]
현재는 광고를 통해 들어오지 않은 문의이거나 사용자가 광고를 통해 접근한 화면에서 이탈한 이후 브라우저 정보를 수집할 수 없는 별도의 환경에서 url을 기입하여 전환된 경우에는 집계되지 않을 수 있습니다.

**Comment by mmk0329** [comment]
​현재 해당홈페이지로 광고진행하는 매체는 당근 입니다.당근 외에 해당 홈페이지로 유입할수있는 경로가 없습니다.네이버, 구글에서 검색시에도 해당 홈페이지 확인이 안됩니다.기존에 유입되었던 고객이 url을 저장해두었다가 다시 접속 후 문의를 남기는경우 간접전환으로 체크가 되는것으로 알고있는데간접전환 추적 기간은 몇일 인가요?
------ Original Message ------
Date: Tuesday, Sep 26, 2023 10:52:26 AM

**Comment by Gummybearr** [comment]
이벤트마다 조금씩 다를 수는 있으나 서비스 신청의 경우 7일을 간접전환 기간으로 잡고 있습니다.
따라서 이탈후 기입한 url이 완전히 동일했다면 url에 추적 파라미터가 달려있기 때문에 문제없이 집계가 되었을 것입니다.
서버 내부에도 오류 로그는 보이지 않아서 이후에도 계속 발생한다면 커뮤니케이션하는 세일즈 채널이나 이슈를 다시 열어주실 수 있나요?

**Comment by mmk0329** [comment]
​서버 내부에도 오류 로그는 보이지 않아서 이후에도 계속 발생한다면 커뮤니케이션하는 세일즈 채널이나 이슈를 다시 열어주실 수 있나요?이부분을 정확하게 이해하지 못하였습니다.세일즈 채널, 이슈부분 다시 설명 요청드립니다.감사합니다:)
------ Original Message ------
Date: Tuesday, Sep 26, 2023 11:19:07 AM

**Comment by Gummybearr** [comment]
문제가 지속될 경우 (소통하시는 분이 있는 경우)당근 광고 세일즈분을 통해 문의해주시거나, 깃헙에 이슈를 열어주실수 있나요?
현재는 추정되는 이슈가 없기 때문에 확인이 어려운 점 양해부탁드립니다.
