### ISSUE TITLE
전환추적 도구가 정상적으로 작동 하는지 궁금합니다.

### ISSUE THREAD

**Issue by pinachigong** [daangn/karrot-conversion-tracker-tool-support#29]
**Describe the question**

전환 코드 ID : 1694757321701400001

추적 스크립트 삽입 URL : https://open.pncg.co.kr/

위 사이트에 페이지뷰 이후 잠재고객수집 데이터 확인을 위한 신청 완료 페이지의 LEAD 스크립트가 정상적으로 작동 하는지 궁금합니다. 

전환추적도구의 모수만 체킹이 되고 심어둔 utm 값은 확인이 되지 않고있습니다.

당근 내 수집 목록에도 체킹이 되지 않는 상태이고요

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Gummybearr** [comment]
안녕하세요 :) 

모수만 체킹이 되고 심어둔 utm 값은 확인이 되고 있지 않다는 말을 제가 이해했는지 확인하고 가면 좋을 것같아 질문드립니다.

광고 소재로 등록한 소재의 url을 통해서 상담신청을 했으나 이벤트를 발송하는 주소만 당근 전환추적코드에 잡히고 소재에 기입한 utm값은 잡히지 않는다는 말씀이 맞으실까요?

**Comment by pinachigong** [comment]
네 맞습니다 utm값은 전혀 잡히지않아 문의 드립니다.

**Comment by Gummybearr** [comment]
이는 전환추적도구를 발송하는 페이지가 `https://open.pncg.co.kr/landing/landing_complete.html`이기 때문입니다. 
발송하시는 url에도 utm이 들어갈 수 있도록 광고주분측의 url을 수정해주시면 전환추적관리 -> 데이터수집 로그에서도 확인이 될 것으로 보입니다.

**Comment by pinachigong** [comment]
URL을 어떤 식으로 수정을 해야하는걸까요?? 저희가 개발 쪽에 대해선 잘 모르는 상태여서 문의드립니다.

**Comment by Gummybearr** [comment]
상담신청 페이지를 눌렀을때 `https://open.pncg.co.kr/landing/landing_complete.html` 페이지로 그냥 이동하기보다 `https://open.pncg.co.kr/landing/landing_complete.html?여기에소재에 세팅한 utm 파라미터들이 들어가게 세팅` 형식으로 들어가도록 해야 될 것으로 보입니다.

**Comment by pinachigong** [comment]
저희가 정확하게 질문을 드리고자 하는 부분은 현재 다른 매체에서 찍히는 모수까지 전환추적에서 확인은 가능한데 
저희가 넣은 값이 정상적으로 작동을 하고있는 부분인지 입니다.

전혀 신청이 들어오지않아서 당근내에서 확인이 어려운건지 
아니면 스크립트를 잘못심어서 체킹이 안되는지에 대해 문의 드립니다!

**Comment by Gummybearr** [comment]
스크립트는 정상적으로 심으신 것으로 보입니다.
실제 사용자들에게 내려간 링크 중 하나를 클릭하여 상담신청을 해보니 데이터가 잘 쌓이는 것을 확인했습니다.
테스트를 위해 발생시킨 전환이 1건 있는 점을 광고 성과 데이터를 볼때 감안해주시길 바랍니다.

**Comment by pinachigong** [comment]
넵 그럼 광고를 통해 신청시 광고관리 내에서도 모수가 체킹이 되겠군요! 

감사합니다.
