### ISSUE TITLE
[QUESTION] 질문 테스트

### ISSUE THREAD

**Issue by extJo** [daangn/karrot-conversion-tracker-tool-support#3]
**Describe the question**
질문에 대한 내용을 상세히 작성해주세요

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
추가적으로 설명을 작성해주세요

**Comment by myzon2** [comment]
Desktop : WINDOW 10
브라우져 :  크롬

**[ 질문 ]
아래 가이드 URL의  "3. 이벤트 스크립트 설치하기 " 에서 Login 이벤트를 설치 중인데요,**
(   https://bizschool.daangn.com/43922c93-2958-42c3-811f-3546d17e80e1  )

**로그인 성공 시,    window.karrotPixel.track('Login'); 를 넣었는데 다음과 같은 에러가 납니다.**
login.do:2188 Uncaught TypeError: Cannot read properties of undefined (reading 'track')
    at Object.success (login.do:2188:25)
    at i (jquery.js:2:27983)
    at Object.fireWith [as resolveWith] (jquery.js:2:28749)
    at A (jquery.js:4:14203)
    at XMLHttpRequest.<anonymous> (jquery.js:4:16491)

왜 이런 에러가 날까요?


**물론, 아래의 공통 스크립트는 head 사이에 위치해있습니다.**
 
<script src="https://karrot-pixel.business.daangn.com/0.0.3/karrot-pixel.umd.js"></script>
<script>
  window.karrotPixel.init('1689035235009700001');
  window.karrotPixel.track('ViewPage');
</script>

**Comment by extJo** [comment]
@myzon2 안녕하세요, 새 이슈로 작성해주실 수 있을까요?

**Comment by myzon2** [comment]
넵 새 이슈로 등록하였습니다.
