### ISSUE TITLE
[QUESTION] 카페24 구매 이벤트 추적 이슈 발생

### ISSUE THREAD

**Issue by vanjeff77** [daangn/karrot-conversion-tracker-tool-support#30]
**Describe the question**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
안녕하세요, 카페24에서 전환추적을 하기위하여, 공통스크립트 및 구매전환용 스크립트를 삽입하였으나, 구매가 실제로 발생했음이 카페24에서 확인되고, GA로도 확인됨에도 불구하고 당근에서는 확인되지 않고 있습니다. 혹시 제가 스크립트 설치 중에 놓친 부분이 있을지 가이드를 주시면 감사하겠습니다. 
![image](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/145206106/81fb1cca-3506-4750-b483-de9c5820bde4)
![image](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/145206106/e0544d0e-201d-4369-a4ea-7e08a67b912b)

**Comment by Gummybearr** [comment]
추가로, 주문 완료 페이지에서는 웹전환추적도구가 잘 세팅되지 않은 것을 확인할 수 있는데, 이는 아래 [문의](https://github.com/daangn/karrot-conversion-tracker-tool-support/issues/19)를 참고하시어 코드의 실행 순서를 수정해주시길 바랍니다.
<img width="653" alt="Screenshot 2023-09-26 at 6 16 30 PM" src="https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/41829700/c26e1da4-8bd8-4c15-9789-c05676dffcaf">

**Comment by vanjeff77** [comment]
안녕하세요, 다음과 같이 액션하였지만, 여전히 안 잡히는 것 같습니다ㅜㅜ 도움이 필요합니다.
**(1) 기존에 GTM을 통한 공통 스크립트 삽입 대신, 헤드 부분에 공통 스크립트 삽입
(2) 주문완료 페이지의 스크립트 수정**

```
<!-- Danggeun Market Code -->
<script>
window.karrotPixel.track(
  'Purchase', 
  {
    'total_price': '$total_product_price',
    'total_quantity': '$product_quantity',
    'products': [{
      'id': '$param',
      'name': '$product_name',
      'quantity': '$product_quantity',
      'price': '$product_price',
    }]
  }
)
</script>
<!-- End Danggeun Market Code -->
``` 

![image](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/145206106/0e247882-92a4-49f8-b92c-62f6b80e1ec8)

**Comment by vanjeff77** [comment]
변수연동과, 웹 전환추적도구 세팅도 잘 마쳤는데 무엇이 문제인지 잘 모르겠습니다 ㅜㅡㅜ 도움이 필요합니다

**Comment by Gummybearr** [comment]
@vanjeff77 안녕하세요 :) 지금 확인했을때는 집계된 구매 이벤트가 있는 것으로 보이는데 문제가 해결되신게 맞나요?

**Comment by vanjeff77** [comment]
안녕하세요,
여러가지 방식으로 수집을 시도해보았는데.
**구매 이벤트 자체만 포함한 코드는 잘 작동**하나,


<script>
window.karrotPixel.track('Purchase');
</script>




![image](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/145206106/62fafc4b-3bfd-4db0-b44d-1495e1385d5b)









  
 
 
 
**구매전환값을 포함하는 코드**를 삽입할시에는, 구매 이벤트 자체를 수집못하는 것 같습니다.

<script>
window.karrotPixel.track(
  'Purchase', 
  {
    'total_price': '{$total_product_price}'
  }
)
</script>



![image](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/145206106/179c7439-3473-4cd0-9a8b-37804c15ce13)



카페24에서는 혹시 구매전환값을 수집하기 어려운 것인지, 도움을 요청드립니다.
