### ISSUE TITLE
당근마켓 카페24 구매 수집이 안되요

### ISSUE THREAD

**Issue by iocompany22** [daangn/karrot-conversion-tracker-tool-support#31]
![77777777777](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/147492953/f7dd1a56-ddfe-429d-a9f5-0c7e24a7aee0)
![20230921_180122](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/147492953/e7db4acc-99c5-460e-9a5f-56a74976b323)

전환 추적 코드 ID : 1692331963359700001
광고계정 ID : 2347894

**Comment by Gummybearr** [comment]
안녕하세요 :) 

아래의 [문의](https://github.com/daangn/karrot-conversion-tracker-tool-support/issues/30)와 비슷한 내용인 것으로 보입니다. 
카페24가 전환값을 담고 있는 변수명이 다르거나 하는 이유로 실제 전환값이 변수에 들어가지 않으면 말씀하신것처럼 수집이 되지 않을 수 있습니다. 비슷한 문의가 몇건 있었던 것으로 기억해서 우선은 구매금액을 제외하고 수집해주실 수 있나요? 현재는 카페24측에서 구매값들을 어떻게 받아올 수 있는지 확인이 필요할 것 같습니다.

**Comment by iocompany22** [comment]
<script>
window.karrotPixel.track(
'Purchase',
{
'total_price': '{$total_product_price}',
'total_quantity': '{$product_quantity}',
'products': [{
'id': '{$product_no}',
'name': '{$product_name}',
'quantity': '{$product_quantity}',
'price': '{$product_price}'
}]
}
)
</script>



이렇게 넣었어요 아직도 구매가 안잡히네요. 어떻게해야할까요 ㅠ

**Comment by Gummybearr** [comment]
실제 변수가 담기지 않았기 때문에 서버에서 거부하고 있는 것입니다.  이 변수를 받아올 수 있는 방법은 호스팅사마다 다를 수 있기 때문에 일괄적인 안내를 드리기는 어려운점 양해 부탁드립니다. 해당 값을 알 수 없는 경우에는 아래와 같이 요청을 보내면 구매 이벤트만 집계할 수 있습니다.

`('Purchase', {})`
