### ISSUE TITLE
[BUG] 전환 추적 코드 생성 불가 이슈

### ISSUE THREAD

**Issue by KSJUHEE** [daangn/karrot-conversion-tracker-tool-support#32]
**Desktop (please complete the following information):**
 - OS: [Window]
 - Browser [chrome]
 - Version [118.0.5993.71]

**Additional context**
하기 이미지와 같이, 전환 추적 코드 추가 시 오류 발생하나, 정확한 원인을 알 수 없어 진행 불가한 상황입니다.
확인 부탁 드리겠습니다.
(오류 메시지 : 지원하지 않거나, 잘못된 URL입니다.)
![image](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/43923313/711109a4-e5dd-4df4-89d6-d70243a52358)

감사합니다. :)

**Comment by KSJUHEE** [comment]
웹사이트 URL도 함께 전달 드립니다!
ㄴ https://www.grip.show/seller

**Comment by extJo** [comment]
@KSJUHEE 
안녕하세요. 혹시 Url 입력시에 https:// 도 추가해서 입력해보셨을까요?

**Comment by KSJUHEE** [comment]
@extJo 안녕하세요, 담당자님!
넵! https:// 추가하여 입력 시 하기와 같이 [도메인 주소까지만 입력해주세요] 오류 알럿 확인됩니다!
![Uploading image.png…]()

**Comment by extJo** [comment]
`https://grip.show` 로 입력하시면 됩니다

**Comment by Gummybearr** [comment]
안녕하세요 :) 
웹 추적 주소는 path나 query param을 허용하고 있지 않습니다. 위에서 언급해주신 것처럼 https://grip.show, 훅은 https://www.grip.show
이렇게 등록해주세요.

실제 도메인이 www.grip.show로 시작하면 후자를, 둘다 쓰고 있으면 둘다 등록하는 것을 권장드립니다.

**Comment by KSJUHEE** [comment]
@extJo @Gummybearr 안녕하세요, 담당자님!
빠른 확인 감사합니다.
말씀 주신 도메인으로 등록해보겠습니다. 감사합니다 :)

**Comment by KSJUHEE** [comment]
@extJo @Gummybearr 안녕하세요, 담당자님! 점심 식사 맛있게 하셨을까요?
다름 아니라 추가 문의사항이 있어 여쭙습니다(__)

말씀주신 대로 전환 코드 생성 완료되어, 사이트에 삽입하고자 하는데요!
gtm내에 삽입 진행해도 이상 없을까요?
확인 부탁 드리겠습니다🙏
