### ISSUE TITLE
[QUESTION] 메이크샵 구매 이벤트 관련 문

### ISSUE THREAD

**Issue by yoojin1019** [daangn/karrot-conversion-tracker-tool-support#33]
아래 스크립트 내 변경 해야 할 변수가 중괄호 {} 까지 인지, 한글 텍스트만 변경 하면 되는지 문의 드립니다. 

<script>
window.karrotPixel.track(
  'Purchase', 
  {
    'total_price': '{구매금액}',
    'total_quantity': '{구매수량}',
    'products': [{
      'id': '{상품ID}',
      'name': '{상품명}',
      'quantity': '{상품수}',
      'price': '{상품가격}',
    }]
  }
)
</script>

**Comment by Gummybearr** [comment]
안녕하세요 :) 
변수를 담는 자리로, 실제 구매와 관련된 수를 중괄호 없이 담아야 합니다.

예시
```json
{
  'total_price': '100',
  'total_quantity': '1',
  ..후략
}
```
