### ISSUE TITLE
전환 스크립트 관련 문의 드립니다. 

### ISSUE THREAD

**Issue by nhmontyhly** [daangn/karrot-conversion-tracker-tool-support#34]
안녕하세요. 당근마켓 전환 이벤트 스크립트 삽입 중에 있는데요,
혹시 아래 스크립트를 심을 때,
상품이 다양하고 구매페이지는 동일한 곳에 떨어질 경우는 스크립트 삽입을 어떻게 해야할까요?

<script>
window.karrotPixel.track(
  'Purchase', 
  {
    'total_price': '{구매금액}',
    'total_quantity': '{구매수량}',
    'products': [{
      'id': '{상품ID}',
      'name': '{상품명}',
      'quantity': '{상품수}',
      'price': '{상품가격}',
    }]
  }
)
</script>

**Comment by nhmontyhly** [comment]
아 참고로, 카페24 통해서 페이지 운영 중에 있습니다!

**Comment by Gummybearr** [comment]
안녕하세요 :) 
페이지에 있는 모든 상품의 id와 상품명을 기입하는 것은 권장하지 않습니다
구매한 상품을 입력할 때 의미가 있는 영역이기에 불가하다면 products를 그냥 빈배열로 입력하는 것을 대신 권장드립니다
