### ISSUE TITLE
[QUESTION] 구매 전환스크립트 사용

### ISSUE THREAD

**Issue by livewithsjsj** [daangn/karrot-conversion-tracker-tool-support#35]
231025

안녕하세요.
현재 워드프레스, 우커머스, flatsome theme 사용 중입니다.

(1) 구매 완료 이후에 떨어지는 페이지가 한 페이지로 모두 동일한데,
어떻게 설치해야 하는지 / 어디에서 정상적으로 금액과 수량이 수집되고 있는지 몰라서 문의드립니다.

현재 구매완료 페이지에
`
<script>
window.karrotPixel.track('Purchase', {

  'total_price': '<?php echo $order->get_total(); ?>', // 구매 금액을 동적으로 설정

  'total_quantity': '<?php echo $order->get_item_count(); ?>' // 구매 수량을 동적으로 설정

});
</script>
`

위 스크립트를 넣었습니다.
구매 전환은 추적되는 듯 한데, 구매 금액과 quantity가 정상적으로 수집되는지 확인하는 방법을 모르겠습니다.
전환 추적에 있어 금액은 ROAS분석에 필요하기에 꼭 넣고 싶습니다.
동적으로 가격을 가져오는 방법이 있을 듯 한데 몰라서 일단 제가 위처럼 적용해보았습니다.
(중괄호({})에 포함된 내용을 서비스 내 실제 데이터 값으로 변경하라고 메뉴얼에 되어 있는데, 구매완료 페이지가 한 페이지이기에 실제 데이터값을 동적으로 가져와야 할 듯 한데, 실제 데이터값을 자동으로 가져오는 방법을 정확히 모르겠습니다...)

-추가 231027-
테스트해보니 구매완료의 경우 위 스크립트는 작동을 안하네요 ㅠ
`
<script>
window.karrotPixel.track('Purchase', {});
</script>
`

일단 위 스크립트로 대체해둔 상태입니다

(2) 장바구니 담기 픽셀의 경우 장바구니와 동적으로 연동되어야 한다는 내용을 보아서, 아래와 같이 삽입했습니다.

`function addKarrotPixel() {
  var addToCartButton = document.querySelector('.single_add_to_cart_button.button.alt.disabled.wc-variation-selection-needed');
  
  if (addToCartButton) {
    addToCartButton.addEventListener('click', function() {
      // 당근마켓 픽셀 코드 실행
      window.karrotPixel.track('AddToCart');
    });
  }
}

// 페이지가 완전히 로드되면 픽셀 코드를 실행
if (document.readyState === 'complete') {
  addKarrotPixel();
} else {
  window.addEventListener('load', addKarrotPixel);
}
`

그런데 Snippet automatically deactivated due to an error on line 2:
Syntax error, unexpected token "var". 라는 오류문이 나옵니다.

문제가 무엇인지 몰라 여쭙습니다.

두 가지 케이스 모두 페이스북 픽셀이나 틱톡처럼 우커머스용 플러그인이 없어서 수동으로 픽셀을 심고 있는데,
제가 초보여서 잘 몰라 문의 남깁니다.

감사합니다.

**Comment by Gummybearr** [comment]
안녕하세요 :) 
워드프레스나 우커머스의 동작방식에 대해서는 잘 알지 못하여 답변을 드리기 어려운점 양해 부탁드립니다.
구매 건수나 금액에 대한 정확한 정보는 우커머스측에 문의드리는 것을 제안드립니다.
