### ISSUE TITLE
[QUESTION] 데이터 추적이 잘 안되는 느낌인데

### ISSUE THREAD

**Issue by adogbowl** [daangn/karrot-conversion-tracker-tool-support#36]
버튼 클릭으로 처리 할때

window.karrotPixel.track('Lead');

위 코드만 단순하게 클릭 시점 후에 바로 로드 시키면 되는건가요? 

수집이 실시간이 아닌건지 되는건지 안되는건지 잘 안되는거 같습니다. 

가이드 메뉴얼에 보면 전부 페이지 로딩 후 시점으로 보이는데 버튼 클릭 가이드는 없나요?

로딩 후 시점이라고 해도 방금 테스트 하나 했는데 수집이 안되고 있는데 수집 시간이 몇분? 몇시간? 걸리는건가요?

GA4 , 구글애드워즈 기타 등등 모두 동일한 시점으로 테스트 했는데 당근만 작동을 안해요... 원인을 알고 싶습니다.

**Comment by extJo** [comment]
@adogbowl 안녕하세요~ 전환추적코드 및 광고주 명 알려주시면 더 도울 드릴 수 있을거같습니다

**Comment by adogbowl** [comment]
프랭크버거메인
ID 1698709498013100001

**Comment by adogbowl** [comment]
작동을 하도 안해서 강제로 작동 시키도로 아예 그냥 html 공 페이지 하나 만들어서 해봤는데 겨우 1개 들어왔습니다.

karrot-pixel.umd.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'pack')
    at f.karrotPixel.window.karrotPixel.e.track (karrot-pixel.umd.js:1:112694)
    at test.html:22:22

그런데 공페이지에서 위와 같은 오류가 발생 했다고 나오긴 합니다.


도메인이 따로 있는 페이지는 아니고 그냥 로컬PC에서 html 파일 한개 만들어서 로딩 버전으로 작업 해서 테스트 중입니다.

**Comment by adogbowl** [comment]
![image](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/45092579/0384ae09-e9f9-4e37-bfbc-da20aa7a2f3d)
![Uploading 스크린샷 2023-11-01 오후 5.03.41.png…]()

**Comment by adogbowl** [comment]
![스크린샷 2023-11-01 오후 5 04 42](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/45092579/d5767b3d-faf3-4684-9cce-06588716582e)

**Comment by adogbowl** [comment]
지금 보니까 또 수집이 됐는데 ;;; 수집에 몇분정도 걸리는건가요?

**Comment by extJo** [comment]
안녕하세요~ 로컬에서는 수집에 대해서 보장해드리진 않습니다. 제가 확인했을 때는 
https://frankburger.co.kr/ 에 Lead 까지 수집을 잘 할 수있는걸로 보입니다

**Comment by extJo** [comment]
그리고 모바일인 경우에 URL이 https://m.frankburger.co.kr/ 로 랜딩되는걸로 확인되는데요, 
해당 서브도메인도 전환 추적 관리 > 해당 전환 추적 코드 > 더보기 > 웹사이트 연동추가로 추가 하셔야합니다 :)
