### ISSUE TITLE
[QUESTION] DB스크립트 코드 설치 위치 문의 드립니다.

### ISSUE THREAD

**Issue by ad2-1** [daangn/karrot-conversion-tracker-tool-support#37]
</head> 태그 바로 위에 [공통스크립트]를 삽입완료하였으며
[DB스크립트] 삽입도 된걸로 알고 있는데, 설치확인이 안된듯하여 재시도 진행중입니다.
[공통스크립트]는 <head> 와 </head> 태그 사이에 삽입하면 되는걸로 확인하였는데요
[DB스크립트] 는 위치가 어디인지 확인 부탁드립니다. 
똑같이 <head> 와 </head> 태그 사이에 삽입하면 되는지 확인 부탁드립니다.

**Comment by seongjunhwang** [comment]
안녕하세요.

공통 스크립트 및 이벤트 스크립트 코드 등록과 관련해서는 가이드 문서에서 확인이 가능한데요.
[가이드 문서](https://bizschool.daangn.com/43922c93-2958-42c3-811f-3546d17e80e1)

공통 스크립트의 경우 head 태그 내 삽입을 권장드리며,
이벤트 스크립트는 해당 이벤트가 발생하는 페이지 내 삽입을 권장드리고 있습닙다.
