### ISSUE TITLE
[QUESTION] 전환 추적 코드가 발동되지 않습니다

### ISSUE THREAD

**Issue by KSJUHEE** [daangn/karrot-conversion-tracker-tool-support#38]
**Desktop (please complete the following information):**
 - OS: Window
 - Browser chrome
 - Version 118.0.5993.71

**Additional context**
가이드에 따라 스크립트로 코드 설치 후 라이브 진행하였으나
일부 이벤트가 [수집 전]으로 확인되는 상황입니다.
![image](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/43923313/e12b4071-c41e-4f6e-90a0-70d50db00602)

내부 테스트 시에는 발동에 이상 없는 것으로 보여, AD Sales 팀을 통해 문의 드렸었는데요!
당시 설치 재확인이 필요한 것으로 말씀 주셔서 아래와 같이 조건 변경하여 재배포 하였으나
여전히 매체 내에서 [수집 전]으로 확인되어서요. :(

- 기존 : path = 셀러 조건에서 발동
- 변경 : path seller 포함 조건에서 발동

현재 연동된 웹 사이트([https://grip.show/])와 실제 이벤트 집계가 필요한(전환 스크립트를 설치한) 사이트([https://www.grip.show/seller])가 상이한 상태인데,
이것도 스크립트 미발동의 원인이 될 수 있을까요?

내부에서는 정확한 원인 파악이 어려운 상황으로, 확인 부탁 드리겠습니다🙏

**Comment by extJo** [comment]
서브도메인(https://www.grip.show)도 등록하고 테스트 해보셨을까요??
만약 등록하시지 않으셧다면 아래 코멘트를 참고하셔서 테스트 후 말씀해주세요~ :)

https://github.com/daangn/karrot-conversion-tracker-tool-support/issues/36#issuecomment-1788577387

**Comment by KSJUHEE** [comment]
안녕하세요, 현재는 홈페이지(https://grip.show/)만 등록해 둔 상태인데요!
메인 도메인 및 전달주신 코멘트 참고하여 진행해보겠습니다 🙏

**Comment by KSJUHEE** [comment]
@extJo 안녕하세요, 이벤트 집계 필요한 셀러 입점 페이지(https://www.grip.show/seller) 는 등록이 불가하여 우선 보류, 서브 도메인([https://www.grip.show]) 등록 완료하였는데요!
[수집전] > [수집중]으로 상태 변경되기까지 시간이 조금 소요되는 것이 맞을까요?

더불어 사이트 1건을 잘못 등록하였는데, 삭제하는 방법이 있을지도 확인 요청 드립니다!

**Comment by extJo** [comment]
@KSJUHEE 
> [수집전] > [수집중]으로 상태 변경되기까지 시간이 조금 소요되는 것이 맞을까요?
수분내로 수집상태를 확인하실 수 있고, 수집된것으로 파악되는데 맞을까요?

> 더불어 사이트 1건을 잘못 등록하였는데, 삭제하는 방법이 있을지도 확인 요청 드립니다!
이 부분은 삭제는 불가능하며 만약 정리하시길 원한다면 새로운 전환 추적 코드를 발급하셔서 새로 연동하셔야합니다

**Comment by KSJUHEE** [comment]
@extJo 담당자님, 감사합니다! 지금은 수집되는 것으로 확인되네요!!! 🙏

**Comment by extJo** [comment]
@KSJUHEE 넵 해당 이슈는 해결된걸로 보고 닫겠습니다~!
