### ISSUE TITLE
[QUESTION] 공통스크립트, 전환스크립트 삽입했는데 확인이 안됩니다 

### ISSUE THREAD

**Issue by jung6427** [daangn/karrot-conversion-tracker-tool-support#39]
안녕하세요. 

스크립트를 삽입했는데 
방문자수 0 / 전환건수 0 
확인이 안되는 문제가 있어 문의드립니다. 

https://rent.krcs.kr/
현재 해당 도메인으로 보안서버인증서 설치를 했고 
head 사이에 스크립트를 삽입했습니다.

https://rent.krcs.kr/result_a.php
여기 완료 페이지에도 
공통 스크립트와 전환스크립트도 삽입했습니다. 

도메인에 특이사항이 있다면 서브 도메인입니다. 
다른 사이트로 리다이렉션 되는것도 아닌데 
왜 적용이 안되는지 ㅠ 궁금합니다... 
(https://rent-krcs.kr  해당 도메인으로 연결했을때는 방문자수 집계가 되었습니다. )

![랜딩페이지_공통스크립트 삽입](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/102494450/957e47cb-b964-44a4-93a6-9b0825443d3f)

![완료페이지_스크립트 삽입](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/102494450/740f91db-f586-4f8c-87db-c17c66ccac0b)

확인 꼭 좀 부탁드립니다. 
감사합니다.

**Comment by Gummybearr** [comment]
안녕하세요 :)
https://rent-krcs.kr
만 등록을 하신 것으로 보입니다. 
https://rent.krcs.kr
도 등록하시면 정상적으로 집계될것으로 보입니다

**Comment by jung6427** [comment]
답변감사합니다. 
https://rent.krcs.kr/
해당 도메인으로 전환 추적 코드 추가에 
웹사이트 url에 등록 해달라는 말씀이 맞으실까요~?

**Comment by Gummybearr** [comment]
맞습니다~
