### ISSUE TITLE
[QUESTION]  추적 스크립트 추가후 수집중 으로 업데이트 되는데 얼마나 딜레이 있을까요? for 디버깅

### ISSUE THREAD

**Issue by kimduksoo** [daangn/karrot-conversion-tracker-tool-support#40]
Vue 에서 추적 코드 아래와 같이 추가 시도중 입니다.

데이터 수집중으로 변경이 되고 있지 않는데 혹시 수집중으로 변경되는데 딜레이가 있을까요?
아니면 다른 문제가 있을까요?

**Comment by extJo** [comment]
오늘 이벤트 지연 처리중이라 수십분 내에 확인이 가능합니다.
이슈가 처리되면 다시한번 알려드리겠습니닷!

**Comment by kimduksoo** [comment]
넵! 알겠습니다. 
대기 하겠습니다 (__)

**Comment by kimduksoo** [comment]
정상적으로 수집 되는걸 확인했습니다. 
빠른 확인 감사합니다 (__)

**Comment by kimduksoo** [comment]
추적코드 추가하면서 문득 든 생각인데 
가볍게 건의 사항 하나 남기겠습니다 (__) 

상세페이지 조회에서 따로 어떠한 상품에 대한 상세페이지 조회인지 인식할 수 있는 인자를 받지 않아 
하나의 쇼핑몰에서 다양한 상품을 팔 경우 A, B 상품의 사용자가 섞이게 될 거 같습니다. 
이로인해 A, B 상품의 성격이 상이할 경우 타겟팅 효력이 떨어질 거 같습니다. 

요약: 지금 모집한 데이터로는 상품별 타겟팅 정보가 수집되지 못하고 서비스 타겟팅 데이터 수집 가능

ps. 물론 광고 소제에 추적 코드를 일일이 연결하는 부분에서, 광고별 추적 코드를 분리하긴 하지만 이럴 경우 광고주 홈페이지에서 상품별 추적 아이디를 분기하는 코드를 추가해야 합니다.

**Comment by Gummybearr** [comment]
안녕하세요 :)

좋은 피드백 감사합니다. 이후에 @extJo 님과 리타게팅/디타게팅을 개선할때 참고하겠습니다!
