### ISSUE TITLE
[QUESTION] 구매 수는 잡히는데 구매 금액이 잡히지 않습니다.

### ISSUE THREAD

**Issue by JiHyun6896** [daangn/karrot-conversion-tracker-tool-support#41]
전환 추척 ID : 1694588814580200001

<script>
    window.karrotPixel.track(
      'Purchase',
    {
    'total_price': '{$product_total_price}',
    'total_quantity': '{$product_quantity}'
        
        })
</script>

현재 해당 스크립트 구매완료 페이지에 삽입 되어 있는데 구매 수는 데이터에 집계가 되지만 구매 금액은 데이터에 집계 되지 않는 현상이 발생하고 있는데 원인을 알 수 있을까요?

**Comment by Gummybearr** [comment]
@JiHyun6896  안녕하세요 지현님 :) 우선 답변이 늦어 죄송합니다.

total_price, total_quantity에는 실제 구매금액, 구매 개수를 담아야 합니다. 
실제 구매금액과 개수를 알 수 있는 방법은 직접 구축한 사이트인지, 호스팅사인지에 따라 다를 수 있습니다.
실제 구매금액이나 개수를 알기 어렵다면 현재처럼 구매 개수만 연동을 하여도 될 것으로 보입니다.
