### ISSUE TITLE
카페24 구매 스크립트 문의

### ISSUE THREAD

**Issue by frafdsaf** [daangn/karrot-conversion-tracker-tool-support#42]
주문완료 페이지에 아래와 같이 넣은 상태인데, 문제가 되는 부분이 있을까요?

<script>
window.karrotPixel.track(
  'Purchase', 
  {
    'total_price': '{$total_product_price}',
    'total_quantity': '{$product_quantity}',
    'products': [{
      'id': '{$order_id}',
      'name': '{$product_name}',
      'quantity': '{$product_quantity}',
      'price': '{$product_price}',
    }]
  }
)
</script>

**Comment by Gummybearr** [comment]
@frafdsaf  안녕하세요 :) 우선 답변이 늦어 죄송합니다.

total_price와 total_quantity 자리에는 실제 구매금액, 개수를 담아야 합니다.
카페24에서 해당 변수를 어떻게 지정하고 있는지는 알 수 없기 때문에 카페 24측에 문의하여 금액이나 개수를 특정 변수로 받고 이를 담아야 할 것으로 보입니다.

이것이 어렵다면 `{'Purchase',{}}`와 유사한 형식으로 구매 이벤트만 넣어서 구매이벤트가 몇건이나 발생했는지 집계하는 것도 가능합니다.
