### ISSUE TITLE
[구매 전환] 전환 스크립트 문의드립니다.

### ISSUE THREAD

**Issue by runcat1** [daangn/karrot-conversion-tracker-tool-support#43]
호스팅사는 카페 24이며, 모듈리스트 확인하여 해당하는 명령어 스크립트 구성하였습니다.

다만, 추적이 되지않아 스크립트 확인 및 해결방안 전달해 주시면 감사하겠습니다. 

<script>
window.karrotPixel.track(
  'Purchase', 
  {
    'total_price': '{$total_product_price}',
    'total_quantity': '{$product_quantity}',
    'products': [{
      'id': '{$order_id}'
      'name': '{$product_name}',
      'qunatity': '{$product_quantity}',
      'price': '{$product_price}'
    }]
  }
)
</script>

**Comment by Gummybearr** [comment]
안녕하세요 :) 

광고주 아이디와 전환추적코드를 알려주실 수 있나요?

**Comment by runcat1** [comment]
> 안녕하세요 :)
> 
> 광고주 계정과 전환추적 코드를 찾을 수 있나요?

안녕하세요. 내용 전달드립니다.

태석광학_광고계정
2387502

전환 추적 코드 ID
1692322901359700001

**Comment by extJo** [comment]
구매금액이나 수량에 대해서 수집하지 않으신다면 아래와같이 삽입부탁드립니다
```
<script>window.karrotPixel.track('Purchase')</script>
```
