### ISSUE TITLE
[고도몰] 사이트 전환 스크립트 설치 문의드립니다.

### ISSUE THREAD

**Issue by hbm1218** [daangn/karrot-conversion-tracker-tool-support#44]
로그인, 회원가입, 상세페이지, 장바구니담기, 구매 이벤트 페이지에 스크립트를 설치할려고 합니다.
저희는 고도몰 호스팅을 사용하고 있습니다.

1. 로그인과 회원가입은 별도의 페이지도 없고 알림창이 없는데 어느부분에 설치해야되나요?
- php 코드(로그인 완료시 페이지)

$daangnScript = "

<script src="https://karrot-pixel.business.daangn.com/0.1/karrot-pixel.umd.js"></script> 
<script>
 window.karrotPixel.init('부여받은 번호'); 
window.karrotPixel.track('Login');
</script>
"

echo $daangnScript;

위와 같은 코드로 작성해도 되는지 문의드립니다.

2. 장바구니 담기 부분은 장바구니 버튼을 클릭시에 설치하면 되나요?
3. 고도몰 구매완료페이지인 경우 수량, 상품명이 명시되어 있지 않은데 어떻게 설치해야될까요?

<script>
window.karrotPixel.track(
  'Purchase', 
  {
    'total_price': '{구매금액}',
    'total_quantity': '{구매수량}',
    'products': [{
      'id': '{상품ID}',
      'name': '{상품명}',
      'quantity': '{상품수}',
      'price': '{상품가격}',
    }]
  }
)
</script>

별도로 고도몰 관련 된 설치 가이드가 있으면 전달 부탁드립니다.

**Comment by Gummybearr** [comment]
안녕하세요 :) 

1. 질문을 잘 이해하지 못했습니다. 로그인과 회원가입이 별도의 페이지가 없는데 어떻게 로그인 완료시 페이지에 코드를 심을 수 있나요?
2. 자바스크립트를 돌릴 수 있는 곳이라면 어디든 자유롭게 코드를 심을 수 있습니다. 
3. 호스팅사에 문의해야 할 것으로 보입니다. 현재 고도몰 설치 가이드가 있지는 않기 때문에 문의 응답에 제한이 있는 점 양해 부탁드립니다ㅠ
