### ISSUE TITLE
ncaught TypeError: Cannot read properties of undefined (reading 'pack') 오류가 나오는데 원인을 알고 싶습니다.

### ISSUE THREAD

**Issue by adogbowl** [daangn/karrot-conversion-tracker-tool-support#45]
Uncaught TypeError: Cannot read properties of undefined (reading 'pack')
    at f.karrotPixel.window.karrotPixel.e.track (karrot-pixel.umd.js:1:112694)
    at <anonymous>:1:67
    at gtm.js?id=GTM-KHHDM7T9&l=googleTagManager&gtm_debug=x&gtm_auth=-5JOo6z5dVUMYVuDG5JbUw&gtm_preview=env-10:465:414
    at HTMLScriptElement.<anonymous> (gtm.js?id=GTM-KHHDM7T9&l=googleTagManager&gtm_debug=x&gtm_auth=-5JOo6z5dVUMYVuDG5JbUw&gtm_preview=env-10:466:118)

설치중인 주소 입니다.
https://hxxaetvmcdz.pro.typeform.com/hpb-cente

광고주 아이디 입니다.
전환 추적 코드 ID
1700036519697300001

**Comment by extJo** [comment]
GTM으로 연동하신 경우에 대해 확인중에 있습니다. 확인 후 답변드리겠습니다!

**Comment by extJo** [comment]
https://github.com/daangn/karrot-conversion-tracker-tool-support/issues/47
