### ISSUE TITLE
[QUESTION] 완료페이지 스크립트 삽입하여 확인 중인데 수치가 반만 잡혀서 문의드립니다.

### ISSUE THREAD

**Issue by jung6427** [daangn/karrot-conversion-tracker-tool-support#46]
안녕하세요. 
문의드릴께 있어 질문남깁니다.

해당 페이지 헤드에 공통 스크립트가 삽입되어있습니다. 
그리고 해당 페이지에 DB를 남길 시 

위의 완료 페이지로 이동이 됩니다. 

이 페이지는 공통스크립트와 아래 스크립트가 들어가있습니다.

<script>
window.karrotPixel.track('CompleteRegistration');
</script>

수치를 체크할려고 하는데 
들어온 DB는 14개라고 치면 
당근마켓의 수치는 7회라고만 표시됩니다...
반만 표시가되는거죠 ㅠ

위와 같은 현상이 계속 있는데 

혹시 이유가 어떻게 되는지 궁금합니다.

별도 애널리틱스까지 삽입해서 테스트를 해봤지만
디버깅 테스트는 잘되는걸로 확인됩니다.

![image](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/102494450/0a03aba6-a0b2-4789-92b8-2a4ea9db3e4c)

**Comment by jung6427** [comment]
해당 내용 추가 보완하여 다시 올리겠습니다.

**Comment by extJo** [comment]
https://github.com/daangn/karrot-conversion-tracker-tool-support/issues/48
