### ISSUE TITLE
[QUESTION] 태그매니저에서 작동 시키는데 오류가 발생 합니다.

### ISSUE THREAD

**Issue by adogbowl** [daangn/karrot-conversion-tracker-tool-support#47]
Uncaught TypeError: Cannot read properties of undefined (reading 'pack')
at f.karrotPixel.window.karrotPixel.e.track (karrot-pixel.umd.js:1:112694)
at :1:67
at gtm.js?id=GTM-KHHDM7T9&l=googleTagManager&gtm_debug=x&gtm_auth=-5JOo6z5dVUMYVuDG5JbUw&gtm_preview=env-10:465:414
at HTMLScriptElement. (gtm.js?id=GTM-KHHDM7T9&l=googleTagManager&gtm_debug=x&gtm_auth=-5JOo6z5dVUMYVuDG5JbUw&gtm_preview=env-10:466:118)

설치중인 주소 입니다.
https://hxxaetvmcdz.pro.typeform.com/hpb-cente

광고주 아이디 입니다.
전환 추적 코드 ID
1700036519697300001

**Comment by extJo** [comment]
GTM으로 연동하신 경우에 대해 확인중에 있습니다. 확인 후 답변드리겠습니다!

**Comment by extJo** [comment]
@adogbowl 안녕하세요. 설치중인 주소에 확인이되지않습니다

**Comment by adogbowl** [comment]
> @adogbowl 안녕하세요. 설치중인 주소에 확인이되지않습니다

https://hxxaetvmcdz.pro.typeform.com/hpb-center

**Comment by extJo** [comment]
@adogbowl GTM 설정 첨부 부탁드립니다

**Comment by adogbowl** [comment]
> @adogbowl GTM 설정 첨부 부탁드립니다

![스크린샷 2023-11-23 오후 5 33 18](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/45092579/d4b8d3bd-da55-47a8-b6ee-3bbf39991e70)


이게 끝입니다.

**Comment by extJo** [comment]
사용 브라우저 및 버전 정보 포함해서 전달 부탁드립니다. 제가 타입폼 들어갔을때는 문제없이 태그매니저가 잘 동작했습니다.

**Comment by extJo** [comment]
이슈는 확인했고, 스크립트 문제로 파악되서 수정 후 안내드리겠습니다~!
감사합니다 :)

**Comment by adogbowl** [comment]
> 이슈는 확인했고, 스크립트 문제로 파악되서 수정 후 안내드리겠습니다~! 감사합니다 :)

네 알겠습니다.

**Comment by extJo** [comment]
@adogbowl 안녕하세요
0.3버전을 이용해서 스크립트 설치 부탁드립니다.
```
<script src="https://karrot-pixel.business.daangn.com/0.3/karrot-pixel.umd.js"></script>
```
