### ISSUE TITLE
당근마켓 전환추적관리 오류 문의의 건

### ISSUE THREAD

**Issue by zoeyjo0** [daangn/karrot-conversion-tracker-tool-support#49]
**Describe the question**
당근마켓 점신_퍼포먼스 계정
ID: 2557498

전환추적관리를 진행하는 과정에서 방문과 회원가입은 진행했는데,
잠재고객 수집(LEAD)를 설치하는 과정에서 오류가 발생되서 문의드립니다.

확인 요청드립니다.

![image](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/35644522/a67b2959-ad99-4777-94cd-66c29c99bb8c)

​

**Comment by extJo** [comment]
안녕하세요. 어떤환경에서 스크립트를 설치하고 계신지 알아야합니다.
스크립트를 직접 삽입하지 않으시고 GTM을 이용해서 설치중이신가요?

**Comment by extJo** [comment]
답변 참고 부탁드립니다
https://github.com/daangn/karrot-conversion-tracker-tool-support/issues/47#issuecomment-1833205845

**Comment by zoeyjo0** [comment]
직접 설치하고 있습니다!
문자로 </script> 닫는것으로 넣으라고 답변주셨는데
닫아서 넣었을 때 동일한 오류 발생합니다.

**Comment by extJo** [comment]
@zoeyjo0 태그와 상관없이 버전이 변경되었습니다.

**Comment by extJo** [comment]
그리고 해당 오류가 발생하는 url 부탁드리겠습니다
