### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by myzon2** [daangn/karrot-conversion-tracker-tool-support#5]
Desktop : WINDOW 10
브라우져 : 크롬
자체 개발한 쇼핑몰입니다.
https://www.duolac.co.kr/

[ 질문 ]
아래 가이드 URL의 "3. 이벤트 스크립트 설치하기 " 에서 Login 이벤트를 설치 중인데요,
( https://bizschool.daangn.com/43922c93-2958-42c3-811f-3546d17e80e1 )

로그인 성공 시, window.karrotPixel.track('Login'); 를 넣었는데 다음과 같은 에러가 납니다.
login.do:2188 Uncaught TypeError: Cannot read properties of undefined (reading 'track')
at Object.success (login.do:2188:25)
at i (jquery.js:2:27983)
at Object.fireWith [as resolveWith] (jquery.js:2:28749)
at A (jquery.js:4:14203)
at XMLHttpRequest. (jquery.js:4:16491)

track에 문제가있는것 같은데, 왜 이런 에러가 날까요?

물론, 아래의 공통 스크립트는 head 사이에 위치해있습니다.

<script src="https://karrot-pixel.business.daangn.com/0.0.3/karrot-pixel.umd.js"></script> <script> window.karrotPixel.init('1689035235009700001'); window.karrotPixel.track('ViewPage'); </script>

**Comment by extJo** [comment]
혹시 login 이벤트를 넣은 코드를 확인 할 수 있을까요?

**Comment by extJo** [comment]
로그인 성공시에 호출하는 경우에 헤더에 해당하는 공통 스크립트가 빠져있지 않은지 확인 부탁드립니다

**Comment by myzon2** [comment]
헤드 사이에 공통스트립트가 아래와 같이 추가 되어있습니다.   ( https://www.duolac.co.kr/login.do  에 ”소스보기” 하시면 공통스크립트가 포함되어 있습니다. ) 




<script src=https://karrot-pixel.business.daangn.com/0.0.3/karrot-pixel.umd.js></script>

<script>

  window.karrotPixel.init('1689035235009700001');

  window.karrotPixel.track('ViewPage');

</script>



 

 

 

로그인 성공 후, 호출하는 로그인 이벤트 코드 


$.ajax({

            type : 'post',

            url : '/loginProcess.do',

            data : { "param" : param } ,

            dataType : 'json',

            error       : Cmmn.onErrorProc,

            success : function(data)

            {   

                if(data.result=="success") {

                           //START :  WIDERPLANET - 로그인 

                           var wp_hcuidTxt = "";

                           if( data.mbrNo != "" )

                           {      wp_hcuidTxt = md5( data.mbrNo  );     } 

 

                            WIDERPLANET_script( wp_hcuidTxt ); 

                           // END  :  WIDERPLANET - 로그인 

 

 

                           // Danggeun Market Code 당근 

                       window.karrotPixel.track('Login'); 

                       // End Danggeun Market Code 당근

**Comment by extJo** [comment]
jquery의 ajax success 에 등록된 함수안에서는 전역으로 설젱된 window 객체를 제대로 참조하기가 어렵습니다.
회피하는 방법을 찾으시거나, 다른방법으로 구현하셔야할거같습니다. 

실마리가 될만한 부분을 참조하실 수 있도록 첨부해드리겠습니다.
https://groups.google.com/g/prototype-scriptaculous/c/IsV_nYGkdrY

**Comment by myzon2** [comment]
아래 코드 중 파란 부분이 기존에 사용된 ( WIDERPLANET  : 당근 스크립트와 비슷한 기능을 하는 코드 ) 코드인데요.

이 코드는 잘 작동합니다.    ( 물론 WIDERPLANET도 전역으로 선언 되어있구요 )

 

그런데 당근 스크립트만 안됩니다. ( 빨간색 부분 )

Success 부분 말고는 로그인 성공 후에 당근 스크립트를 넣을 부분이 없습니다.

 


$.ajax({

            type : 'post',

            url : '/loginProcess.do',

            data : { "param" : param } ,

            dataType : 'json',

            error       : Cmmn.onErrorProc,

            success : function(data)

            {   

                if(data.result=="success") {

 

 

                           //START :  WIDERPLANET - 로그인 

                           var wp_hcuidTxt = "";

                           if( data.mbrNo != "" )

                           {      wp_hcuidTxt = md5( data.mbrNo  );     }  

                            WIDERPLANET_script( wp_hcuidTxt ); 

                           // END  :  WIDERPLANET - 로그인 

 

 

                          // Danggeun Market Code 당근 

                          window.karrotPixel.track('Login'); 

                          // End Danggeun Market Code 당근  

 

 

                    

                       if($("#id_reg").is(":checked")){ // ID 저장하기를 체크한 상태라면,

                        setCookie("duolacLoginId", $("#loginId").val(), 7); // 7일 동안 쿠키 보관

                    }

                    

                    window.location.href=loginE.returnUrl;

                } else if(data.result=="fail") {

                    alert(data.message);

 

                    if(data.resultCode == 'E999'){

                                        window.location.href="/loginDorm.do";

                    }

                }

            }

        });

**Comment by IsaacYouKorea** [comment]
안녕하세요. 당근마켓 광고실 프론트엔드 개발자 Isaac이예요.

_Uncaught TypeError: Cannot read properties of undefined (reading 'track')_

이렇게 에러가 발생한다고 해주셨는데,
이 에러가 발생하는 라인에서 window랑 window.karrotPixel이 호출되는지 콘솔로 확인해주실 수 있을까요?

**Comment by myzon2** [comment]
Ajax 의 success 부분에 아래와 같이 로그를 찍었습니다.

console.log( window );

console.log( window.karrotPixel );

 

window.karrotPixel 에서 undefined 가 찍힙니다.

 

[ 콘솔 결과 ]

**Comment by IsaacYouKorea** [comment]
$.ajax 콜을 하기 이전까지는 window.karrotPixel이 호출되는데
success 안에서만 안되는거죠?

우회하는 방법으로는 WIDERPLANET_script와 동일하게 전역 함수를 정의를 해놓고
그걸 호출하는 방법도 있을거 같아요.

**Comment by myzon2** [comment]
가이드 주신대로 아래와 같이 했는데 안됩니다.

 

[ 전역 함수 ]  WIDERPLANET_script와 마찬가지로 아래와 같이 함수를 만듦.


function Danggeun_script(  ) 

{

       window.karrotPixel.track('Login'); 

}

 

 

Danggeun_script 함수를 success 안에 넣음. 


$.ajax({

            type : 'post',

            url : '/loginProcess.do',

            data : { "param" : param } ,

            dataType : 'json',

            error       : Cmmn.onErrorProc,

            success : function(data)

            {   

                if(data.result=="success") {

 

                           //START :  WIDERPLANET - 로그인 

                           var wp_hcuidTxt = "";

                           if( data.mbrNo != "" )

                           {      wp_hcuidTxt = md5( data.mbrNo  );     }  

                            WIDERPLANET_script( wp_hcuidTxt ); 

                           // END  :  WIDERPLANET - 로그인 

 

                          console.log( window );

                         console.log( window.karrotPixel );

                           

                                 

                          // Danggeun Market Code 당근  

                          Danggeun_script(); 

                          // End Danggeun Market Code 당근

**Comment by IsaacYouKorea** [comment]
@myzon2 
로그인 부분을 다음 같이 코드 스니펫을 만들어서 돌려봤을때는 픽셀 동작이 되는데
여기서부터 디버깅 해볼 수 있을까요?


```
// loginE.login
var loginId = document.getElementById('loginId');
var loginPw = document.getElementById('loginPw');
var param = JSON.stringify(loginE.objectifyForm($(document.getElementById('loginFrm')).serializeArray()));

$.ajax({
    type: 'post',
    url: '/loginProcess.do',
    data: {
        "param": param
    },
    dataType: 'json',
    error: Cmmn.onErrorProc,
    success: function(data) {
        if (data.result == "success") {
            console.log(window.karrotPixel);
            window.karrotPixel.track('Login');
            // window.location.href = loginE.returnUrl;
        }
    }
});


```

**Comment by myzon2** [comment]
네 아래와 같이 undefined 가 나옵니다.

**Comment by IsaacYouKorea** [comment]
@myzon2 
콘솔에 KarrotPixel 관련 아무런 에러도 안뜨나요?
localhost에서 작업중이시면 Domain 에러가 보일 수도 있을거 같은데요

**Comment by myzon2** [comment]
넵 아무런 에러 안뜨고 undefined 만 뜹니다.

**Comment by IsaacYouKorea** [comment]
@myzon2 
window.karrotPixel을 참조할 수 있는 부분은 어디까지 인가요?

**Comment by myzon2** [comment]
[ 그림 1] 과 같이 공통코드가 설치 되어있는데요.

https://www.duolac.co.kr/login.do 에서는 스크립트 에러가 안나는데,

 

http://localhost:8090/login.do 에서는 아래와 같이  에러가 납니다.



 

위 에러 중 두번째 에러의 링크를 누르면 다음과 같습니다. 



 

 

[ 그림 1 ]  - 공통코드




<script src=https://karrot-pixel.business.daangn.com/0.0.3/karrot-pixel.umd.js></script>

<script>

  window.karrotPixel.init('1689035235009700001');

  window.karrotPixel.track('ViewPage'); 

</script>

**Comment by IsaacYouKorea** [comment]
https://www.duolac.co.kr/login.do에서는 ajax 호출 후 정상적으로 pixel이 동작되는걸까요?

**Comment by myzon2** [comment]
운영의 Success 안에  window.karrotPixel.track('Login'); 를 넣으면 에러가 안 납니다.

 

개발에서만 공통스크립트 부터 에러가 나는 것 같습니다.

**Comment by IsaacYouKorea** [comment]
불편을 드려 죄송합니다.

쿠키 관련 기능때문에 도메인이 없을 경우에는 에러를 뱉어주도록 처리하고 있는데,
개발 환경상 확인이 어려우신 게 아닐까 생각이 되요.
저희도 이 부분 고려해서 pixel 업데이트 하도록 할께요.
감사합니다 🙇

**Comment by myzon2** [comment]
혹시 언제즈음 해결이 될까요?

**Comment by IsaacYouKorea** [comment]
@myzon2 
0.1 버전으로 시도해보시겠어요?

```
<!-- Danggeun Market Code -->
<script src="https://karrot-pixel.business.daangn.com/0.1/karrot-pixel.umd.js"></script>
<!-- End Danggeun Market Code -->
```

**Comment by myzon2** [comment]
넵  0.1로 바꾸어 하니 됩니다.

 

이제부터 작업을 0.1로  진행하면 될까요?

 

<script src="https://karrot-pixel.business.daangn.com/0.1/karrot-pixel.umd.js"></script>

**Comment by myzon2** [comment]
안녕하세요. 스크립트 설치 진행중인데.

아래 캡춰 한 스크립트 두개가 뭘 의미하는지 모르겠어서요.

이 두개가 뭘의미하는건지요?

**Comment by IsaacYouKorea** [comment]
@myzon2
캡처 이미지가 보이지 않아요.

**Comment by myzon2** [comment]
![image](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/139190829/7d95c469-1734-4db0-9834-5dff79f70aac)

**Comment by myzon2** [comment]
깃허브에 이미지 올려두었습니다.

**Comment by IsaacYouKorea** [comment]
각 이벤트는 서비스 특성과 목표에 맞춰 선택적으로 활용하시면 돼요.
문의주신 이벤트 또한 잠재고객 수집 또는 서비스 신청 이벤트에 대한 추적이 필요한 광고주에 제공되는 이벤트 타입이예요.
제공하는 모든 이벤트를 사용할 필요는 없으며, 각자 서비스 상황에 필요한 이벤트를 골라서 삽입하여 활용하시면 될 것 같습니다.

**Comment by myzon2** [comment]
넵 감사합니다.

**Comment by IsaacYouKorea** [comment]
네, 좋은 피드백 주셔서 감사해요~ 
해당 스레드는 닫도록 할께요
