### ISSUE TITLE
[QUESTION] 상품 별 전환 스크립스 삽입 문의

### ISSUE THREAD

**Issue by gusdk905** [daangn/karrot-conversion-tracker-tool-support#50]
**Describe the question**
A clear and concise description

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

안녕하세요.
어도비 사이트 내 당근마켓 전환 스크립트를 설치하려고 하는데요. 
어도비 사이트의 경우 한 도메인 내 여러 상품 (포토샵, 일러스트, 프리미어프로 등) 페이지가 있습니다. 

저희는 어도비 상품 별로 스크립트를 삽입해 상품 별 전환 체크를 하고 싶은데요. 
하여 하기 3가지 체크 부탁드립니다. 

1) 어도비 상품 별(Photoshop, Acrobat…) 스크립트 삽입 가능여부 / 가능 시 가이드 함께 첨부
2) 어도비 상품 별 스크립트 삽입 시 충돌 발생 가능성 여부
3) 충돌 가능성 있을 시 우회 또는 개선 방안 있는지 여부

확인해주시면 감사드리겠습니다.

**Comment by extJo** [comment]
@gusdk905 안녕하세요.
어도비 상품별로 따로 전환추적 집계를 하고싶은 이유가 있을까요? 수집한 모수군에 대해서 따로 타겟생성해서 제품군마다 캠페인 집행하기 위해서일까요?

> 어도비 상품 별(Photoshop, Acrobat…) 스크립트 삽입 가능여부 / 가능 시 가이드 함께 첨부

만약 따로 집계하고싶으시다면 상품갯수만큼 전환추적코드를 생성하시고 <head> 태그 안에 상품 별 진입점 및 라우팅되는 하위 URL까지 전파 가능하도록 따로 삽입하셔야 합니다.

> 어도비 상품 별 스크립트 삽입 시 충돌 발생 가능성 여부

<head> 안에서 여러 전환추적코드를 동시에 호출하지 않는다면 이벤트 수집에는 문제없습니다

> 충돌 가능성 있을 시 우회 또는 개선 방안 있는지 여부

위 답변으로 갈음합니다

감사합니다

**Comment by gusdk905** [comment]
확인 감사합니다.

제가 이해한 바가 맞는지 체크 부탁드립니다. 

결국 메인 페이지에 [공통 스크립트] 삽입, 
각 상품 갯수만큼 [이벤트 (구매) 스크립트] 를 설치하는게 맞는걸까요 ?

2번 충돌의 경우 조금 더 상세하게 설명해주시면 감사드리겠습니다. 
전환추적 코드를 가지고 스크립트를 호출하지 않는다는 말에 대해 이해가 어렵네요 ㅠ ㅠ

**Comment by extJo** [comment]
@gusdk905 

https://www.adobe.com/kr/
은 제외한 상품별 메인페이지별로 전환추적코드를 발급받으시고 각 전환추적코드별로 스크립트를 삽입해주시면 됩니다
- https://www.adobe.com/kr/products/photoshop.html
- https://www.adobe.com/kr/products/illustrator.html
- 등등

구매 스크립트는 어디에 설치하실 예정인가요? 구매 컴포넌트가 공통이라면 따로 수집하기에는 어려움이 있습니다
