### ISSUE TITLE
[구매전환] 전환 스크립트 문의 드립니다.

### ISSUE THREAD

**Issue by chulhwans** [daangn/karrot-conversion-tracker-tool-support#51]
호스팅사는 카페 24이고, 당근에서 진행 하라고 말씀 주신 부분에 대하여 진행을 했으나, 다른 이벤트들은 추적이 가능한데
구매 전환 이벤트만 수집이 되고 있지 않아 문의드립니다.

현재 카페24 스마트 디자인 쪽에서 주문완료 페이지에

<script>
window.karrotPixel.track(
  ('Purchase', {})
</script>

해당 코드값 넣어두어서 추적이 되지 않아서

<script>
window.karrotPixel.track(
  'Purchase', 
  {
    'total_price': '{구매금액}',
    'total_quantity': '{구매수량}',
    'products': [{
      'id': '{상품ID}',
      'name': '{상품명}',
      'quantity': '{상품수}',
      'price': '{상품가격}',
    }]
  }
)
</script>

해당 코드값도 넣어보았지만 추적이 되지 않았습니다.

광고 계정 ID
2037661

전환 추적코드 ID
1697522024598400001

입니다.

**Comment by seongjunhwang** [comment]
안녕하세요.
당근마켓 황성준입니다.

주문 완료 페이지에 구매 이벤트만 수집을 원하시는 경우 스크립트를 아래와 같이 삽입 부탁드리겠습니다.

```
<!-- Danggeun Market Code -->
<script>
window.karrotPixel.track('Purchase');
</script>
<!-- End Danggeun Market Code -->
```

**Comment by chulhwans** [comment]
구매 이벤트 수집 원하는데 구매 금액 구매 수량 등을 알고싶으면 어떻게 진행해야하나요 ?

**Comment by extJo** [comment]
카페 24내에 API를 참고하셔서 작성부탁드립니다.
저희가 따로 코드로 제공하지 못하는점 양해부탁드립니다.
