### ISSUE TITLE
[BUG] 사이트에 전환 추적 스크립트를 설치 하였는데 구매 이벤트가 발생하지 않고 있습니다.

### ISSUE THREAD

**Issue by mevit0504** [daangn/karrot-conversion-tracker-tool-support#53]
카페24 솔루션사를 이용중이며, 변수의 경우 모듈리스트에 맞춰서 잘 설정 하였습니다.
단순히 구매 건수를 확인 하기 위함이 아니라 금액과 수량 등을 알기 위해서 스크립트를 수정하여 넣었는데 이벤트로 넘어가지지 않습니다. 다른 view content나 add to cart는 잘 트래킹이 되지만 purchase만 오류가 발생하고 있습니다. purchase 단독으로 넣었을 땐 문제 없이 잘 트래킹 되지만 변수값을 넣었을때는 계속 읽지를 못하네요. 확인 부탁드립니다. 

<script type="text/javascript">
window.karrotPixel.track(
  'Purchase', 
  {
    'total_price': '{$total_order_price}',
    'total_quantity': '{$product_quantity}',
    'products': [{
      'id': '{$order_id}',
      'name': '{$product_name}',
      'quantity': '{$qty}',
      'price': '{$total_product_price}',
    }]
  }
)
</script>

**Comment by extJo** [comment]
해당내용 참고부탁드립니다

https://github.com/daangn/karrot-conversion-tracker-tool-support/issues/51
