### ISSUE TITLE
[QUESTION] CTA 버튼 스크립트 삽입 가능 여부 

### ISSUE THREAD

**Issue by gusdk905** [daangn/karrot-conversion-tracker-tool-support#54]
**Describe the question**
A clear and concise description

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

어도비 사이트 내 스크립트 외 버튼(CTA) 스크립트 삽입이 가능할지 문의 드립니다.

전환 스크립트의 경우 '구매 완료' 단의 페이지를 트래킹하여 전환 건수로 체킹할 예정인데요
그 이전 단계인 회원가입, 구매시작 버튼 등의 효율을 체크하기 위해 [버튼 스크립트]가 필요한거라고 이해해주시면 될 것 같습니다

해당 내용 내부적으로 체크 부탁 드리며, 버튼 스크립트 삽입이 가능할 경우 스크립트 세부 내용도 전달 부탁 드립니다.

예시는 첨부파일로 확인 부탁드립니다. 
![1](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/26589891/36d63967-d7dd-4486-8d0f-ce7ff3f3cd90)

**Comment by extJo** [comment]
@gusdk905 
안녕하세요. 말씀하시는 부분이 버튼의 action이 일어날 때 스크립트가 동작 가능한지 질문주신걸까요?

**Comment by gusdk905** [comment]
네 맞습니다!

**Comment by extJo** [comment]
@gusdk905 가이드대로 스크립트를 설치하셧다면 global window에 karrotPixel이 존재하는 형태여서
```
<script>
function buttonClick() {
  ...
  window.karrotPixel.track(...)
}
</script>

<button onClick=buttonClick() ... />
```
형태로 작성해주시면 됩니다.
