### ISSUE TITLE
[QUESTION] 이벤트 스크립트를 심는 방법을 알 수 있을까요? 

### ISSUE THREAD

**Issue by Eameslol** [daangn/karrot-conversion-tracker-tool-support#55]
방문 이벤트는 적용이 되는 상태인데, 나머지 이벤트 스크립트는 테스트해보니 수집이 되지 않고 있습니다. 
구매, 장바구니 담기, 상세페이지 조회, 회원가입, 로그인, 잠재고객 수집 이벤트를 수집할 수 있는 방법 궁금합니다.

**Comment by extJo** [comment]
[가이드 참고](https://bizschool.daangn.com/43922c93-2958-42c3-811f-3546d17e80e1#:~:text=%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8%20%EC%BD%94%EB%93%9C%EB%A5%BC%20%ED%99%95%EC%9D%B8%ED%95%B4%EB%B3%B4%EC%84%B8%EC%9A%94.-,%EC%9D%B4%EB%B2%A4%ED%8A%B8%20%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8,%EC%84%A4%EB%AA%85,-%EB%A1%9C%EA%B7%B8%EC%9D%B8%20%EC%9D%B4%EB%B2%A4%ED%8A%B8%20%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8)하셔서 설치하셨을까요?
