### ISSUE TITLE
[QUESTION] 당근 전환지표 관련 문의드립니다.

### ISSUE THREAD

**Issue by ccejjj** [daangn/karrot-conversion-tracker-tool-support#57]
안녕하세요.
당근 전환지표 관련하여 문의드립니다.

광고계정 : 2402950
전환추적ID : 1697598421111800001

광고계정 : 2402879
전환추적ID : 1698721313107400001

위 두 계정 현재 전환 추적 관리 탭에서 이벤트 모수는 정상적으로 수집되고 있습니다.
그런데 운영중인 캠페인에 전환 추적 코드를 적용하였는데도 대시보드 및 보고서 상에 전환 지표가 전혀 잡히고있지 않아 문의드립니다.
약 두달 전부터 문제가 해결되고 있지 않아서 빠른답변 부탁드리겠습니다ㅠ

감사합니다.

**Comment by extJo** [comment]
@ccejjj 안녕하세요. 소재 렌딩페이지 URL이 데스크톱용으로 확인됩니다. 
웹사이트 전환추적을 위해서 리다이렉션 링크는 제한하고 있습니다.
모바일용 URL을 넣으시면 해결될것으로 보입니다

**Comment by ccejjj** [comment]
빠른 답변 감사합니다! 
말씀주신대로 설정해서 구매수, 장바구니 담기수는 잡히는데 구매금액이 잡히질않네요ㅠ

<script src="https://karrot-pixel.business.daangn.com/0.1/karrot-pixel.umd.js"></script>
<script>
  window.karrotPixel.init('1697598421111800001');
  window.karrotPixel.track('Purchase');
</script> 

이렇게 넣으면 전환추적은 잡히는데 

<script src="https://karrot-pixel.business.daangn.com/0.1/karrot-pixel.umd.js"></script>
<script>
  window.karrotPixel.init('1697598421111800001');
  window.karrotPixel.track(
  'Purchase', 
  {
    'total_price': '{$total_order_price}',
    'products': [{
      'price': '{$product_total_price}',
    }]
  }
)
</script> 

이렇게 넣으면 전환추적도 잡히지않습니다ㅠ
왜그런지 알수있을까요?ㅠㅠ

**Comment by extJo** [comment]
안녕하세요. [가이드문서](https://bizschool.daangn.com/87729a84-5029-4a17-9531-d0f299e5f1f0)를 참고하셔서 스크립트 작성 부탁드립니다.

<img width="1067" alt="image" src="https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/22790901/802d2a74-5ec4-4384-ac5a-b40005401bc7">
