### ISSUE TITLE
당근마켓 전환 스크립트 문의 관련[QUESTION]

### ISSUE THREAD

**Issue by 23432rtea1134s** [daangn/karrot-conversion-tracker-tool-support#58]
안녕하세요.

<script src="https://karrot-pixel.business.daangn.com/0.1/karrot-pixel.umd.js"></script>
<script>
  window.karrotPixel.init('1701920344634200001');
  window.karrotPixel.track('SubmitApplication');
</script>

이렇게 전환 스크립트를 생성하여 홈페이지에 삽입하려고 하는데요.
이럴경우에 방문스크립트를 따로 설치해야하는지 위에 스크립트를 넣으면 방문 및 상담신청 둘다 잡히는지 확인 부탁드립니다.

**Comment by extJo** [comment]
방문 스크립트는 모든 페이지 헤더에 동일하게 적용해주시면 됩니다
```
<head>
<script src="https://karrot-pixel.business.daangn.com/0.1/karrot-pixel.umd.js"></script>
<script>
window.karrotPixel.init('1701920344634200001'); 
window.karrotPixel.track('ViewPage'); 
</script>
</head>
```

그 후 필요하신곳에 원하는 이벤트만 심으시면 됩니다
```
<script>
window.karrotPixel.track('SubmitApplication'); 
</script>
```

자세한 가이드는 [가이드 노션](https://bizschool.daangn.com/43922c93-2958-42c3-811f-3546d17e80e1) 참고하셔서 작성부탁드립니다
