### ISSUE TITLE
[QUESTION] 카페24 구매 완료 변수값 관련_ 구매수량, 상품ID 문의

### ISSUE THREAD

**Issue by ADXENO** [daangn/karrot-conversion-tracker-tool-support#59]
카페24 호스팅 사용 중이며,
구매 완료 스크립트 관련해서 문의 드립니다.

<script>
window.karrotPixel.track(
  'Purchase', 
  {
    'total_price': '{$total_order_price}',
    'total_quantity': '{구매수량}',
    'products': [{
      'id': '{상품ID}',
      'name': '{$product_name}',
      'quantity': '{$product_quantity}',
      'price': '{$product_price}',
    }]
  }
)
</script>
 

여기 까지 작업 완료한 상태인데,
구매수량/ 상품ID 변수값이 어떤걸 말하는지 모르겠습니다.

https://sdsupport.cafe24.com/product/detail.html?product_no=6139&cate_no=67&display_group=1#none

답변 가능할까요?

**Comment by extJo** [comment]
안녕하세요. 카페 24내 API 를 참고하셔서 작성하시면 됩니다. 
저희가 따로 가이드 드리지 못하는점 양해부탁드립니다.

https://github.com/daangn/karrot-conversion-tracker-tool-support/issues/51#issuecomment-1833036562
