### ISSUE TITLE
[QUESTION] 카페24 관련 질문

### ISSUE THREAD

**Issue by jae1cho** [daangn/karrot-conversion-tracker-tool-support#62]
당근 q&a
1.purchase 던질 때 파라미터 같이 던지라고 알려주셨는데, 이때 파라미터 변수는 임의로 세팅해서 보내도 상관 없냐
( 구매금액만 세팅해서 보내고 싶다  'total_price': '{$total_order_price}', 양식으로 보내도 상관 없냐) 

2. 1처럼 보냈을 때 구매수량 +1 이 되는게 맞냐 ( purchase만 보냈을 땐 1이 올라가고 있다, 파라미터 변수만 정확하게 보내면 마찬가지로 1이 올라가냐)

**Comment by extJo** [comment]
1. 원하시는 값으로 설정하셔서 보내시면 됩니다. 카페24 API를 참고하셔서 보내시면 됩니다.
2. 1을 안하셔도 구매수는 구매 스크립트 설치하신 부분이 실행될때마다 +1 됩니다. 구매 스크립트를 가이드에 맞게 설정하셧다면, 구매 마다 +1 될것입니다.

**Comment by jae1cho** [comment]
그러면


<script>
window.karrotPixel.track('Purchase');
</script>



<script>
window.karrotPixel.track(
  'Purchase', 
  {
    'total_price': '{카페24API에서 제공하는 파라미터}',
  }
)
</script>


이런식으로 2개를 해야 구매수와 구매금액을 알수있는건가요?

**Comment by extJo** [comment]
```
<script>
  window.karrotPixel.track( 'Purchase', { 'total_price': `{카페24API에서 제공하는 파라미터}`, } )
</script>
```
로 작성하시면 됩니다

**Comment by jae1cho** [comment]
1. 구매 스크립트 코드 에러 관련 질문 
1) 구매 스크립트 예시대로 그대로 세팅한 후 진행 
<!— Danggeun Market Code —>
<script>
window.karrotPixel.track(
  'Purchase', 
  {
    'total_price': '{$total_order_price}',
    'total_quantity': '{$total_order_price}',
    'products': [{
      'id': '{$total_order_price}',
      'name': '{$total_order_price}',
      'quantity': '{$total_order_price}',
      'price': '{$total_order_price}',
    }]
  }
)
</script>
<!— End Danggeun Market Code —>

2) object에 마지막 쉼표 뻬고 세팅한 후 진행

<script>
window.karrotPixel.track(
  'Purchase', 
  {
    'total_price': '{$total_order_price}',
    'total_quantity': '{$total_order_price}',
    'products': [{
      'id': '{$total_order_price}',
      'name': '{$total_order_price}',
      'quantity': '{$total_order_price}',
      'price': '{$total_order_price}'
    }]
  }
)
</script>
<!— End Danggeun Market Code —>

1, 2 두 케이스 다 다음 로직이 타지지 않습니다. 확인 부탁드립니다. 
purchase 이외의 파라미터를 추가로 보낼 때 위와 같이 코드를 작성하여 보냈는데 이후 로직을 타지 않습니다. 
참고로 파라미터는 테스트를 위해서 임의로 같은 값을 세팅했습니다.

2. 파라미터 세팅 관련 질문
- 1번이 해결된다면 구매금액 파라미터 값만 필요합니다. 아래와 같이 세팅해서 보내면 될까요? 
window.karrotPixel.track( ‘Purchase’, { ‘total_price’ : ‘{$price 관련 param}’})

**Comment by extJo** [comment]
1번에 작성하신 코드는, 가이드에 있는 단순 예시용이므로 API를 참고하셔서 작성하셔야합니다.
그대로 사용하실 수 없는 코드입니다.

2번은 스크립트를 작성하신 코드를 그대로 붙여주시면 확인해보겠습니다

**Comment by jae1cho** [comment]
<script>
window.karrotPixel.track(
  'Purchase', 
  {
    'total_price': '{$total_order_price}',
  }
)
</script>
<!— End Danggeun Market Code —>

![스크린샷 2024-01-08 오후 2 43 32](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/155703012/9da474be-ddab-4a54-8d50-292a6ead5ff5)

**Comment by extJo** [comment]
참고하신 API 문서가 [이 문서](https://sdsupport.cafe24.com/product/detail.html?product_no=6139&cate_no=67&display_group=1)일까요?

**Comment by jae1cho** [comment]
네 맞습니다

**Comment by extJo** [comment]
이 문서만으로는 구매금액을 연동하기 어려울것 같습니다. 
CAFE24측에 문의해서 픽셀 스크립트에 사용할 수 있는 API 문서를 받으셔야할거같습니다.

**Comment by jae1cho** [comment]
https://developers.cafe24.com/docs/api/#method 

이 문서로 확인이 가능할까요?

**Comment by extJo** [comment]
이 문서는 Cafe24측과 제휴된 서드파티 앱 만들때 사용하는것으로 보이는데, 당근의 경우 아직 Cafe24랑 제휴가 되어있지 않아서 저 문서를 통해서 수집을 하기에는 어려워보입니다. Cafe24 측에 스마트디자인을 통해서 주문완료시에 구매금액 값을 스크립트에 실행 할 수 있도록 방법을 문의해야 할것 같습니다.
