### ISSUE TITLE
당근 전환추적 코드 고도몰에서는 치환을 어떻게 하나요? 

### ISSUE THREAD

**Issue by sreotiugad** [daangn/karrot-conversion-tracker-tool-support#63]
<script>
window.karrotPixel.track(
  'Purchase', 
  {
    'total_price': '{구매금액}',
    'total_quantity': '{구매수량}',
    'products': [{
      'id': '{상품ID}',
      'name': '{상품명}',
      'quantity': '{상품수}',
      'price': '{상품가격}',
    }]
  }
)
</script>

여기서 {} 사이에 들어가는 내용은 고도멀에서 어떻게 찾나요?? 
답변 부탁드립니다.

**Comment by extJo** [comment]
고도몰측에 픽셀 스크립트에 이용 할 수 있는 API를 전달받으셔서 치환하셔야 할 것 같습니다.
