### ISSUE TITLE
[QUESTION] 오늘플러스 회원가입 이벤트 추적 문의_240223

### ISSUE THREAD

**Issue by hyungwoo219** [daangn/karrot-conversion-tracker-tool-support#64]
**Describe the question**
A clear and concise description

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

오늘플러스 계정 총 2개의 스크립트 설치하였는데요. 
1개는 랜딩이 이루어지는 오늘플러스 사이트, 다른 1개는 회원가입이 이루어지는 사이트입니다.
회원가입이 이루어지는 사이트에 회원가입 이벤트 추적을 위해서 스크립트 작업을 하였는데요. 
현재 방문자 이벤트는 정상 수집되고 있으나, 회원가입 이벤트 확인이 안되고 있습니다.
현재 스크립트 작업에 이슈가 있는지 체크해주실 수 있을지 문의드립니다.

[광고주 오늘플러스]
yksso
전환 추적 코드 ID1707960231485500001
연동 웹사이트 URL https://www.yksso.co.kr
ㄴ 회원가입 이벤트 미수집

**Comment by extJo** [comment]
@hyungwoo219 안녕하세요! 공유주신 내용 확인차 질문 드려요

-----
1
회원가입 이벤트를 추적하고싶으신게 맞을까요? 회원가입이 일어나는 `https://www.yksso.co.kr/` 도메인을 기준으로 만드신 도구 yksso는 회원가입이 잡히는걸로 보입니다

-----
2
> 말씀 주신 https://m.ykbrand.co.kr/ 관련 문의드립니다.
이 부분에서는 어떤걸 확인하고싶으신걸까요?

**Comment by hyungwoo219** [comment]
안녕하세요! 내용 확인 주셔서 감사합니다!

말씀 주신 것과 같이 https://www.yksso.co.kr/ 도메인 기준으로 회원가입 이벤트 설치한 것인데요.

일전에 답변 주셨을때 회원가입시 https://m.ykbrand.co.kr/ 으로 시작하는 도메인으로 이동하는 것으로 보인다고 말씀 주셔서요!
혹시 확인 주셨던 https://m.ykbrand.co.kr/도메인을 어디서 확인 주셨는지 문의드린 내용입니다. 설치한 스크립트와 해당 도메인과 연관성이 있으면 따로 스크립트 작업이 필요할 것 같아 문의드린 것입니다.

일전에 답변 주신 내용 하기 첨부드립니다.

==================================================================================

[당근]안녕하세요?

회원가입 스크립트를 설치한 웹사이트가 "https://www.yksso.co.kr/" 맞을까요?
확인해보았을 때, 해당 url은 통합회원 안내 페이지이고
회원가입 시 "https://m.ykbrand.co.kr/" 으로 시작하는 도메인으로 이동하는 것으로 보여요.

자주 묻는 질문의 [전환 추적 코드를 세팅하였는데 전환 추적 코드의 이벤트가 확인되지 않아요.]
https://www.daangn.com/wv/faqs/10132 내용을 확인해보세요.

만약 모바일 url이 별도로 있는 경우, 해당 도메인까지 등록해주셔야 정상적으로 이벤트가 수집됩니다.
해당 이벤트의 스크립트가 의도한 웹사이트 페이지 내 잘 세팅되어 있는지 확인해 주세요.

감사합니다.

당근 팀 드림
==================================================================================
