### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by hyungwoo219** [daangn/karrot-conversion-tracker-tool-support#65]
**Describe the question**
A clear and concise description

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

======================================================================================
이전 문의

오늘플러스 계정 총 2개의 스크립트 설치하였는데요.
1개는 랜딩이 이루어지는 오늘플러스 사이트, 다른 1개는 회원가입이 이루어지는 사이트입니다.
회원가입이 이루어지는 사이트에 회원가입 이벤트 추적을 위해서 스크립트 작업을 하였는데요.
현재 방문자 이벤트는 정상 수집되고 있으나, 회원가입 이벤트 확인이 안되고 있습니다.
현재 스크립트 작업에 이슈가 있는지 체크해주실 수 있을지 문의드립니다.

[광고주 오늘플러스]
yksso
전환 추적 코드 ID1707960231485500001
연동 웹사이트 URL https://www.yksso.co.kr
ㄴ 회원가입 이벤트 미수집

======================================================================================
추가 문의 

SMS로 회신 주신 내용 확인 하였으며, 현재 광고주 코드 작업 수정 완료하였다고 합니다.
현재 회원가입 이벤트 수집되는 상태인데요, 말씀 주신 https://m.ykbrand.co.kr/ 관련 문의드립니다.

현재 내부 인원 동원하여 확인 한 결과 모바일 신규 가입시 YKSSO 도메인으로 확인이 된다고 합는데요.
https://www.yksso.co.kr/account/join/sso?site_code=TDPLUS

말씀 주신 회원가입 후 어느 페이지에서 도메인이 변경된다는 것인지, 확인주시면 개발단에 추가 확인 및 스크립트 삽입 요청하겠습니다. 
저희 내부에서 확인하였을때는 YKSSO로 랜딩이 되어서요!
현재 스크립트 작업에 이슈가 있는지 체크해주실 수 있을지 문의드립니다.

**Comment by hyungwoo219** [comment]
메일 수신 : digitalmedia219@dmcmedia.co.kr
해당 메일로 회신 주셔도 괜찮습니다!

**Comment by extJo** [comment]
에 답변 드렸습니다~!

https://github.com/daangn/karrot-conversion-tracker-tool-support/issues/64
