### ISSUE TITLE
[QUESTION] 회원가입 이벤트만 수집되지 않습니다.

### ISSUE THREAD

**Issue by analytics-chan** [daangn/karrot-conversion-tracker-tool-support#67]
**Describe the question**
A clear and concise description

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

2/29 당근마켓 전환 스크립트 코드를 GTM으로 설치했습니다.
방문(페이지뷰) 포함 총 4개 설치했는데 회원가입만 아직까지도 수집이 되지 않고 있습니다.
GTM 디버그 툴로 확인했을 때 회원가입 시 당근마켓 전환 문제없이 작동되고 있는 것으로 보여지는데,
혹시 스크립트 작업에 이슈가 있는지 체크 가능한지 문의드립니다.

ID : 1709169658048400001
연동 웹사이트 URL : https://noon.co.kr/

**Comment by extJo** [comment]
GTM 설정 캡쳐 부탁드립니다

**Comment by analytics-chan** [comment]
![image](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/145420546/10c89ef9-3516-4c33-b3be-f943dfe6aaba)

회원가입 부분만 캡쳐하면 될까요?

**Comment by extJo** [comment]
회원가입 태그 호출 이전에 호출되는 태그가 있을까요?

**Comment by analytics-chan** [comment]
"/member/join_step3" 해당 페이지에 도달했을 때 호출되도록 설정해두어서 회원가입 태그 호출 이전에 호출되는 태그는 업습니다.

**Comment by analytics-chan** [comment]
또한 다른 매체나 GA 회원가입 트리거도 동일하게 설정되어 있는데 현재 당근마켓 픽셀만 수집되지 않고 있습니다 ㅜㅜ

**Comment by analytics-chan** [comment]
혹시 스크립트 작업에 이슈가 있는지 확인 가능할까요?
현재까지 회원가입 이벤트는 수집되고 있지 않습니다.

**Comment by extJo** [comment]
회원가입 이벤트가 트리거 되는 페이지가 로드되는 시점에 공통 스크립트가 트리거 될까요?

**Comment by analytics-chan** [comment]
어제 1544-9796으로 문자 답변 받았을 때 회원가입 완료 페이지에 이벤트 코드가 삽입되어 있지 않다고 하는데,
지금 현재 테스트 해봤을 때 회원가입이 완료되는 페이지에 GTM상으로 소스코드에 확인되고 있습니다.
또한 말씀하신 것처럼 회원가입 이벤트가 트리거 되는 페이지가 로드되는 시점에 공통 스크립트가 트리거 되고 있습니다.
![image](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/145420546/c16d581b-c088-4d9a-8803-7c3708b634c8)

**Comment by extJo** [comment]
모바일인경우 도메인이 m.noon.co.kr 인 걸로 확인됩니다. 
해당 소스에도 반영 되어있는지 확인부탁드리며, 제가 회원가입 하였을 때 가입 완료 이벤트가 발송되지 않은걸로 확인됩니다.
따라서 설치 여부 정확하게 파악 부탁드리며, GTM으로 설치 된 경우 저희가 디버깅하기 어렵습니다.

만약 모바일 버전 사이트에서도 반영되어있다면, GTM 태그 설정 시 공통 스크립트와 가입 완료 스크립트가 동시에 실행되도록 설정해서 테스트 바랍니다.

**Comment by analytics-chan** [comment]
테스트 시 모바일 m.noon.co.kr 에서도 동일하게 완료 이벤트가 설치되어 있는 것으로 보여집니다ㅜㅜ
GTM 설정 시 공통 스크립트와 가입 완료 스크립트가 동시에 실행되고 있는 상황입니다.
혹시 다른 문제점은 없을까요?
![image](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/145420546/778a7844-88e3-4efb-8fd7-429b500dec75)

**Comment by extJo** [comment]
> 해당 소스에도 반영 되어있는지 확인부탁드리며, 제가 회원가입 하였을 때 가입 완료 이벤트가 발송되지 않은걸로 확인됩니다.

해당 부분 확인 바랍니다

**Comment by extJo** [comment]
> 저희 페이지뷰 내에서 스크립트 인식이 되지 않아

어떤 뜻일까요?

또한 공통 스크립트 중 해당 부분 변경 부탁드립니다

이전 버전
```
<script src="https://karrot-pixel.business.daangn.com/0.1/karrot-pixel.umd.js"></script>
```

최신 버전
````
<script src="https://karrot-pixel.business.daangn.com/0.3/karrot-pixel.umd.js"></script>
```

**Comment by analytics-chan** [comment]
테스트 진행 시 공통 스크립트와 가입 완료 스크립트가 동시에 실행되도록 설정되어 있으나 데이터 수집이 되지 않아서 회원가입 완료하는 버튼을 클릭했을 때 스크립트 실행되도록 설치했더니 데이터 수집되고 있음을 말씀드린 거였습니다ㅎㅎ
공통 스크립트 부분은 변경해서 다시 한 번 테스트 해보겠습니다!

**Comment by extJo** [comment]
@analytics-chan 그러면 문제되는 부분은 해결된걸로 파악하면 될까요?

**Comment by analytics-chan** [comment]
2.0으로 변경후 테스트 진행했는데 처음과 동일한 조건으로 페이지뷰로 변경했을 때 여전히 회원가입은 동작하지 않습니다.

**Comment by extJo** [comment]
> 페이지뷰로 변경했을 때 여전히 회원가입은 동작하지 않습니다.

페이지뷰로 변경했다는 말씀이 어떤걸까요?

**Comment by analytics-chan** [comment]
가입 완료 페이지(예: join.html) 에 당근 마켓 스크립트를 추가하여 공통 스크립트와 가입완료 스크립트가 동시에 실행되도록 설정했습니다.
말씀하신 것처럼 2.0으로 변경도 완료했구요.
하지만 여전히 동작하지 않았습니다.

**Comment by extJo** [comment]
그 가입 완료 페이지로 정상적으로 이동하는게 맞을까요?
다른 광고주분들은 문제없이 사용중이라서요 (GTM 또는 직접설치).
전체 가입 플로우 및 태그 호출되고 있는지 정확하게 확인 부탁드립니다

**Comment by analytics-chan** [comment]
가입 완료페이지로 정상적으로 이동하고 있습니다.
전체 가입 플로우 및 태그 호출되고 있는지도 정확하게 확인 진행했습니다.

**Comment by extJo** [comment]
GTM 설정 및 코드 첨부 부탁드립니다

**Comment by analytics-chan** [comment]
![image](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/145420546/0c563c95-7999-4f78-aedf-a3e02941a8b9)
위와 같이 설정했습니다.
다만 타 업체에서 다른 스크립트 삽입시 에러 발생하는 부분 확인되었는데,
공통 스크립트에 들어가는 아래 코드 삽입시 에러 발생하지 않는 것으로 보여져서
해당 부분도 코드 삽입 후 테스트 진행해보려고 합니다.

`<script src="https://karrot-pixel.business.daangn.com/0.1/karrot-pixel.umd.js"></script>`

**Comment by analytics-chan** [comment]
타 업체 소스에서 이벤트별로 코드 삽입 시 데이터 잘 유입되네요.
위 코드를 각각의 이벤트 설정 시 추가해주어야 할 것 같네요.
