### ISSUE TITLE
[QUESTION] 간편결제(네이버페이) 별도 버튼 설치를 하고자 할 때, 필요한 구매스크립트 가이드가 필요합니다.

### ISSUE THREAD

**Issue by dsakfljl** [daangn/karrot-conversion-tracker-tool-support#68]

**Comment by dsakfljl** [comment]
추가로 설명 드리면, 저희 현재 호스팅사는 엔에이치엔커머스(주) 이며, N페이 사용 중인데 버튼에 스크립트 추가가 필요하다고 전달 받았습니다.

다만, 메이크샵과 같이 간단하게 작업이 가능한지 직접 설치해야 한다면 가이드가 있는지 문의 드립니다.
바쁘시겠지만, 가능한 빠른 회신 주시면 감사하겠습니다 :)

아래 웹사이트 전달 드립니다.
https://www.misope.co.kr

**Comment by dsakfljl** [comment]
추가로 설명 드리면, 저희 현재 호스팅사는 엔에이치엔커머스(주) 이며, N페이 사용 중인데 버튼에 스크립트 추가가 필요하다고 전달 받았습니다.
다만, 메이크샵과 같이 간단하게 작업이 가능한지 직접 설치해야 한다면 가이드가 있는지 문의 드립니다.
바쁘시겠지만, 가능한 빠른 회신 주시면 감사하겠습니다 :)

아래 웹사이트 전달 드립니다.
https://www.misope.co.kr

**Comment by extJo** [comment]
메이크샵 이외에 타 호스팅 업체에서는 간단연동이 불가능하며, 해당 호스트사 API 참고하셔서 설치바랍니다.
저희가 호스팅사가 아니기때문에, 따로 가이드 드리기는 어렵습니다

**Comment by dsakfljl** [comment]
해당 호스팅사에 문의하겠습니다. 답변 감사합니다:)

**Comment by dsakfljl** [comment]
구매금액 스크립트 관련해서 추가로 문의드립니다!

 
<script>
window.karrotPixel.track(
  'Purchase', 
  {
    'total_price': '{구매금액}',
    'total_quantity': '{구매수량}',
    'products': [{
      'id': '{상품ID}',
      'name': '{상품명}',
      'quantity': '{상품수}',
      'price': '{상품가격}',
    }]
  }
)
</script>


해당 스크립트에서 구매금액 부분에 '원' 또는 ','과 같은 표시단위가 없이 단순 숫자로만 반영이 되어야 하는건지 확인 부탁드립니다.

**Comment by extJo** [comment]
네 단순 숫자만 입력 가능합니다

**Comment by dsakfljl** [comment]
구매 전환(구매, 구매금액)에 있어 무통장이나 N페이와 같은 간편결제는 찍히는 데 카드결제에 대한 전환값이 잡히지 않습니다. 혹시 스크립트 상에 어떤 부분이 문제인지 확인해주셨으면 합니다.
![카드구매1](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/163078853/faadaa0e-131e-44f9-80f6-6b200baf40b7)
![카드구매2](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/163078853/5d0faec7-e3bc-4fa6-a9f2-4848e466fd29)

**Comment by extJo** [comment]
수집과 관련된 문제가 아니라서 해당 호스팅사에 문의드려야 할거같습니다~!
