### ISSUE TITLE
[세일업_김정윤] 전환 추적 관리 관련 문의의 건_테스트용2

### ISSUE THREAD

**Issue by KimJeongYoon** [daangn/karrot-conversion-tracker-tool-support#69]
안녕하세요 당근 팀 박소래매니저님.
세일업 김정윤입니다.

다름이 아니오라, 하기 광고 계정 전환 추적 관리 관련 문의드리오니 확인 부탁드립니다.

                                                                          - 하 기 -

1. 광고계정명 : 테스트용2
2. 광고계정ID : 2621416
3. 전환 추적 관리 : 방문, 서비스신청 데이터 잡히게 스크립트 설치 완료되어 잘 수집되고 있습니다. 
![KakaoTalk_20240326_175516935](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/165113431/15825a7d-3a63-4897-b19f-1c96ebbd07da)

![KakaoTalk_20240326_174502538](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/165113431/c22a1de9-e994-4bbf-adf3-1e0f3580b125)

4. 광고관리 화면 : 전혀 표시가 되지 않고 있습니다. 뭔가 셋팅을 잘못 한건지 확인 한번해주시면 감사하겠습니다. 
![KakaoTalk_20240326_174528584](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/165113431/047ddb45-5a59-4845-964e-14ead072cf34)

  (상기와 같이 전부 0으로만 나옵니다.)

 

스크립트 설치는 잘 되서 수집 잘 되고 있는데 
광고계정하고 결과 연동이 안되고 있는 문제 같다고 하십니다만,
확인 한 번 부탁드리겠습니다.

이상, 감사합니다.

**Comment by WONDOOBANJUM** [comment]
안녕하세요. 호스팅 카페24를 사용하고 있어서 코드는 쉽게 넣을 수 있었습니다. 방문만 수집되고 이 외 항목은 왜 수집이 안될까요.. 담당자 원두반점 심학수 010-6655-5484
