### ISSUE TITLE
[QUESTION] 18일 15시 22분 이후로 전환 추적 데이터가 들어오지 않습니다.

### ISSUE THREAD

**Issue by ai-latte** [daangn/karrot-conversion-tracker-tool-support#7]
![image](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/107900148/1f5d6311-19f6-4b06-bc68-2b1fda5c0c8c)

전환 추적 관리에서 제공하는 버전이 변경되어 있어 0.1로 버전으로 변경 후 배포하였으나
여전히 전환 추적 데이터가 잡히지 않고 있습니다.

확인 부탁드립니다.

**Comment by Gummybearr** [comment]
안녕하세요 ai-latte님

제가 확인했을 때는 전환추적기 2개에서 이벤트가 수집되고 있는 것으로 보입니다.

현재도 이슈가 있다면 알려주세요.

감사합니다.

**Comment by ai-latte** [comment]
답변 감사합니다.
현재 수집 중인 이벤트 확인했습니다.

그런데 이전에는 이벤트 발생 시 당근 비즈니스 화면에서 즉시 반영되어 보여졌는데,
일정 시간을 기준으로 수집 데이터가 반영되는 것 같습니다.

반영까지 시간이 걸리는 게 맞을까요?

**Comment by extJo** [comment]
@ai-latte 안녕하세요.
내부적으로 이벤트 처리 지연이 발생했어서, 지금은 문제없이 수분내에 반영되어 확인할 수 있습니다.
불편을드려서 죄송합니다.
