### ISSUE TITLE
[QUESTION] 로그인 이벤트 스크립트 위치 문의

### ISSUE THREAD

**Issue by bimgallery** [daangn/karrot-conversion-tracker-tool-support#70]
안녕하세요, 로그인 이벤트 스크립트 설치하려고 하는데,
로그인을 완료한 페이지에 삽입하는 걸 권장한다고 써 있어
문의 드립니다.

현재 운영 중인 사이트가 로그인 후 메인으로 이동하는데
이벤트 스크립트를 로그인 페이지에 삽입하는 것이 맞나요
아니면 메인 페이지에 로그인 시 스크립트 동작하도록 삽입하는 것이 맞나요?

**Comment by extJo** [comment]
후자로 동작하는게 맞습니다
