### ISSUE TITLE
[QUESTION]당근마켓 리타겟팅 캠페인 진행을 위해 스크립스 삽입 문의드립니다.

### ISSUE THREAD

**Issue by SEAMIN97** [daangn/karrot-conversion-tracker-tool-support#71]
안녕하세요. 담당자님

<해커스 공인중개사> 당근마켓 리타겟팅 캠페인 진행을 위해 스크립스 삽입 문의드립니다.
공통 스크립트 삽입 관련 문의사항이 있어 아래에 전달드리니 확인 후 답변 부탁드리겠습니다.
 
[문의사항]
하기와 같이 공통 스크립트를 삽입하면 리타게팅이 가능한것인지 문의드리오니, 확인하시어 회신 부탁드리겠습니다 !
 <script src="https://karrot-pixel.business.daangn.com/0.2/karrot-pixel.umd.js"></script> <script>    window.karrotPixel.init('전환 추적 코드 ID');         window.karrotPixel.track('ViewPage'); </script> 

감사합니다.

**Comment by extJo** [comment]
단순 방문을 기준으로 리타게팅 하시려면 그 스크립트만 설치하시면 됩니다.
자세한 부분은 가이드 참고 부탁드립니다
https://bizschool.daangn.com/43922c93-2958-42c3-811f-3546d17e80e1
