### ISSUE TITLE
[QUESTION] 당근마켓 전환추적코드 이벤트값 수정 문의 

### ISSUE THREAD

**Issue by JiyoonRyu** [daangn/karrot-conversion-tracker-tool-support#72]
안녕하세요 에코마케팅 - 웅진스마트올 키즈 담당자입니다.

광고계정명 : 웅진스마트올 키즈
광고계정ID : ID: 2648813
전환 추적 관리 : 현재는 방문, 구매 위주로 전환 스크립트 설치돼있는 것 같은데 구매 이벤트가 아닌 잠재고객수집 이벤트로 데이터 로그 쌓이게 수정하는 방법 문의드립니다. 

웅진스마트올 키즈 캠페인은 DB 캠페인이기 때문에 전환추적코드 "구매" 데이터를 "잠재고객수집" 데이터로 수정해야한다고 말씀해주셨는데, 코드 확인 과정에서 생긴 문의사항 아래로 전달드립니다. 

우선 웅진스마트올 키즈 전환추적관리 페이지에서 <데이터 수집 로그 상세> 에 이벤트가 전혀 확인되지 않고 있습니다! 
질문 1)  혹시 아래 가이드 처럼 전환 추적코드에 등록한 도메인과 실제 세팅할때 쓰는 URL (단축URL 활용 중 / 매번 바뀜) 이 다르기 때문에 로그가 쌓이지 않는 것이라고 보면 될 지 확인 부탁드립니다. 저희도 실시간으로 성과를 트레킹해야하기에 도메인 URL 과 세팅URL이 다를 수 밖에 없는데 이럴 때 로그가 쌓이게 하는 방법도 있을까요?
*가능한 전환 추적 코드에 등록한 도메인과 랜딩페이지 URL 이 동일한 도메인으로 구성될 수 있게 세팅 권장

질문 2-1) 추가로, 웹사이트 연동할 때, 방문과 구매 데이터 수집 모수는 찍히는데 데이터 수집 로그는 찍히지 않는 이유 확인 부탁드립니다. 

또한 히스토리 확인해보니 전환추적코드 연동코드는 당근 가이드에 있는 <기본 코드>로만 등록돼있습니다.
질문 2-2) 구매 PURCHASE 이벤트 코드 등록이 안 돼있는데도 데이터 수집로그상 수집중으로 뜨는 이유도 확인 부탁드립니다. 

3) 당근 가이드에서는 전환추적 관리 코드 중 이벤트값을 수정하기 위한 가이드는 기재돼있지 않은데, 저희 캠페인과 같이 구매 이벤트에서 잠재고객수집으로 데이터 수집 모수를 변경해야할 경우 수정방식이 아닌, 기존 등록된 전환추적코드 외에 신규방식으로로 전환추적코드를 하나 더 생성해야하는 것인지도 확인 부탁드립니다. 
ㄴ 전일 신규로 전환추적코드를 생성해도 LEAD 이벤트 추가가 불가한데 자세한 수정 방식 전달 부탁드리겠습니다. 

현재 이미지 파일이 첨부되지 않아 글로만 작성드렸는데 자세한 이미지 및 메일 히스토리는 "강지원 매니저"님께 문의 부탁드립니다.

**Comment by extJo** [comment]
1) 픽셀 설치가 제대로 되어있지 않은것 같은데, 확인 부탁드립니다
2) 1번 확인 이후에 답변 드리도록 하겠습니다

**Comment by JiyoonRyu** [comment]
픽셀 설치 가이드에 대해서는 어디서 확인할 수 있을까요??

**Comment by extJo** [comment]
[전환 추적 코드 연동 가이드](https://bizschool.daangn.com/tracking-guide) 에 있습니다

**Comment by JiyoonRyu** [comment]
매니저님 혹시 픽셀 설치가 전환코드 설치와 동일하다고 생각하면 될까요? 
아래 이미지 참고 부탁드립니다. 기존에 설치돼있던 전환추적코드인데 어떤 부분이 오류인지를 몰라 문의드린 건이어 확인 부탁드리겠습니다. 
![당근마켓 전환추적코드 2](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/165269363/b1b436aa-d7d3-4bb4-bcfb-e2f7e4e3149e)
![전환추적관리 PNG](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/165269363/c50afcc3-bb99-4937-ad13-60ee482126a1)

**Comment by extJo** [comment]
네 픽셀 설치랑 동일한게 맞습니다
[상세 가이드](https://bizschool.daangn.com/43922c93-2958-42c3-811f-3546d17e80e1)를 참고하셔서 이벤트를 수집할 수 있도록 설치 부탁드립니다

**Comment by JiyoonRyu** [comment]
매니저님 상세가이드에 적힌대로 이벤트를 수집할 수 있도록 캠페인 딴에서 전환추적코드가 연동은 돼있으나, 초반 질의사항에 적힌대로 구매이벤트가 아닌, 잠재고객수집 이벤트로 수정 요청을 주셨기에 해당 방법 문의드린 건입니다. 
ㄴ 또한 데이터는 쌓이고 있으나, 데이터수집로그는 찍히지 않고 있는 부분 또한 의문이어 이 부분 확인 부탁드리겠습니다. 
![전환추적코드 연동은 돼있음](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/165269363/5b3d39ae-7edf-4963-aed0-495403d29740)

**Comment by extJo** [comment]
> 매니저님 상세가이드에 적힌대로 이벤트를 수집할 수 있도록 캠페인 딴에서 전환추적코드가 연동은 돼있으나, 초반 질의사항에 적힌대로 구매이벤트가 아닌, 잠재고객수집 이벤트로 수정 요청을 주셨기에 해당 방법 문의드린 건입니다.

가이드에 있습니다. 구매대신 잠재고객 수집으로 변경하시면 됩니다

> ㄴ 또한 데이터는 쌓이고 있으나, 데이터수집로그는 찍히지 않고 있는 부분 또한 의문이어 이 부분 확인 부탁드리겠습니다.

최근에 수집된 이벤트가 없어서 로그가 나오지 않습니다.

<img width="1058" alt="image" src="https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/22790901/4ecf12bc-03b9-496c-a620-784a77954a02">

**Comment by JiyoonRyu** [comment]
매니저님, 전환추적코드를 초반 생성했을 때 이벤트값을 넣을 수가 없게 돼있기 때문에 가이드와 같이 실행할 수가 없었습니다. 
ㄴ 때문에 수정 관련 방법을 자세히 여쭤본 부분이며 혹시 유선 설명이 가능하시다면 
010-6210-5379 에코마케팅 유지윤으로 연락 부탁드리겠습니다.

**Comment by extJo** [comment]
생성할때 드리는 코드는 예제이며, 가이드를 따라서 설치하신다면 문제없이 설치하실 수 있습니다

**Comment by JiyoonRyu** [comment]
매니저님 가이드 자체가 어려운 문제가 아니라, 코드를 편집할 수 있는 란 자체가 아예 막혀있습니다. 
이 
![잠재고객수집 이벤트 전환추적코드 넣으면되는데 코드를 넣을 수 있는 란의 편집 자체가 안됩니다](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/165269363/699eb274-20ee-47d5-83b4-614ffddc80f0)
부분 때문에 잠재고객 데이터 수집할 수 있는 코드 자체를 넣지 못한 상황이며 이미지 참고 부탁드립니다. 
ㄴ 현재 진척상황이 아예 없어 확인 가능하시다면 연락 부탁드리겠습니다.

**Comment by extJo** [comment]
@JiyoonRyu 코드는 광고주 사이트에 삽입할떄 수정하셔 추가하시면 됩니다
