### ISSUE TITLE
[QUESTION] 안녕하세요 당근마켓 전환추적 코드 생성했으나 수집이 안되어서 문의드립니다.

### ISSUE THREAD

**Issue by juyeongEee** [daangn/karrot-conversion-tracker-tool-support#73]
안녕하세요
프로그레스미디어 - 페셔네이트 담당자입니다

광고계정명 : 페셔네이트
광고계정 ID : 2413437
전환추적관리 :  카탈로그광고로 진행중인 업체이며, 광고 셋팅 전에 전환추적관리에서 < +전환추적코드 추가> 로 만들었으며, 별도의 스크립트 삽입없이 공통 스크립트로만 진행중입니다. 4/8 기준으로 광고 돌아가고 있고 전환추적관리에서 데이터 수집이 확인이 안되어 문의드립니다.

질문 1) 웹페이지 호스팅사는 카페 24를 이용중이며 혹시 호스팅사별로 전환추적코드를 별도로 셋팅을 해야될까요?

질문 2) 카탈로그 상품(소재) 별로 추적코드를 추가해야되는지와 각각의 코드 생성 때 URL 입력칸에 상품상세페이지 주소는 입력이 불가한데 이부분은 웹페이지 도메인으로만 입력이 가능한가요?

질문 3) 전환추적코드에서 데이터로그가 <수집전>으로만 떠있고 당근가이드에 있는 기본코드로만 등록을 해둔상태인데 < 방문 / 로그인 / 구매 / 장바구니담기 / 상세페이지 조회 > 모집수를 확인하려면 스크립트를 삽입을 해야될까요?

질문 3-1) 혹시 스크립트 삽입을 해야된다면 방법이 어떻게 되는지도 말씀부탁드립니다. 
생성하면서 스크립트 삽입이나 수정부분이 되지 않아서 같이 확인 후 말씀부탁드립니다.

**Comment by extJo** [comment]
> 질문 1) 웹페이지 호스팅사는 카페 24를 이용중이며 혹시 호스팅사별로 전환추적코드를 별도로 셋팅을 해야될까요?

cate 24는 해당 업체에서 연동 이슈가 있어서 따로 cafe 24측에 문의 바랍니다. 일반적인 연동은 [가이드](https://bizschool.daangn.com/tracking-guide)에 따라서 설치하시면 됩니다

> 질문 2) 카탈로그 상품(소재) 별로 추적코드를 추가해야되는지와 각각의 코드 생성 때 URL 입력칸에 상품상세페이지 주소는 입력이 불가한데 이부분은 웹페이지 도메인으로만 입력이 가능한가요?

캠페인 단위로 추가해야합니다. 상세페이지 주소를 넣는것이 아닌 최상위 도메인만 넣으면 수집 가능합니다.
ex) naver.com/shop/12341234 -> naver.com 만 입력

> 질문 3) 전환추적코드에서 데이터로그가 <수집전>으로만 떠있고 당근가이드에 있는 기본코드로만 등록을 해둔상태인데 < 방문 / 로그인 / 구매 / 장바구니담기 / 상세페이지 조회 > 모집수를 확인하려면 스크립트를 삽입을 해야될까요?

네 가이드에 따라서 이벤트 별로 설치하시면 됩니다.
> 질문 3-1) 혹시 스크립트 삽입을 해야된다면 방법이 어떻게 되는지도 말씀부탁드립니다.
생성하면서 스크립트 삽입이나 수정부분이 되지 않아서 같이 확인 후 말씀부탁드립니다.

가이드 확인 바랍니다.

**Comment by juyeongEee** [comment]
가이드 확인하였으나 이해가 잘 안되어서 다시 문의드립니다

전환추적코드 생성 시 웹사이트연동으로 생성하며 별도 스크립트 삽입 없이 생성하였으나 이벤트 확인이 안되는데
문제점이 뭔지를 잘 모르겠습니다 
![전환추적 연동 코드](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/166467446/986b8985-3c17-413e-9079-9490bd65decf)
![핏에이블 연동코드](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/166467446/a2394632-e639-49c7-9f01-2ba6a1f8c54e)

**Comment by extJo** [comment]
되는것으로 확인 됩니다

<img width="1425" alt="image" src="https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/22790901/f8d25e1b-771f-4d18-9304-588497d9431b">
