### ISSUE TITLE
[QUESTION] 서비스 신청 이벤트 스크립트 등록 문의 드립니다.

### ISSUE THREAD

**Issue by momoya80** [daangn/karrot-conversion-tracker-tool-support#74]
이벤트 스크립트를 사용하려면, 
(1)픽셀 설치 공통 스크립트와 (2)전환 추적을 위한 이벤트 스크립트를 설치하는 것은 알고 있습니다.
해당 픽셀을 설치하는 위치와 호출하는 방법에 대해 문의 드립니다.

먼저 제가 광고를 진행하고자 하는 랜딩페이지는 2개의 도메인으로 구성되어 있습니다.
즉 랜딩페이지의 도메인으로 이용중인 '티스토리' 페이지에 
서비스 신청을 받는 도메인을 '아이프레임 방식'으로 삽입하여 랜딩페이지를 만들었습니다.

질문1.
이렇게 도메인이 다른 경우에 2개의 스크립트(1번 - 픽셀 스크립트, 2번 - 이벤트 스크립트)는 어느 도메인에 설치해야 수집이 가능한지 궁금합니다.

질문2.
이벤트 스크립트는 랜딩페이지에서 [서비스 신청완료]를 실행한 후, 해당 스크립트가 동작하도록 해야하나요? 아니면 랜딩페이지에 소스만 삽입이 되면 알아서(?) 체크가 되는 건가요?

바쁘시겠지만 확인 후 빠른 답변 부탁드립니다.

**Comment by extJo** [comment]
1. 도메인 둘 다 전환추적도구에 등록해주시길 바랍니다
2. 스크립트가 동작하도록 삽입해야할거같습니다.

참고로 아이프레임 기반으로 동작하는 건 동작할지 보장할 수 없어보입니다.
