### ISSUE TITLE
[QUESTION] 당근마켓 스크립트 설치 관련 문의드립니다.

### ISSUE THREAD

**Issue by SEAMIN97** [daangn/karrot-conversion-tracker-tool-support#75]
안녕하세요. 담당자님

<당근마켓> 리타겟팅 진행을 위해 스크립트 설치 중 문의드릴 사항이 있어 아래에 전달드립니다.

[문의 사항]
>> 스크립트 내 ‘전환 추적 코드 ID’, ‘ViewPage’ 값을 삽입하도록 되어있는데, 어떤 값을 입력하면 되는 것인지 문의드립니다. 

이미지 파일 첨부드리니 참고하시어 답변 부탁드리겠습니다.
감사합니다.
![20240416_144452](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/165226234/b98c5ed8-d906-475e-8656-92ee60fb0457)

**Comment by Gummybearr** [comment]
안녕하세요 :) 

당근비즈니스 광고 전문가모드 - 광고 관리 - 전환 추적 관리 에서 생성한 전환 추적 코드 ID를 입력하면 됩니다.
전환 이벤트의 종류 등 다른 내용들은 [가이드](https://bizschool.daangn.com/tracking-guide) 문서를 참고해주세요

**Comment by SEAMIN97** [comment]
당근마켓 전환 추적 코드 생성 시 확인되는 코드 이미지로 재전달드립니다.
![image](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/165226234/8c9e5b35-b964-4ac3-96b0-32ce754d31db)

**Comment by extJo** [comment]
> ViewPage은 당근마켓 전환 추적 코드 생성 시 확인되는 아래의 코드 넣으면 되는 부분일지 아님 다른 값을 넣어야하는 것일지 문의드립니다.

네 맞습니다.
