### ISSUE TITLE
[QUESTION] 서비스 신청 이벤트 추적 질문

### ISSUE THREAD

**Issue by moon-135** [daangn/karrot-conversion-tracker-tool-support#76]
안녕하세요, 웹페이지에서 사용자 form 제출을 트리거로 "서비스 신청" 이벤트를 추적하고자 합니다.
가이드에서 아래 코드를 확인했는데요, 질문이 있습니다.
1. 스크립트를 어느 위치에 삽입해야 하나요? (form 제출 시 특별한 화면이 노출되지는 않고 form 내에서 제출이 완료되었다는 메시지만 나오게 되어 있습니다)
2. 서비스를 신청하는 이벤트에 **동적 스크립트가 작동하는 형태로 삽입**하라는 것이 무슨 의미인지 잘 모르겠습니다. 

<script>
window.karrotPixel.track('SubmitApplication');
</script>

**Comment by extJo** [comment]
1. 제출 버튼을 눌렀을때 해당 스크립트가 동작하도록 작성해주시면 될거같습니다
2. js 함수를 만들어서 클릭과 같은 액션이 발생한 경우 동작하도록 하면 됩니다
