### ISSUE TITLE
[QUESTION] 당근마켓 전환 스크립트 관련 문의의 건

### ISSUE THREAD

**Issue by seungwooyawm** [daangn/karrot-conversion-tracker-tool-support#77]
안녕하세요.

광고 계정명 : 하나애드_STCO
광고 ID : 2892152

전환추적 스크립트 관련하여 문의사항이 있어 전달드립니다.

    'products': [{
      'id': '{상품ID}',
      'name': '{상품명}',
      'quantity': '{상품수}',
      'price': '{상품가격}',
      
위와 같이 전환 스크립트 내 (products) id ~ price 경우 [단일 / 복수] 설정이 가능한데,

복수로 전환수 / 전환매출값을 트래킹 하고자 할 때 스크립트 내 별도의 수정은 필요 없는지

혹은 복수 트래킹을 위해서 스크립트 내 추가적인 수정이 필요한 지 여부 문의드립니다.

**Comment by extJo** [comment]
안녕하세요. 복수개로 트레킹 하길 원하신다면 products에 상품과 관련된 데이터 구조체(id, name, quantity 등이 포함된)를 배열로 넣어주시면 됩니다. 또한 복수개인 경우 total_price와 total_quantity가 배열에 넣은 합계만큼 들어갈 수 있도록 제공해주시면 됩니다

**Comment by seungwooyawm** [comment]
STCO의 경우 복수개로 트래킹이 필요하여 

혹시 말씀주신 내용을 반영한 스크립트 예시 전달 가능한지 추가적으로 문의드립니다.

**Comment by extJo** [comment]
내용 반응은 광고주 측에서 직접 하셔야하며, 저희가 광고주의 모든 환경 및 코드를 이해하고 있는 바가 아니라서 직접 작성해주셔야합니다

**Comment by seungwooyawm** [comment]
현재 당근 마켓 전환 스크립트 설치 완료되어,

정상적으로 작동하는 여부 확인해 주실 수 있는지 문의드립니다.

**Comment by extJo** [comment]
전환추적관리에서 이벤트가 수집되는지 확인하시면 됩니다
