### ISSUE TITLE
[QUESTION] 이벤트 스크립트 설치 문의

### ISSUE THREAD

**Issue by juyeongEee** [daangn/karrot-conversion-tracker-tool-support#78]
**Describe the question**
A clear and concise description

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

이벤트 스크립트 설치 관련해서 문의 드립니다.

호스팅사 : 카페 24

광고주 측 개발 담당자로부터 회신 온 내용으로
" 회원가입 이벤트 스크립트는 설치가 불가능합니다 :: 1초 회원가입 사용으로 인해 회원가입 완료 페이지가 존재하지 않음 "

이런 경우에 회원가입 스크립트를 어느 쪽으로 설치를 해야되는지 문의 드립니다.

" 로그인 완료 후 마이페이지로 떨어지는 경우에 로그인 스크립트를 마이페이지로 넘어간 상태로 설치해도 되는지 문의 요청 "

이 두가지에 대해서 문의드립니다.

**Comment by extJo** [comment]
> 광고주 측 개발 담당자로부터 회신 온 내용으로
> " 회원가입 이벤트 스크립트는 설치가 불가능합니다 :: 1초 회원가입 사용으로 인해 회원가입 완료 페이지가 존재하지 않음 "
> 이런 경우에 회원가입 스크립트를 어느 쪽으로 설치를 해야되는지 문의 드립니다.
> " 로그인 완료 후 마이페이지로 떨어지는 경우에 로그인 스크립트를 마이페이지로 넘어간 상태로 설치해도 되는지 문의 요청 "
> 이 두가지에 대해서 문의드립니다.

회원가입이 되었다고 판단되는 페이지 또는 동작에 스크립트를 삽입하시면 됩니다

**Comment by juyeongEee** [comment]
그러면 로그인 스크립트의 경우에는 어떻게 설치를 해야될까요

**Comment by extJo** [comment]
특정 밴더사를 저희가 다 이해하고 가이드 드릴 수 없으며, 광고주마다 상황이 다르므로 적절한 곳에 스크립트 삽입 하시면 됩니다

**Comment by juyeongEee** [comment]
혹시 카페24에 구매 스크립트를 삽입했는데, 여기뿐만아니라 카페24로 자사몰 운영하는 업체들 모두 당근 전환추적코드에서 확인하면 당근 유입이 아닌, 자사몰 전체 구매 값이 체킹이 되는 데 따로 당근에서 유입되어 확인 할 수 있는 방법이 있을까요?

**Comment by extJo** [comment]
광고 집행을 도와주는 도구이며, GA 같은 애널리틱스 제품이 아니라서 말씀하신것 처럼 분석 할 순 없습니다~ 메타 픽셀 참고 부탁드립니다
