### ISSUE TITLE
구매 전환 이벤트 문의드립니다.

### ISSUE THREAD

**Issue by runcat1** [daangn/karrot-conversion-tracker-tool-support#8]
**Describe the question**
A clear and concise description

**Desktop (please complete the following information):**
 - Browser [chrome]

**Additional context**

<script>
window.karrotPixel.track(
  'Purchase', 
  {
    'total_price': '{구매금액}',
    'total_quantity': '{구매수량}',
    'products': [{
      'id': '{상품ID}'
      'name': '{상품명}',
      'qunatity': '{상품수}',
      'price': '{상품가격}'
    }]
  }
)
</script>

카페24 이용중이며, 호스팅사 구매 변수(함수)를 알고싶습니다.

**Comment by seongjunhwang** [comment]
안녕하세요!

호스팅사에서 사용하는 변수는 각 호스팅사의 서비스를 통해 확인이 가능한 점 양해부탁드립니다.
카페24의 경우 서비스 가이드 페이지 내 모듈리스트 라는 문서를 통해 구매 관련 변수 확인이 가능한 것으로 보이는데요.
자세한 내용은 아래 링크를 확인해주시기 바랍니다.

[https://sdsupport.cafe24.com/product/detail.html?product_no=6139&cate_no=67&display_group=1](url)
