### ISSUE TITLE
[QUESTION] 전환 추적 관리 이벤트 수집 관련 문의

### ISSUE THREAD

**Issue by geonheeThingsflow** [daangn/karrot-conversion-tracker-tool-support#80]
**당근 전환 추척관련 수집안되는 문제**
안녕하세요.
전환추척 스크립트 연동 후 이벤트 수집되지않아 문의드립니다.

광고계정 : 띵스플로우_헬로우봇

배포된 웹 페이지에 아래와같이 스크립트 코드 확인됩니다.
```
<script src="https://karrot-pixel.business.daangn.com/0.2/karrot-pixel.umd.js"></script>
<script>
    window.karrotPixel.init('광고ID');
    window.karrotPixel.track('ViewPage');
</script>
```

"광고ID" 문제없는것 확인하였고 "연동 웹사이트 URL"도 정상등록 하였으나 계속해서 이벤트 수집전으로 표시되어 문의 드립니다.

**Comment by extJo** [comment]
'광고 ID' 라고 적은 부분에 어떤값을 넣으셨을까요? 운영중인 전환 추적도구가 운영 / 개발 두가지로 나뉜거같은데 맞을까요?

**Comment by geonheeThingsflow** [comment]
@extJo 네 운영, 개발 도메인 따로 세팅해두었고 광고ID에 전환 추적 관리 "전환 추적 코드 ID"값을 넣어놨습니다.

**Comment by extJo** [comment]
설치한 웹앱 주소 부탁드립니다

**Comment by geonheeThingsflow** [comment]
@extJo https://dev.hellobot.co/ 입니다.

**Comment by extJo** [comment]
혹시 서버사이드 랜더링일까요?

**Comment by geonheeThingsflow** [comment]
@extJo SSR로 내려주는 코드에서는 "karrot-pixel" 부분이 안보이네요, 당근픽셀은 무조건 SSR환경에서만 동작하는걸까요?

**Comment by extJo** [comment]
아뇨, 픽셀은 CSR 환경에서만 동작합니다! 
에러로그 보니깐 window 가 정의되기전에 script가 mount되는거같은데요. window 정의가 된 이후에 script가 mount 될 수 있도록 코드 수정 부탁드립니다

**Comment by extJo** [comment]
네 ~ 그러면 이슈는 닫도록 하겠습니다
