### ISSUE TITLE
[QUESTION] 전환 추적 관리 이벤트 수집 관련 문의

### ISSUE THREAD

**Issue by EDAEUN** [daangn/karrot-conversion-tracker-tool-support#81]
안녕하세요
당근 전환 추적 스크립트 연동후 이벤트 수집이 중복으로 집계되고 있어 해당 사유 문의 드립니다.

이벤트 스크립트는 [서비스 신청]에만 삽입이 되어있으나, [방문]에도 중복으로 집계되고 있으며
[서비스 신청] 이벤트 23년 11/2에 추가 되었으며 이후 정상 트래킹 중으로 확인했던 점 참고 부탁 드립니다.

* 광고계정: 윤스닷컴
* 추가된 스크립트 코드:

<script>
window.karrotPixel.track('SubmitApplication');
</script>

**Comment by extJo** [comment]
방문 이벤트는 공통 스크립트내에 존재하며, 필수적으로 설치해야하는 이벤트입니다

https://bizschool.daangn.com/43922c93-2958-42c3-811f-3546d17e80e1#:~:text=%E2%80%A2-,%EC%9B%B9%EC%82%AC%EC%9D%B4%ED%8A%B8%20%EC%97%B0%EB%8F%99%20%2D%20%EA%B3%B5%ED%86%B5%20%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8,-%3C!%2D%2D%20Danggeun%20Market%20Code

**Comment by EDAEUN** [comment]
네 방문 이벤트는 공통 스크립트인점 확인 하였습니다.

다만 저희가 내부적으로 확인하고 있는 서비스 신청수 데이터와 전환추적 이벤트 코드를 통한 신청수가 60배 이상 차이가 나서,
이벤트 스크립트가 중복으로 집계되고있는건 아닐지 재문의 드립니다.

ex) 내부 데이터 기준 4월 신청수 166건 > 전환 추적 코드의 4월 이벤트 스크립트 신청수 9898건
└ 서비스 신청 완료 페이지에 이벤트 스크립트 추가 되어있음

**Comment by extJo** [comment]
서비스 신청 완료 스크립트를 신청 후 방문하는 페이지에 설치하셧다면, 유저가 화면을 리프래시 하는 동작을 하면 중복집계가 가능합니다.
따라서 신청, 구매와 같은 이벤트는 특정 동작을 발생시키는 (예를들면 구매버튼을 누른다던지) 시점에 호출 될 수 있도록 스크립트를 설치하시기 바랍니다

**Comment by EDAEUN** [comment]
네 말씀주신 바와 같이, CTA 버튼에 설치 해보려 했는데 광고주 측에서 해당 코드가 이미 적용되어 있다고 하셔서
아래 코드 내용으로 여부 확인 부탁 드리겠습니다.

<link rel="stylesheet" href="/image/common/css/event-240325.css">

 



<script src="https://karrot-pixel.business.daangn.com/0.1/karrot-pixel.umd.js"></script>

<script>

  window.karrotPixel.init('1697596674446800001');

  window.karrotPixel.track('ViewPage');

  window.karrotPixel.track('SubmitApplication');

</script>


![Uploading image001.png…]()

**Comment by extJo** [comment]
버튼에 설치되어있지않고, 전역 헤더 스크립트에 설치되어있습니다

**Comment by EDAEUN** [comment]
안녕하세요, 서비스 신청 버튼에 이벤트 스크립트 수정 반영하였는데,
데이터 수집로그가 없다고 나와 해당건 확인 부탁 드리겠습니다.

![image](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/169642404/e6431a66-e037-41c1-9f44-b0a9379bf44b)

**Comment by extJo** [comment]
가이드대로 해당 전환추적코드로 설치하셧는지 확인 부탁드립니다

**Comment by EDAEUN** [comment]
안녕하세요, 윤선생 당근마켓 전환 추적 코드가 미집계되고 있는 오류 보고 드립니다.

현재 서비스신청(SubmitApplication) 전환 추적 코드가 5/31일을 마지막으로 데이터 수집이 끊긴것으로 보여
지난 5/17에 신청하기 CTA 버튼에 스크립트 삽입이 되었는데 미집계 사유 문의 드립니다.

신청 페이지: https://www.yoons.com/experience/consultationRequest
신청 버튼: 페이지 최하단의 [신청] (아래 이미지 참고)
의심되는 사유는 6월에 페이지 변경으로 인해 페이지 시안이 변경되었는데
해당 시점에 CTA 버튼에 삽입된 스크립트도 유실되었을수 있을듯 하여 자세한 확인 부탁 드립니다.
![image](https://github.com/user-attachments/assets/c31446dd-2ff8-404b-8b1c-057b57b090f6)
