### ISSUE TITLE
[QUESTION] 당근 스크립트 설치 관련 문의

### ISSUE THREAD

**Issue by LEE-HAN-NA** [daangn/karrot-conversion-tracker-tool-support#82]
안녕하세요, 전일 당근 스크립트 설치 완료되었으나, 아래 항목이 확인되지 않아 문의 드립니다.

![image](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/169733165/ba364fc1-2b1e-41e8-b409-c03fee0bc21c)

1. 엘리하이_서비스신청(무료체험신청완료)
무료체험신청완료 URL은 아래와 같아 엘리하이 웹사이트 URL과 서브도메인이 상이합니다.
이럴 경우 전환 추적이 안될 수 있는지, 안된다면 어떻게 수정해야하는지 문의드립니다.
m.mbest.co.kr/pub_event/event/00000233e/ajax/join_finish.asp

2. 엘리하이&엘리하이키즈_회원가입
엘리하이/엠베스트/엘리하이키즈 3개 업종은 픽셀을 나누어 두었지만, 회원가입 페이지는 1개 URL(아래)로 동일합니다.
이럴 경우 3개의 공통 스크립트와 1개의 이벤트 스크립트를 설치하면 3개 픽셀에 모두 전환이 1개씩 나오는지 문의드립니다.
https://accounts.mbest.co.kr/memreg/join/mb_join.asp

감사합니다.

**Comment by extJo** [comment]
1, 2 번 다 제인드릴수 있는 마땅한 해결책은 없으며, 통합해서 관리하시길 바랍니다.

**Comment by extJo** [comment]
하나로 통합해서 운영하시도록 직접 설정하시면 됩니다~!

**Comment by LEE-HAN-NA** [comment]
> 하나로 통합해서 운영하시도록 직접 설정하시면 됩니다~!

통합하려면 설치된 기존 스크립트 삭제 후 새로 발급 받아 다시 설치해야하는 번거로움이 있고, 기존 스크립트와 충돌이 일어날 수 있을 것 같아 부득이하게 변경 요청드렸습니다.

- 엘리하이
- 전환 추적 코드 ID : 1713166339471200001

연동 웹사이트 URL을 아래와 같이 수정해주실 수 없는지 문의드립니다.
기존 : https://mjr.mbest.co.kr
변경 : https://mjr.mbest.co.kr, https://m.mbest.co.kr (혹은 https://*.mbest.co.kr)


감사합니다.

**Comment by extJo** [comment]
해당 전환 추적코드에 직접 url을 추가하시면 됩니다.
URL 추가를 원하시는 전환추적코드에 들어가셔서 
우측상단에 위치한 `더보기` -> `웹사이트 연동 추가`를 누르신 뒤에 추가하시면 됩니다

**Comment by LEE-HAN-NA** [comment]
> 해당 전환 추적코드에 직접 url을 추가하시면 됩니다. URL 추가를 원하시는 전환추적코드에 들어가셔서 우측상단에 위치한 `더보기` -> `웹사이트 연동 추가`를 누르신 뒤에 추가하시면 됩니다

말씀주신대로 서브도메인 추가했고, 전환테스트를 통해 스크립트 정상 설치되어 있는 점 확인했습니다.
(완료페이지 코드 txt 파일 첨부)
[엘리하이 MO 무료체험신청완료 페이지.txt](https://github.com/daangn/karrot-conversion-tracker-tool-support/files/15330417/MO.txt)

Fiddler 를 통해 아래와 같이 200 코드 정상 발송 확인했는데, 전환 추적 관리에서 확인 안되는 사유 확인 부탁드립니다.
id	1713166339471200001
uid	km|mbest.co.kr|1711502469714|2f7c7c44-9a7d-4f3b-8c08-bab016311d69
et	SubmitApplication
rl	https://m.mbest.co.kr/memreg/regist/primetab_finish.asp?chk_grade=1&m_key=3194809&ori_key=7866&enc_key=1aa45b39df4318fe295bcd1d6d61a9c900bbdd6c40c0bd4d5875d95ef7280a1be06fee7ef329a38671f7d9b0d36e1d3d00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
l	https://m.mbest.co.kr/pub_event/event/00000233e/ajax/join_finish.asp
ts	1715839398852
pl	{}
md	{"sw":496,"sh":864,"ec":0,"it":1715839398579,"v":"0.3.0"}

감사합니다.

**Comment by LEE-HAN-NA** [comment]
> 다시한번 확인 가능하실까요?

전환 테스트는 개인정보 인증 후 삭제하는데 시간이 걸려서 오늘 진행이 어렵습니다.
다만, 전환 추적 관리에서 서비스신청 1명이 확인되는데 어떤 문제 였는지 알 수 있을까요?

**Comment by extJo** [comment]
픽샐 SDK 내부적으로 버그가 존재해서 금일 패치버전 배포하였습니다~!

**Comment by LEE-HAN-NA** [comment]
> 픽샐 SDK 내부적으로 버그가 존재해서 금일 패치버전 배포하였습니다~!

회원가입 전환은 아직 잡히지 않고 있습니다. 명일까지 확인 후 수집되지 않는다면 전환테스트 후 추가 문의드리겠습니다.
(Closed로 변경하셨기에 추가 답변 드립니다!)
