### ISSUE TITLE
[QUESTION] 지난번과 유사한 오류가 발생 합니다.

### ISSUE THREAD

**Issue by adogbowl** [daangn/karrot-conversion-tracker-tool-support#83]
**Desktop (please complete the following information):**
 - OS: 
 - Browser : 크롬
 - Version : 0.2

**Additional context**

아래와 같은 오류로 픽셀이 정상 적으로 수집이 안되고 있습니다.

<script src="https://karrot-pixel.business.daangn.com/0.2/karrot-pixel.umd.js"></script>
<script>
  window.karrotPixel.init('1715504904393200001');
  window.karrotPixel.track('ViewPage');
</script>

현재 적용한 버전은 0.2 버전이고 지난번에 알려주신 0.3 버전으로 해봐도 동일하게 오류가 발생 하고 있습니다.

https://viinscent.com/
ㄴ 적용된 사이트이며 카페24임대형 쇼핑몰입니다.

order_result.html:1 Access to resource at 'https://collect.kr.karrotmarket.com/p/c?id=1715504904393200001&uid=km%7Cviinscent.com%7C1715662152248%7Cd093ac42-80c5-46ad-a45f-b0fc442d7edd&et=ViewPage&rl=https%3A%2F%2Fviinscent.com%2Forder%2Forderform.html%3Fbasket_type%3DA0000%26delvtype%3DA&l=https%3A%2F%2Fviinscent.com%2Forder%2Forder_result.html%3Forder_id%3D20240514-0000167&ts=1715828459388&pl=%7B%7D&fp=506bacdec4eb08c9c7269404fd61f645&md=%7B%22sw%22%3A3440%2C%22sh%22%3A1440%2C%22ec%22%3A0%2C%22it%22%3A1715828459054%2C%22v%22%3A%220.4.1%22%7D' from origin 'https://viinscent.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.Understand this error
karrot-pixel.umd.js:1 
        
        
       POST https://collect.kr.karrotmarket.com/p/c?id=1715504904393200001&uid=km%7Cviinscent.com%7C1715662152248%7Cd093ac42-80c5-46ad-a45f-b0fc442d7edd&et=ViewPage&rl=https%3A%2F%2Fviinscent.com%2Forder%2Forderform.html%3Fbasket_type%3DA0000%26delvtype%3DA&l=https%3A%2F%2Fviinscent.com%2Forder%2Forder_result.html%3Forder_id%3D20240514-0000167&ts=1715828459388&pl=%7B%7D&fp=506bacdec4eb08c9c7269404fd61f645&md=%7B%22sw%22%3A3440%2C%22sh%22%3A1440%2C%22ec%22%3A0%2C%22it%22%3A1715828459054%2C%22v%22%3A%220.4.1%22%7D net::ERR_FAILED
t.wn @ karrot-pixel.umd.js:1
t.bn @ karrot-pixel.umd.js:1
(anonymous) @ karrot-pixel.umd.js:1
Promise.then (async)
(anonymous) @ karrot-pixel.umd.js:1
i.track @ karrot-pixel.umd.js:1
(anonymous) @ order_result.html?order_id=20240514-0000167:1276Understand this error
order_result.html:1 Access to resource at 'https://collect.kr.karrotmarket.com/p/c?id=1715504904393200001&uid=km%7Cviinscent.com%7C1715662152248%7Cd093ac42-80c5-46ad-a45f-b0fc442d7edd&et=Purchase&rl=https%3A%2F%2Fviinscent.com%2Forder%2Forderform.html%3Fbasket_type%3DA0000%26delvtype%3DA&l=https%3A%2F%2Fviinscent.com%2Forder%2Forder_result.html%3Forder_id%3D20240514-0000167&ts=1715828460089&pl=%7B%22total_quantity%22%3A1%2C%22total_price%22%3A32800%2C%22products%22%3A%5B%7B%22id%22%3A24%2C%22name%22%3A%22%EB%B9%84%EC%9D%B8+%EC%96%B4%EB%8F%84%EB%9F%AC%EB%B8%94+%ED%8D%BC%ED%93%B8+%EB%A9%80%ED%8B%B0+%EC%98%A4%EC%9D%BC%22%2C%22quantity%22%3A1%2C%22price%22%3A29800%7D%5D%7D&fp=506bacdec4eb08c9c7269404fd61f645&md=%7B%22sw%22%3A3440%2C%22sh%22%3A1440%2C%22ec%22%3A0%2C%22it%22%3A1715828459054%2C%22v%22%3A%220.4.1%22%7D' from origin 'https://viinscent.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.Understand this error
karrot-pixel.umd.js:1 
        
        
       POST https://collect.kr.karrotmarket.com/p/c?id=1715504904393200001&uid=km%7Cviinscent.com%7C1715662152248%7Cd093ac42-80c5-46ad-a45f-b0fc442d7edd&et=Purchase&rl=https%3A%2F%2Fviinscent.com%2Forder%2Forderform.html%3Fbasket_type%3DA0000%26delvtype%3DA&l=https%3A%2F%2Fviinscent.com%2Forder%2Forder_result.html%3Forder_id%3D20240514-0000167&ts=1715828460089&pl=%7B%22total_quantity%22%3A1%2C%22total_price%22%3A32800%2C%22products%22%3A%5B%7B%22id%22%3A24%2C%22name%22%3A%22%EB%B9%84%EC%9D%B8+%EC%96%B4%EB%8F%84%EB%9F%AC%EB%B8%94+%ED%8D%BC%ED%93%B8+%EB%A9%80%ED%8B%B0+%EC%98%A4%EC%9D%BC%22%2C%22quantity%22%3A1%2C%22price%22%3A29800%7D%5D%7D&fp=506bacdec4eb08c9c7269404fd61f645&md=%7B%22sw%22%3A3440%2C%22sh%22%3A1440%2C%22ec%22%3A0%2C%22it%22%3A1715828459054%2C%22v%22%3A%220.4.1%22%7D net::ERR_FAILED

![스크린샷 2024-05-16 오후 12 04 08](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/45092579/dbfc5f3b-3937-4bdf-bc8c-0d15f7b71035)

**Comment by extJo** [comment]
다시 확인 부탁드립니다~!

**Comment by adogbowl** [comment]
> 다시 확인 부탁드립니다~!

해결 됐습니다. 감사합니다.
