### ISSUE TITLE
이벤트 스크립트 문의 드립니다.

### ISSUE THREAD

**Issue by moosojeong** [daangn/karrot-conversion-tracker-tool-support#84]
엘리하이키즈 회원가입 수집되지 않아 문의 드립니다.

[ 현재 세팅 상황 ]

1) 회원가입 페이지 현황
엘리하이/엠베스트/엘리하이키즈 3개 업종은 픽셀을 나누어 두었지만, 회원가입 페이지는 1개 URL(아래)로 동일합니다.
이럴 경우 3개의 공통 스크립트와 1개의 이벤트 스크립트를 설치하면 3개 픽셀에 모두 전환이 1개씩 나오는지 문의드립니다.
https://accounts.mbest.co.kr/memreg/join/mb_join.asp

2) 엘리하이키즈 추척코드 형황
아래와 같이 회원가입 스트립트 정상설치 되어 있고, 실제 남겨봤을때 엠베스트 계정으로 집계 됩니다.
저희는 엘리하이키즈로 집계 되어야 하는 부분인데 1번의 영향인 것 으로 예상 하고 있습니다.

  - 전환 추적 코드 ID : 1702368116019000001
  - 회원가입 완료 페이지 PC : https://www.mbest.co.kr/Pub_memreg/mb_join_finish.asp?mflag=False&mem_status=6&co_key=3722
  - 회원가입 완료 페이지 MO : 완료 페이지가 아닌 메인 페이지로 이동 됨

# 설치된 회원가입 스크립트

<script>
window.karrotPixel.track('CompleteRegistration');
</script>

**Comment by extJo** [comment]
세일즈 매니저분들 통해서 전달 완료된거같은데, 맞을까요?
