### ISSUE TITLE
[라이프스탠다드] 구매전환 관련하여 문의드립니다.

### ISSUE THREAD

**Issue by seungwooyawm** [daangn/karrot-conversion-tracker-tool-support#86]
현재 전환 스크립트 설치중에 있으며, 한가지 문의사항이 있어 전달드립니다.

**- 광고 계정 이름 : 하나애드_라이프스탠다드

- 광고 ID : 29250006**

[ 구매전환 스크립트 관련 문의]

전환 추적에서 구매 기준으로 만드는 일반 구매 외에 

네이버 페이와 카카오페이에서 발생하는 구매를 추적하는 별도 방안이 있는지 문의드립니다.

**Comment by extJo** [comment]
네이버페이와 카카오페이 결제 완료 후 랜딩되는 페이지에서 구매 관련 스크립트를 설치하시면 될거같습니다

**Comment by seungwooyawm** [comment]
네이버페이 / 카카오페이 결재 완료 후 자사몰로 다시 랜딩되는 것이 아니라 페이지 내 스크립트 설치 어려워,

당근 마켓의 경우 "네이버페이 / 카카오페이" 클릭 시 구매 전환으로 집계되도록
별도 설정 혹은 추가 스크립트를 활용하여 트래킹 할 수 있는 방안이 있는지 문의드립니다.

**Comment by extJo** [comment]
단순히 네이버페이 / 카카오페이로 결제하기를 누른다고해서 결제가 완전히 이루어지는건 아닐것으로 판단됩니다.
만약 단순히 클릭만 집계하고싶으시면, 해당 결제하기 버튼들에 대해서 클릭 이벤트에 대해서 콜백으로 스크립트가 동작할 수 있도록 작성해주시면 됩니다

**Comment by extJo** [comment]
[비슷한 문의 링크 전달 드립니다](https://github.com/daangn/karrot-conversion-tracker-tool-support/issues/54#issuecomment-1835557646)

**Comment by seungwooyawm** [comment]
안녕하세요.

현재 자사몰 구매전환 스크립트 설치 후 테스트 진행중에 있는데,

스크립트가 정상적으로 작동하지 않아 스크립트 내 어떤 부분에서 이상이 있는지 확인이 가능한지 여부 문의드립니다.

- 현재 삽입 스크립트


<body>

window.karrotPixel.track(
--
  | 'Purchase',
  | {
  | 'total_price': $(".totalPay .-font-optima").text().replace("KRW", "").replace(",", "").trim(),
  | 'total_quantity': products.reduce(function (acc, product) { return acc + product.quantity; }, 0),
  | 'products': products
  | })
  | } catch (e) {
  | console.log(e);
  | }
  | });

**Comment by extJo** [comment]
구매 추가정보에 대한 값들은 string으로 타입 변환 해주셔야합니다! 혹시 그 부분이 대응되어있을까요?

**Comment by extJo** [comment]
@seungwooyawm 혹시 해결되었을까요?

**Comment by seungwooyawm** [comment]
내부 개발자 확인하였을 시 주문완료 스크립트의 경우 string 타입으로 변경 완료되었다고하며,

아래 전환 스크립트 전달드립니다!

말씀주신 것처럼 string 타입으로 변환이 완료되었을 경우 아래 스크립트로 정상적으로 추적이 가능할까요?

<html>
<body>

window.karrotPixel.track(
--
  | 'Purchase',
  | {
  | 'total_price': total_price,
  | 'total_quantity': total_quantity,
  | 'products': products
  | })
  | } catch (e) {
  | console.log(e);
  | }
  | });


</body>
</html>

**Comment by extJo** [comment]
예시로 이렇게 값이 설정되어야합니다
```
window.karrotPixel.track('Purchase', { 
  'total_price': '100000', 
  'total_quantity': '2', 
  'products': [...생략...]
}
```

**Comment by seungwooyawm** [comment]
친절하게 설명주시어 감사합니다!

금일 구매전환 스크립트 추가적으로 수정하여 테스트 예정에 있으며,

일전에 설명 주셨던 것처럼 클릭 이벤트에 대해서 콜백으로 스크립트가 동작할 수 있도록 작성하였는데

혹시 확인해 주실 수 있는지 문의드립니다.

[네이버페이, 카카오페이_스크립트_0614.txt](https://github.com/user-attachments/files/15830195/_._0614.txt)

**Comment by extJo** [comment]
@seungwooyawm 구매가 수집되는걸로 보이는데 맞을까요?

<img width="1521" alt="image" src="https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/22790901/5bd15b3c-3840-497d-9f7d-c43c9899a5fb">

**Comment by seungwooyawm** [comment]
이전에도 전환 추적 내 수집중에 있었으나, 실제 구매테스트시 대시보드상 확인이 어려워
금일 추가적으로 테스트 진행중에 있습니다.

**Comment by extJo** [comment]
>실제 구매테스트시 대시보드상 확인이 어려워
어떤 뜻일까요?

**Comment by seungwooyawm** [comment]
구매 테스트시 정상적으로 이벤트 발생 출처 트래킹이 가능한 점 확인하였습니다.

하기 캡처본과 같이 정상적으로 수집중이라면 문제 없는 것이 맞을까요?

![image](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/168428062/daa588c8-9af4-4cc6-8197-4e5e9ba4b852)

**Comment by extJo** [comment]
네 맞습니다
