### ISSUE TITLE
[QUESTION] 이벤트 스크립트 집계 문의

### ISSUE THREAD

**Issue by chapro84** [daangn/karrot-conversion-tracker-tool-support#87]
업체명 : 카스페이스
전환 추적 코드 ID : 1714015241491400001
연동 웹사이트 URL : https://www.carspace.co.kr

현재 이벤트 스크립트 설치 상황

1. 회원가입(/member/member_update.php 페이지에 삽입)

<script>
window.karrotPixel.track('CompleteRegistration');
</script>

2. 실시간 예약(/sub04/pl/pl_page.php 페이지에 삽입)

<script>
window.karrotPixel.track('SubmitApplication');
</script>

현재 회원가입의 경우 정상적으로 집계가 되고 있는걸로 보이는데
실시간 예약은 제대로 체크가 되지 않아 정검차 문의드립니다.

실시간예약의 경우 클릭 했을 때 해당 페이지가 로딩되는 클릭이벤트로 봐주시면 될 것 같습니다.

마지막으로 광고관리시스템 전환 추적 관리 메뉴에서 표시되는 방무, 회원가입 등 지표가 집계되고 있는데
해당 메뉴는 당근 광고와 상관없이 사이트에서 일어나는 방문 회원가입이 모두 찍히는게 맞는건지 문의드리며,
광고 관리 대시보드에는 당근 광고를 통해 회원가입이 이루어져야 표시가 되는 것 같은데
현재까지 0건이라 혹시 제대로 이벤트 스크립트 셋팅이 된건지 문의드립니다.

**Comment by extJo** [comment]
> 현재 회원가입의 경우 정상적으로 집계가 되고 있는걸로 보이는데
실시간 예약은 제대로 체크가 되지 않아 정검차 문의드립니다.

SubmitApplication (실시간 예약) 이벤트도 발송되는것으로 확인되는데, 실시간 예약을 누르면 해당페이지를 방문하는지 확인부탁드립니다.

> 마지막으로 광고관리시스템 전환 추적 관리 메뉴에서 표시되는 방무, 회원가입 등 지표가 집계되고 있는데
해당 메뉴는 당근 광고와 상관없이 사이트에서 일어나는 방문 회원가입이 모두 찍히는게 맞는건지 문의드리며,

전환 추적 관리메뉴에서 나타나는 지표는 당근 광고에 따른 전환과 상관없이, 사이트에서 일어나는 설치하신 이벤트가 집계됩니다.

> 광고 관리 대시보드에는 당근 광고를 통해 회원가입이 이루어져야 표시가 되는 것 같은데
현재까지 0건이라 혹시 제대로 이벤트 스크립트 셋팅이 된건지 문의드립니다.

전환 추적 관리메뉴에서 집계된다면, 스크립트 설정은 정상적으로 이루어진걸로 판단할 수 있습니다.
