### ISSUE TITLE
[픽셀 삽입 관련 문의] 로그인 이벤트 스크립트 삽입 페이지 문의

### ISSUE THREAD

**Issue by shlim1201** [daangn/karrot-conversion-tracker-tool-support#88]
- 호스팅사 : 카페24

당근마켓 전환추적 코드 - 이벤트 스크립트 중 '로그인 이벤트 스크립트'를 삽입하고자 합니다.
로그인이 완료되면 사이트 메인화면으로 이동하게 되는데
이 경우 로그인 이벤트 스크립트를 메인 페이지에 삽입하면
사용자가 로그인을 수행한 경우에만 이벤트 수집이 되는걸까요?

**Comment by extJo** [comment]
로그인 이벤트 스크립트를 로그인 버튼이 누를때 동작하도록 작성하시면 됩니다
