### ISSUE TITLE
[QUESTION] 안녕하세요 당근 전환추적 연동 가능한 호스팅사인지 문의드립니다.

### ISSUE THREAD

**Issue by juyeongEee** [daangn/karrot-conversion-tracker-tool-support#89]
**Describe the question**
A clear and concise description

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

안녕하세요 

자사몰 운영중인 업체이며 호스팅사를 후이즈(https://whois.co.kr/) 로 사용중입니다.

해당 호스팅사도 당근 전환 추적 연동이 가능한지 문의드리며,

가능하다면 카페24와 동일하게 스크립트 설치를 진행해야되는지도 문의드립니다.

**Comment by extJo** [comment]
당근 스크립트를 설치해서 수집이 확인되면 문제없을것으로 보입니다~
호스팅 서비스가 다르니, 구매나 장바구니 담기 수집에 담기는 데이터를 추출하는 방법이 다를 수 있으니 해당 업체의 API를 참고하셔서 수집하시면 될거같습니다
