### ISSUE TITLE
[QUESTION] 카페24 구매 전환 이벤트 스크립트 문의

### ISSUE THREAD

**Issue by runcat1** [daangn/karrot-conversion-tracker-tool-support#9]
**Describe the question**
A clear and concise description

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

안녕하세요.

<script>
window.karrotPixel.track(
  'Purchase', 
  {
    'total_price': '{$total_product_price}',
    'total_quantity': '{$product_quantity}',
    'products': [{
      'id': '{$order_id}'
      'name': '{$product_name}',
      'qunatity': '{$product_quantity}',
      'price': '{$product_price}'
    }]
  }
)
</script>

일전에 전달해주신 카페24 모듈리스트 활용하여 구매 전환 스크립트 삽입하였는데 전환 수집이 일어나지 않아 문의드립니다.
아을러  네이버 페이 결제 전환 추적도 가능한지 문의드립니다.

{$naver_mileage_used_amount}<<네이버 페이 관련 카페24 모듈리스트 정보 전달드리며 관련해서 당근마켓 픽셀 값 중 네이버 페이 리턴값이 있는지 문의드립니다.

**Comment by Gummybearr** [comment]
안녕하세요 :) 첨부해주신 스크립트에 콤마가 빠져있는 것으로 보입니다.
```js
products': [{ 'id': '{$order_id}', ...후략
```
콤마를 삽입 한 이후에도 문제가 발생할 경우 이 스레드를 통해 알려주세요.

감사합니다.

**Comment by Gummybearr** [comment]
2주간 stale해서 닫을게요 문제가 있다면 다시 열어주세요
