### ISSUE TITLE
카페24 당근 구매전환 스크립트 설치

### ISSUE THREAD

**Issue by SHIN6564** [daangn/karrot-conversion-tracker-tool-support#90]
카페24에 당근 구매전환 스크립트 설치를 하려하는데 설치위치와 아래 ' ' 표시된 부분은 변수를 어떻게 설정해야하나요?

<script>
window.karrotPixel.track(
  'Purchase', 
  {
    'total_price': '{구매금액}',
    'total_quantity': '{구매수량}',
    'products': [{
      'id': '{상품ID}',
      'name': '{상품명}',
      'quantity': '{상품수}',
      'price': '{상품가격}',
    }]
  }
)
</script>

**Comment by extJo** [comment]
카페 24 API를 참고하셔서 해당 값을 채우시면 됩니다~!

**Comment by SHIN6564** [comment]
혹시 카페24에 아래 스크립트를 장바구니 페이지에 심었는데 수집이 되지 않는데 왜그럴까요



--
  | <script>
  | window.karrotPixel.init('1718179949162200001');
  | window.karrotPixel.track('AddToCart');
  | </script>
  |

**Comment by extJo** [comment]
도메인 등록이 정상적으로 되어있는지 확인이 필요합니다!
또한 공통 스크립트가 잘 적용되어있는지 확인해보시길 바랍니다
