### ISSUE TITLE
회원가입 전환 추적 관련 문의

### ISSUE THREAD

**Issue by mad-sol** [daangn/karrot-conversion-tracker-tool-support#91]
**문의 사항**
- 현재 '회원가입'을 목표로 캠페인을 운영하고 있습니다. 가입 전환이 당근 대시보드에서는 5건 미만으로 거의 잡히지 않는데 반해, 구글 애널리틱스에서는 300건 정도로 집계되고 있습니다. 전체 전환이 수집되지 않고 있는 듯 하여, 어떻게 조치하면 될지 문의 드립니다.

**광고 계정**
- 계정명: 유플닷컴_디지털채널(cxm)
- ID: 2846177
- 광고 집행 기간: 24/6/3 00:00 - 현재

**Comment by extJo** [comment]
대시보드가 어느 대시보드를 말씀하시는걸까요? 광고 성과 대시보드일까요 아니면 전환추적도구 대시보드일까요?

**Comment by mad-sol** [comment]
광고 성과 대시보드입니다.
![image](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/172742262/3f74beef-b6c6-49ef-b845-952659d5550e)

**Comment by extJo** [comment]
랜딩확인결과 모바일인경우 모바일 m.lguplus.com ~~ 으로 이동하는걸 확인했습니다.
전환 추적도구에 해당 도메인도 추가부탁드립니다.

**Comment by mad-sol** [comment]
확인 감사합니다.
연동 웹사이트 url에 아래처럼 추가했는데요, 추가 작업은 필요 없을까요?
![image](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/172742262/9ea0fee4-4c0d-4a41-b71d-c098edbf4559)

**Comment by extJo** [comment]
네 맞습니다. GA는 utm을 기준으로 분석할것으로 예상되는데요, 당근 리포트 상에 수집되는 내용은 픽셀이 수집하는 내용으로써 analytics 제품으로 수집한 수와 상이할 수 있습니다.
