### ISSUE TITLE
구글 태그 매니저를 통해서 전환스크립트 구현하려고 합니다. 

### ISSUE THREAD

**Issue by good11010** [daangn/karrot-conversion-tracker-tool-support#92]
구글 태그매니저를 통해서 전환 스크립트를 구현하려고 합니다. 
개발자는 아니고 마케터 입니다. 
관련해서 가이드가 있을지 문의 드립니다. 

감사합니다.

**Comment by extJo** [comment]
아직 GTM을 위한 공식 가이드는 없습니다. 
다만 이전에 GTM관련 문의로 답변나간 부분들은 있으니 참고하셔서 연동하시면 될것같습니다.

- https://github.com/daangn/karrot-conversion-tracker-tool-support/issues/67#issuecomment-2017170876
- https://github.com/daangn/karrot-conversion-tracker-tool-support/issues/47#issuecomment-1823978912
