### ISSUE TITLE
[QUESTION] 당근마켓 스크립트 gtm 연동 

### ISSUE THREAD

**Issue by jaewonlee823** [daangn/karrot-conversion-tracker-tool-support#93]
**Describe the question**
A clear and concise description

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

당근마켓 전환 추적 스크립트 (회원가입, 장바구니담기, 구매) 
gtm을 통해서 삽입하였는데요. 

계속 연동이 확인이 안되어서 
확인 부탁드립니다. 
![Uploading 화면 캡처 2024-06-19 171023.png…]()

**Comment by extJo** [comment]
이미지가 보이지않는데요, 해당 내용 일단 참고부탁드립니다
https://github.com/daangn/karrot-conversion-tracker-tool-support/issues/92

**Comment by jaewonlee823** [comment]
<img width="892" alt="화면 캡처 2024-06-19 171042" src="https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/173244820/30bf6f81-b693-4988-9b46-c9f698d03d71">
<img width="728" alt="화면 캡처 2024-06-19 171023" src="https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/173244820/3968b2a0-adaf-42be-a379-27445453e5cb">


이미지 재첨부드립니다. 
페이지뷰(방문)까지는 당근마켓에서 수집중이라고 확인이 되는데요.
회원가입이나 구매는 따로 확인이 되지 않고 있습니다.

**Comment by extJo** [comment]
1. 구매와 관련된 데이터가 주입 될 수 있도록 직접 수정하셔야합니다.
2. 모든 태그에 공통 스크립트를 포함해서 작성해주시길 바랍니다

**Comment by jaewonlee823** [comment]
1. 구매 관련된 데이터는 제외하고 구매 이벤트만 트래킹 하고 싶다면
 
<script>
window.karrotPixel.track('AddToCart');
</script>


위의 스크립트만 구매완료 페이지에 삽입하면 될까요?

2. 모든 태그에 공통 스크립트 포함해서 작성하시라고 한다면

  상단에 공통 스크립트 
<img width="428" alt="화면 캡처 2024-06-20 114937" src="https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/173244820/d119f5d8-fda8-40a1-99a0-60f9e86498e0">

이걸 삽입 우선적으로 하고 하단에 트래킹 원하는 이벤트 스크립트를 삽입하면 될까요?

**Comment by jaewonlee823** [comment]
<img width="183" alt="화면 캡처 2024-06-20 115037" src="https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/173244820/97f4fbe4-8837-47a1-a00b-a843d4571c22">

1. 에 말씀드린 스크립트는 위의 껄로 확인 주시면 감사드리겠습니다.

**Comment by extJo** [comment]
1. 네 맞습니다
2. 네 맞습니다

**Comment by extJo** [comment]
@jaewonlee823 답변이 충분히 되었을까요?
