### ISSUE TITLE
[QUESTION] GTM의 구매 이벤트 설정 시 이벤트 파라미터 값 설정에 대해 문의  드립니다. 

### ISSUE THREAD

**Issue by good11010** [daangn/karrot-conversion-tracker-tool-support#94]
안녕하세요. 현재 GTM으로 당근광고스크립트를 셋팅 중에 있습니다. 
기존에 GTM에 셋팅된 이벤트를 트리거로 설정해서 이벤트 스크립트를 설정하고 있는데요. 
이벤트 파리미터 값을 설정하는 방식에 대해 문의를 드리고자 합니다. 

![GA4_구매이벤트 테이블](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/173243416/66b1317c-e437-4e35-8477-75468a5f7e7a)

![당근광고_구매태그](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/173243416/442d03a4-9cc2-43c5-b11d-4453e30d7d4a)

GA4의 이벤트 필드의 정보를 당근구매태그와 매칭할 수 있을지요?   GTM에 맞춤 HTML를 작성할때 예를 들어  'total_price': '{구매금액}' 에 GA4 이벤트필드의 값이 들어가게 소스를 어떻게 작성해야 할지 문의 드립니다. 

감사합니다.

**Comment by extJo** [comment]
해당 내용은 GTM 문서와 GA문서를 참고하셔서 작성하시길 바랍니다.
따로 저희가 가이드 드릴 수 없는 점 양해부탁드립니다.
