### ISSUE TITLE
[QUESTION] 당근마켓 전환 스크립트 설치 오류 관련 문의

### ISSUE THREAD

**Issue by wlgl111** [daangn/karrot-conversion-tracker-tool-support#95]
**Describe the question**
A clear and concise description

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

안녕하세요.
광고계정 ID : 연세하나병원_PR(2954646)

안녕하세요.
해당 계정 전환 스크립트 설치 진행하려 하였으나,
현재 첨부된 이미지와 같이 얼랏 노출되며 전환 추적 코드 생성되지 않고 있습니다.

URL 입력 시 마지막 하이픈 제외하고 
http://www.hanahospital.com 및 www.hanahospital.com 입력 하였으나
지원하지 않거나, 잘못된 URL로 얼랏 노출되고 있습니다.

광고주 URL 은 http://www.hanahospital.com/ 해당 랜딩으로,
프로토콜 오류로 생성 불가능한 상황인지 확인 부탁드립니다.

![연세_당근_추적](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/173221928/643a752f-4314-4228-aba1-4159d14a25f0)

**Comment by extJo** [comment]
http 는 지원하지않습니다. https인 웹사이트만 연동 가능합니다

**Comment by extJo** [comment]
@wlgl111 추가 문의 내용이 있을까요?

**Comment by wlgl111** [comment]
없습니다! 감사합니다:)
