### ISSUE TITLE
[QUESTION] 스크립트 문의

### ISSUE THREAD

**Issue by incross-pm2** [daangn/karrot-conversion-tracker-tool-support#96]
**Describe the question**
A clear and concise description

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

대동 캠페인 건으로 아래와 같이 태그를 삽입했습니다.
처음엔 방문 유저가 전환 유저보다 훨씬 많고 정상 측정되어 이상 없는 것으로 생각했는데요.
최근 방문 유저=전환 유저 규모가 거의 유사해서 전환 태그가 잘못 삽입된 것으로 예상됩니다.
혹시 태그에 이상 있는지 확인 부탁드립니다.

[방문 페이지- head와 /head 사이]

<script src="https://karrot-pixel.business.daangn.com/0.2/karrot-pixel.umd.js"></script>
<script>
  window.karrotPixel.init('1715048020653400001');
  window.karrotPixel.track('ViewPage');
</script>

[전환 페이지- head와 /head 사이]

<script>
window.karrotPixel.track('Lead');
</script>

**Comment by extJo** [comment]
전환 페이지에 진입할때만 Lead로 입력한 스크립트가 동작하게 작성하셨을까요?

**Comment by incross-pm2** [comment]
> 전환 페이지에 진입할때만 Lead로 입력한 스크립트가 동작하게 작성하셨을까요?

맞습니다

**Comment by extJo** [comment]
설치한 사이드 url 첨부 부탁드립니다

**Comment by incross-pm2** [comment]
> 설치한 사이드 url 첨부 부탁드립니다

사이드 url이 어떤 건지 알 수 있을까요?
우선 저희 트래킹 링크 공유드립니다
https://ko.daedong.co.kr/event?utm_source=app&utm_medium=event&utm_campaign=interest_customers&utm_id=gx&utm_content=app_danggeun

**Comment by extJo** [comment]
해당 페이지 방문시에도 Lead가 호출되는데, 스크립트를 정확히 설치하셧는지 확인 부탁드립니다

**Comment by incross-pm2** [comment]
> 해당 페이지 방문시에도 Lead가 호출되는데, 스크립트를 정확히 설치하셧는지 확인 부탁드립니다

확인하고 말씀드리겠습니다
아래 태그대로 삽입되었다면 이상 없을까요?

[방문 페이지- head와 /head 사이]
<script src="https://karrot-pixel.business.daangn.com/0.2/karrot-pixel.umd.js"></script> <script> window.karrotPixel.init('1715048020653400001'); window.karrotPixel.track('ViewPage'); </script>

[전환 페이지- head와 /head 사이]
<script> window.karrotPixel.track('Lead'); </script>

**Comment by extJo** [comment]
네 다만 전환페이지에도 공통 스크립트는 동일하게 설치되어있어야합니다.

**Comment by incross-pm2** [comment]
공통 스크립트는 아래 방문 스크립트 말씀이실까요?!

<script src="https://karrot-pixel.business.daangn.com/0.2/karrot-pixel.umd.js"></script> <script> window.karrotPixel.init('1715048020653400001'); window.karrotPixel.track('ViewPage'); </script>

**Comment by extJo** [comment]
네 맞습니다

**Comment by extJo** [comment]
@incross-pm2 추가문의 있으실까요?
