### ISSUE TITLE
[QUESTION] 당근 전환 스크립트 관련 문의 

### ISSUE THREAD

**Issue by cross-md** [daangn/karrot-conversion-tracker-tool-support#97]
**Describe the question**
A clear and concise description

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

현재 전환(서비스신청) 캠페인 운영중으로, 하기 랜딩페이지 하단 [카카오톡 1초 비용확인] 버튼 클릭시 전환수로 집계되도록 
랜딩> 블랭크 페이지>카카오 채널로 이동하는 경로에서 블랭크 페이지에 스크립트 설치해둔 상태인데요, 
우측 [무료상담 바로신청]  버튼 클릭시 동일한 스크립트가 설치되어 있어 전환이 중복 집계될 듯한데 
[카카오톡 1초 비용확인] 전환건수만 따로 트래킹하려면 스크립트를 변경하여 진행이 필요한지 확인 부탁드립니다. 

![365MC_랜딩페이지](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/173768406/e10614a0-1c01-4edb-a601-b21a8c9586d5)

**Comment by extJo** [comment]
카카오톡 1초 비용확인을 눌렀을 때 스크립트가 동작하도록 작성하시면 됩니다.
[비슷한 문의 전달드립니다](https://github.com/daangn/karrot-conversion-tracker-tool-support/issues/54#issuecomment-1835557646)

**Comment by cross-md** [comment]
스크립트는 동일하게 하기 서비스 신청 스크립트로 진행하면 될까요? 
다른 버튼 클릭시 전환이 중복 집계되지 않을지 확인 부탁드립니다. 


<script>
window.karrotPixel.track('SubmitApplication');
</script>

**Comment by cross-md** [comment]
![스크립트](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/173768406/d2b86cdd-5a90-47f6-9dfa-4b12b2dca7d5)

**Comment by cross-md** [comment]
위 내용 빠르게 확인 부탁드려도 될까요?

**Comment by extJo** [comment]
네 해당 스크립트를 동작하도록 삽입하시면 됩니다.

**Comment by cross-md** [comment]
확인 감사드립니다! 상기 랜딩페이지 하단 버튼 각 이벤트에 따라 전환값 구분하고자 SubmitApplication / Lead 이벤트로 구분하여 설치한 상태인데, 정상 작동 여부 확인 부탁드립니다! 
- 하단 좌측 배너[카카오톡 1초 비용확인] - Lead
- 하단 우측 배너[무료상담 바로신청] - SubmitApplication

**Comment by cross-md** [comment]
위 내용 빠른 확인 부탁드려도 될까요?

**Comment by extJo** [comment]
확인 가능한 링크 전달부탁드립니다

**Comment by cross-md** [comment]
https://incheon.365mc.com/landing_m/Y22/D1104_ic.php?route=ICCARROT_BC&src=image&kw=0008AA 

위 링크로 확인 부탁드립니다! 감사합니다

**Comment by extJo** [comment]
클릭 이벤트가 동작될 때 픽셀 발행이 안되는거같은데요. 다시한번 확인 부탁드립니다

**Comment by cross-md** [comment]
현재 픽셀 설치된 점 체크했습니다! 위 링크로 다시 확인 부탁드려도 될까요?

**Comment by extJo** [comment]
카카오톡으로 넘어가는 경우에는 저희측에서 확인하기가 어려운거같아보입니다. 일단 SubmitApplication 이벤트는 잘 발행되는것으로 보아 이상 없을걸로 생각됩니다

**Comment by extJo** [comment]
@cross-md 추가문의 있을까요?

**Comment by cross-md** [comment]
담당자님, 추가 문의 사항이 있어 코멘트 드립니다. :) 

현재 하기 랜딩페이지에서  하단 고정배너 (카카오톡 1초 비용확인/무료상담 바로신청) 버튼 클릭시 플랫폼상 전환수는 정상 집계되고 있는 것으로 확인되나, 랜딩페이지 중간에 있는 배너 버튼 클릭시 전환 이벤트가 집계되고 있지 않은 듯 하여 정상적으로 설치 및 작동되고 있는 상태인지 확인 요청드립니다! 
랜딩페이지 : https://incheon.365mc.com/landing_m/Y22/D1104_ic.php

![365mc_전환이벤트3](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/173768406/a7194c4c-b0fb-411b-ac25-8d291a2dff6e)
![365mc_전환이벤트2](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/173768406/b0837b57-9370-4d54-96d5-7c52e28f5cb9)
![365mc_전환이벤트1](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/173768406/0c262422-7ef6-467a-b597-7f4c2a879860)

**Comment by cross-md** [comment]
안녕하세요 담당자님 :) 위 문의드린 사항 확인 가능하실까요?
