### ISSUE TITLE
[QUESTION] 당근 전환 스크립트 작동여부 관련 문의

### ISSUE THREAD

**Issue by cross-md** [daangn/karrot-conversion-tracker-tool-support#98]
**Describe the question**
A clear and concise description

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

현재 하기 랜딩페이지에서 하단 고정배너 (카카오톡 1초 비용확인/무료상담 바로신청) 버튼 클릭시 플랫폼상 전환수는 정상 집계되고 있는 것으로 확인되나, 랜딩페이지 중간에 있는 배너 버튼 클릭시 전환 이벤트(SubmitApplication)가 집계되고 있지 않은 듯 하여 정상적으로 설치 및 작동되고 있는 상태인지 확인 요청드립니다! (하단 이미지 참고 부탁드립니다.) 
> 랜딩페이지 : https://incheon.365mc.com/landing_m/Y22/D1104_ic.php

![365mc_전환이벤트1](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/173768406/de85b1f6-87fb-4b02-ad29-dc1b0fcf3687)

![365mc_전환이벤트2](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/173768406/be9c005f-1de7-4ccc-b0d6-d140c5c98c8a)

![365mc_전환이벤트3](https://github.com/daangn/karrot-conversion-tracker-tool-support/assets/173768406/209d4d04-0710-4649-b931-8c0a9f0a4381)

**Comment by extJo** [comment]
스크립트 정상 설치 유무는 직접 확인 하셔야합니다~!
설치 전체를 다 도와드릴 수 없는 점 양해부탁드립니다
