### ISSUE TITLE
[QUESTION] 구매 이벤트 스크립트 오류 문의

### ISSUE THREAD

**Issue by dnjstlr801** [daangn/karrot-conversion-tracker-tool-support#99]
당근 매체에 광고를 운영하고자, 구매 이벤트 스크립트를 설치하였는데요,
데이터 트래킹이 되지 않아, 문의 드립니다!!

당근 측에서 제공하는 스크립트 가이드는 아래와 같은데요.

<script>
window.karrotPixel.track(
  'Purchase', 
  {
    'total_price': '{구매금액}',
    'total_quantity': '{구매수량}',
    'products': [{
      'id': '{상품ID}',
      'name': '{상품명}',
      'quantity': '{상품수}',
      'price': '{상품가격}',
    }]
  }
)
</script>

실제 저희 측에서 삽입한 스크립트 코드는 [스크린샷] 부분에 첨부하였는데,
제가 봤을 때는 매체측 가이드에서 제공한 내용에는 products 뒤 대괄호 앞뒤로 ' 표시가 확인되지 않는데
실제 심어져 있는 스크립트에서는 products 부분에서 ' 표시가 확인되고 있어서 발생한 이슈일 수도 있다고 생각하는데요~

상기 내용으로 인한 오류일까요?
아니면 추가 수정해야할 부분이 있을까요?

![삽입 구매 이벤트 스크립트](https://github.com/user-attachments/assets/286e186a-d34f-487c-b116-b3be055c2c29)

**Comment by extJo** [comment]
> 제가 봤을 때는 매체측 가이드에서 제공한 내용에는 products 뒤 대괄호 앞뒤로 ' 표시가 확인되지 않는데
실제 심어져 있는 스크립트에서는 products 부분에서 ' 표시가 확인되고 있어서 발생한 이슈일 수도 있다고 생각하는데요~

실제 심으신 코드가 잘못되신거같습니다~! 빨간 박스 치신 부분을 삭제해주시면 될거같습니다
